### ISSUE TITLE
City building culling could be more efficient

### ISSUE THREAD

**Issue by Luomu** [pioneerspacesim/pioneer#1058]
This is done currently using the building's collision mesh bounding radius (actually it seems to be extent/diameter and not radius) and frustum::TestPoint. Tall buildings are not even close to being spherical, so when a tall building disappears off the edge of the screen it may still be "drawn". Adding a bounding box check to Frustum would be more suitable.

**Comment by impaktor** [comment]
Things have progressed over the past 3 years.  What's our status here, @fluffyfreak?  (sorry for spamming you today).

**Comment by fluffyfreak** [comment]
I did look into improving the culling but ditched it in the end. 
Since then I made building rendering use instancing which has dramatically improved performance even if we are drawing more building than we need too.

It becomes a tradeoff, spend more time on the CPU doing additional culling, but do you gain anything in rendering performance if that's now so fast anyway?

I think we can close this until we have things like shadows which might make fillrate and GPU performance a potential bottleneck when a bit more precise culling could be useful.
