### ISSUE TITLE
LOD of stars

### ISSUE THREAD

**Issue by Zordey** [pioneerspacesim/pioneer#1834]
Easily seen when in deep space, when nothing is on screen then 0 triangles are registered. When a star is visible on screen triangle count jumps to over 140k triangles.

In this example I have just jumped into Sol, external view, 2286 triangles visible
![Screenshot from 2012-12-18 23:01:28](https://f.cloud.github.com/assets/1453261/20802/25cc43c4-496a-11e2-9f5e-c5bb04669e87.png)

Turn a few pixels to bring Sol on screen and triangle count jumps to 142254 even though it is merely a few pixels on screen
![Screenshot from 2012-12-18 23:01:20](https://f.cloud.github.com/assets/1453261/20817/8f314616-496a-11e2-95fd-9bf11212c3d1.png)

**Comment by impaktor** [comment]
> We really need to draw billboards or spikes for distant stars. 

@robn Didn't you do that 1-2 years ago? @fluffyfreak did #3428, I leave it to you two to close this issue.

**Comment by fluffyfreak** [comment]
I think that there's a few things we need to do here.
1. Render-to-texture Billboard replacements for stars.
2. Specific star class derived from BaseSphere like GasGiants are with simplified rendering.

There's no reason for stars to need 140,000 poly's anyway :/

**Comment by fluffyfreak** [comment]
I had a hack at this tonight, it's a bit of a bugger because of the way that stars are drawn.

They have a nasty static halo around them that is 8 times the radius of the Star itself but is alpha blended. This means that "they" are actually the star + halo in pixels on screen so they're nearly always visible from any distance and thus the full planet gets rendered.

**Comment by corundscale** [comment]
Would it be possible to change the way distant objects are drawn in general? A bright object (star, sunlit planet, sunlit spaceship, etc.) against a dark background is going to be visible as a point of light even if it's way below your resolution and will stay this way until it gets too faint, not too small so distant objects should get static size billboards that only change in brightness with distance and stop being drawn if they fade to 0.

As for the nasty static halo, I think it should be replaced with glare.
Maybe reuse the halo itself for corona.

**Comment by fluffyfreak** [comment]
@corundscale you want to be looking in `Camera::Update` and `Camera::Draw` for the code that decides to draw a billboard or not.

As I say it's tricky for the Stars, and I have tried before, because of that halo which is so visible. One option would be to draw a halo or to change the star rendering entirely.

Stars maybe only need the rendering system of a gas giant (*fixed sphere*), plus halo/aurora which would stop them using so many triangles at least.

**Comment by corundscale** [comment]
I think that at least one kind of stars should get proper "terrain" - red giants which are currently understood to be dominated by few massive convection bubbles. 

Thankfully they move too slowly for Pioneers lack of animated terrain to be an issue and old asteroids could end up with [remarkably similar tertrain](http://spacesimcentral.com/ssc/topic/2116-wanted-new-screenshots/?p=54114).

**Comment by fluffyfreak** [comment]
Maybe but you wouldn't see anything due to the blinding intensity of the light anyway :)
All i really mean is there's a bunch of things that could really do with looking at and some serious thinking and discussion because of the interlinked problems.

**Comment by corundscale** [comment]
Actually I'm not sure about this light intensity - red giant are luminous but they are also very large, spreading this luminosity around large area. They are also much cooler than Sol.

Even if they would still be hard to look at directly you would be able to see the irregular outline and they would also be sufficiently dimmed to see clearly when viewed through a sufficiently thick or "dirty" atmosphere - I have seen sunsets IRL where the sun was sufficiently dimmed to be looked at not just with naked eye but through binoculars without discomfort (I don't think I need to say how bad idea that is under normal circumstances).

**Comment by fluffyfreak** [comment]
Well one option for current the stars would just be to limit their maxDepth to 1 or 2 instead of allowing it to go upto 16 or 20 deep! That'd stop it from using so many triangles anyway.

We do have shape for the stars already, that's how you get the elliptical fast spinning ones, worth checking out if you wanted to use some of the noise functions for red giants or something.

**Comment by richardpl** [comment]
Haven't this been fixed?

**Comment by fluffyfreak** [comment]
Well, technically yes something was done about this, however you do still get planets, stars, etc all rendering at big distances still with potentially very high poly counts.

**Comment by mike-f1** [comment]
@fluffyfreak : in function `Camera::Update` :

https://github.com/pioneerspacesim/pioneer/blob/b2258e261bb47fbb30908dbe018fda1134651ea3/src/Camera.cpp#L139-L163

...and in function  `Camera::Draw` :

https://github.com/pioneerspacesim/pioneer/blob/b2258e261bb47fbb30908dbe018fda1134651ea3/src/Camera.cpp#L253-L262

...thus (...if I'm reading that thing correctly...) that code will render things only when they are over 8 pixels of heigth on screen...

Closing? ;)

**Comment by fluffyfreak** [comment]
Since star rendering in general needs quite a lot of work, sure this can be closed.

**Comment by mike-f1** [comment]
@fluffyfreak , it's in my sight: if you think what I sketched in #4402 could be suitable, I may start working on it...

Better sayd:
1) Create `StarSphere: public BaseSphere`
2) "Copy-paste" some code from `GasSphere`
3) "Copy-paste" some code from `GeoSphere` and
4) limit the number of depth level and the number of triangles for each patch

...And that should be enought, isn't?

**Comment by fluffyfreak** [comment]
@mike-f1 yes something like that, it need the height so that it can support ellipsoid stars rather than anything else.

When I said that it needs a lot of work it needs all of that plus I was thinking of using billboards to represent a constantly moving swarm around the star itself, and meshes with UV animated textures on them to represent solar flares, loops, etc.

Also of course it should really melt you're ship within a few minutes/seconds if you get too close à la: http://www.thetenthplanet.de/archives/4062

**Comment by mike-f1** [comment]
> [....] it need the height so that it can support ellipsoid stars rather than anything else.

Oh, I didn't realize that... But it still need less vertex and patches for sure :)

> When I said that it needs a lot of work it needs all of that plus I was thinking of using billboards to represent a constantly moving swarm around the star itself, and meshes with UV animated textures on them to represent solar flares, loops, etc.

Yeah! That's a **LoT** of works :sweat_smile: ...But sure the effect will be great!

Anyway let me know when or if you will begin: I don't want to shot on your feet.
