### ISSUE TITLE
numbers on the screen

### ISSUE THREAD

**Issue by Azimech** [pioneerspacesim/pioneer#218]
When having selected a target with a large distance, you often see a list of numbers beyond a practical limit of the brain. I often can't read the the super fast changing strings of numbers and make mistakes of large proportions. 
There is no point in having a distance of hundreds of thousands of kilometers, having even the decimals shown.

For readability the game already switches from 14959787070 (you get the issue now ;-) ) to 0.1 AU, how about something similar for the smaller values: 14.9 Mkm, 1.49 Mkm, 0.149 Mkm, and decimals only shown with distances under 10 km.

**Comment by Wuzzy2** [comment]
Mkm? Seriously? No, just no. Such a suggestion clearly comes from someone who is not familiar with the SI system. :P

I am in favor of:

* m = 1 meter
* km (kilometer) = 1000m
* Mm (megameter) = 1,000,000m
* Gm (gigameter) = 1,000,000,000m
* Tm (terameter) = 1^12 m
* Pm (petameter) = 1^15 m
* Em (exameter) = 1^18 m

This is just based on the SI system (no silly ad-hoc inventions), so it should be more or less clear. Please mind the case, it matters! (so no “KM” or “MM” or “Km” etc. Also “mm” would be millimeter, of course. ;-) ). 
Look here for a full list of SI prefixes: https://en.wikipedia.org/wiki/Metric_prefix

I doubt we ever need extreme values like zetameter (1^21 m) or yottameter (1^24 m) because the circumference of the game universe is about 8000 ly = 75685843780646400000 m or approx. 75 Em.

But I think there are still people who are comfortable with AU. IMO the best solution would be to make this a menu option where you can select from different distance units.

I suggest the following options:

* m, km, AU, ly. (This is what the game is using right now, I am not sure how to call this setting, “astronomical” maybe?)
* SI units only (which I just described) (m, km, Mm, Gm, …)
* Maybe: Display lengths in meters, but as appropriate exponential (e.g. “300³ m”)
* Maybe: Scientific notation, based on meter (e.g. “3.543E6 m” for 3543000 m)
* If you are interested in other units, please post them

**Comment by impaktor** [comment]
I think ly, (parsec), km and AU are the most obvious units. All other are uncommon, and not clear, as Mm, Gm, etc. are never actually used (correct me if I'm wrong), and we lack intuitive feeling for them. I don't know how many Mm/Gm/km it's out to Pluto, or from Earth to Sol, but I do know it's 40 AU, and 1 AU, respectively. I think I'm at a common level for a space-game player.

I think a better solution is when the distance is too small to be shown in AU, to round off, maybe like 1.67 1e6 km, instead of 1.67 Gm, or 1671342 km.

If someone want's to implement your strict SI metric prefix-system, and make that optional, fine by me.

**Comment by fluffyfreak** [comment]
Mm is more common, used in Elite Dangerous for example and because of the situation I knew immediately what it meant despite never having seen it before.

**Comment by impaktor** [comment]
@fluffyfreak 
So, you say yes to AU -> Mm -> km? No Gm, Tm, Pm?

**Comment by Wuzzy2** [comment]
I think the current system could be kept as default (maybe with some tweaks to get rid of very large numbers of km, I don't know), with the strict SI system as an alternative option (and maybe other systems later, should they be desired).

Simply because ly and AU are more common, but I think the other system has its merits as well, even if units like Gm are uncommon. It is still entirely “legal” under SI rules. ;-)

**Comment by fluffyfreak** [comment]
I'm just saying that it's more familiar than you'd expect and that perhaps another step of AU -> Mm -> km would be ok. 
You can take it too far (_Gm, Tm, Pm_) which might just add confusion.

@Wuzzy2 if you want to try adding this feature then I'd be happy to review it, and if it is optional as you suggest, then perhaps merge it - depending on the code and functionality etc obviously :)

**Comment by impaktor** [comment]
This is a very easy fix, for anyone who want's to start poking the pioneer code.

See `format_distance()` in src/utils.cpp. Add Mm, and scientific notation, if needed. 

If no one goes at it, I can do it in the comming week, provided I can get pioneer to compile again.
