### ISSUE TITLE
Ridiculous missions

### ISSUE THREAD

**Issue by Cosm1cGam3r** [pioneerspacesim/pioneer#2898]
I took 2 missions to deliver packages to MU Herculesi

Hyperjumped there and... for first package I got 20 days and for second one I got 32 days.

Then I checked distances. For that 32 day deadline package I had to travel 113 AU !
That with 20 days deadline was only 3539.81 AU..........

Yes thanx for putting me in mission REALLY impossible! lol

I tried to deliver that 32 day deadline one to that 113 AU away base. That took my little ship 3 f....reaking months! It would be faster to hyperjump there!

Not even mentioning that 3539 AU that I will not even dare to try to finish !

You guys really must forgot that F:E2 system of hyperjumps and create some other way that would hyperjump us no further than 10-20 AU from selected planet. And If star system is insanely huge we should have option to hyperjump to other planet that is on orbit on other star in same star system. Or even hyperjump from one planet to other planet that are further away than 50 AU

Otherwise that game is not making any sense.

That packages was worth about 1.100 credits. Who would spend 3 months to earn that silly money? 

I tried to play fair but after that silly distances I am planing to load before that jump and just ignore that packages. How to throw them away and lose reputation that way instead of spending hours of my real life to get to planets that are away like 100+ AU not mentioning that insane 3539 AU !

It was pain to wait to get to that 113 AU and read message how they are mad that I was late. lol Imagine pilot that spent 3 months to travel just to be flipped off and not paid that pathetic 1100 for that insane job :)

 I wonder if there would be some insane player to check how long it would take to travel 3539 AU. I can only guess. Maybe more than 3 in game years and real life hours about 8? LOL

Seriously think about making more believable travel system. I loved F:E2 but with years that passed I wonder if that month travels for few hundred credits was even making any sense :)

**Comment by osjc** [comment]
> So, the "physical law" that jump engines have a minimal jump distance still hold :)).

Well, I heard rumors about star systems where objects are like 14064.6 AU away from each other ("Falaphi", though I could not find it). Or even like 34265 AU. So I did some back-of-the-envelope calculations:

1 AU = 8 light minutes (assuming AU=150 mil km and c=300000 km/s)
14064.6 AU = 112516.8 light minutes = 1875 light hours = 78 light days = 0.21 light year
34265 AU = 274120 light minutes = 4568.7 light hours = 190.36 light days = 0.52 light year

Well, if such systems really do exist (especially the 34265 AU one) and there are two different systems closer together than 0.5 l.y., then your "physical law" is wrong.

So a better "handwave" would be that the "hyperjumping possibility" depends on the universe between the potential source and target being "favorably folded" to allow jump between two points of an universe. Thus two systems even though they are e.g. 20 l.y. apart in 3D space could actually be just only about 20 light days apart in 4D space. On the other hand two far away locations within the same system could be not much closer in 4D space either due to e.g. gravity (gravity could be stretching the part of the universe affected by it flat, leading to the impossibility to do straight intrasystem jumps).
