### ISSUE TITLE
decapitated scanner blobs?

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#3103]
I think this is more noticeable in the new smaller scanner, but I'm not sure we want to decapitate the lines in this way, or do we? I guess they aught to be cut at some point, or?

**Left:** blob out side of sphere, **Right:** blob inside sphere.
![scanner](https://cloud.githubusercontent.com/assets/619390/3762896/31ba9e6c-189c-11e4-8808-38b35aa8e280.png)

Maybe it's just me being silly.

**Comment by impaktor** [comment]
I don't know, I kind of don't like the current angle the compact-scanner is displayed at. I think it's a bit too much from above, and our non-compact scanner is too much in the other direction, so it's viewed at a very low "altitide" from the plane. I think I like the scanner of Elite The New Kind the best. I wonder what the major and minor axis are in these ellipses.

In __Elite The New Kind__ it looks like:
![the new kind](https://cloud.githubusercontent.com/assets/619390/11912880/aeb3d868-a651-11e5-99bc-e211b2ac0c14.png)

In __Elite+__:
![elite+](https://cloud.githubusercontent.com/assets/619390/11912892/c5e77184-a651-11e5-8559-570725c3cc8c.jpg)

In __Oolite__:
![oolite](https://cloud.githubusercontent.com/assets/619390/11912895/d414b168-a651-11e5-9cb3-db8f4671fc61.png)

And in __Frontier__ it's very much from the "side", or viewed from a low distance above the plane:
![frontier](https://cloud.githubusercontent.com/assets/619390/11912901/0e84fa10-a652-11e5-80e8-154b266b90e8.jpg)

And in __Pioneer__ with "non-compact" scanner option:
![pioneer](https://cloud.githubusercontent.com/assets/619390/11912908/7f56ae50-a652-11e5-962a-7e3a205a27c4.png)

**Comment by nozmajner** [comment]
I guess it might be because Pioneers scanner is orthographic (Oolite too), but those examples from Elite and Frontier all seem to be in perspective.
An example of both, viewed from the same point of view:
![scanner_comparison](https://cloud.githubusercontent.com/assets/4182678/11913394/ab1b02ec-a662-11e5-9feb-32296d0cb532.png)
But on the other hand some of those Elite scanners seem to be cheating with that perspective, and only that grid might really be in perspective, because in some the horizontal center line is at halfway, but it actually should be a bit upper, because in perspective, the axis of the circle and the resulting ellipse doesn't line up:
![scanner_both_](https://cloud.githubusercontent.com/assets/4182678/11913446/76980d2e-a664-11e5-9c89-4ab7ad27a14b.png)
Frontier and New Kind seems to have a truly perspective scanner. Both appear to be cheating anyway, since the perspective of the grid and the ellipses seem to be quite different. Like in Frontiers case there are 8 grid lines towards to sides, but only 4 towards the front and back, but actually there should be the same number. The New Kind seems to be more precise in this regard, but still seems off a bit.
It should look something like this:
![scanner_newkind](https://cloud.githubusercontent.com/assets/4182678/11913526/154bd1a6-a667-11e5-8983-99de419c2c9c.png)

**Comment by impaktor** [comment]
Wow! 
Great explenation, thanks!

**Comment by impaktor** [comment]
So, just to be clear, the actual issue we're tracking here is that maybe the scanner plane should be the cross section of a cylinder rather than a sphere, with ships far above the plane have the distance logarithmicly scaled or clamped.

**Comment by nozmajner** [comment]
Is this/these are still an issue?

**Comment by impaktor** [comment]
> Is this/these are still an issue?

Well, it still happens, I think, since scanner code is unchanged, but this is getting less relevant considering the new IWAR/freespace-scanner.

**Comment by Web-eWorks** [comment]
This issue is fixed with the new PiGui planar radar.
