### ISSUE TITLE
Failed to set Video mode: Could not create GL context

### ISSUE THREAD

**Issue by McConn75** [pioneerspacesim/pioneer#3275]
Hi all.

The issue mentioned by the headline occured while trying to start pioneer.exe version 20141219-win32.
Got an older version (201309.33-win32) which is running.

My PC:
Win 7 64
AMD FX 6100 (6 cores, 3.3 GHz), 8 GB
GeForce GTX 560 Ti, 4 GB
DirectX 11

Any hints how to solve it aside: take the running version ? :)

Regards
McConn75

**Comment by fluffyfreak** [comment]
@jasondude7116 & @McConn75 have you tried the latest releases? Do they work or do you still see the same problems?

**Comment by jasondude7116** [comment]
It seems to work now and fps is much better.

**Comment by fluffyfreak** [comment]
Thanks for replying @jasondude7116 :) yeah there has been a look of optimisation since that earlier build!

**Comment by impaktor** [comment]
__Summary:__ OP has not been heard from since the first post, his graphics card should work, jasondude had similar issues, but not anymore, pioneer ran slow after opengl 3.1 (and new space stations I assume?) upgrade of pioneer, but everything works better now.

Plus there were even more optimizations merged after latest post in this issue 6 months ago, so nothing more to do here, I think. Closing.
