### ISSUE TITLE
Still strange rendering

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#3336]
So a continuation of #3308, the BBS is fixed as I mentioned there, but world view is still strange. 
(On latest master, 77bd4bb7504207b20faafee1a6835522efd74798, GNU/Linux)

![ps2](https://cloud.githubusercontent.com/assets/619390/5897511/067f86a0-a545-11e4-8b96-d4326f79c03e.gif)

**Comment by fluffyfreak** [comment]
It looks to me as though the zbuffer clearing is just not happening on Linux. Perhaps the calls to glDepthRange used to clear it but for some reason they don't anymore?

Do a quick test and find the call in the renderer where `glDepthRange` lives and after it put a call to `ClearDepthBuffer`. If that works then it's not really the optimal solution but it might suffice.

**Comment by impaktor** [comment]
Not sure I follow. As far as I can tell, `glDepthRange` is used in `graphics/opengl/RendererGL.cpp` wrapped in a `SetDepthRange` call, which in turn is used in some places in `SectorView.cpp`, which doesn't feel like the correct place for this to go wrong, since it happens without going into sector view.

Or should I muck about in `SectorView.cpp`?

**Comment by fluffyfreak** [comment]
Hmm, damn that was my best guess. Basically I don't know why but it looks like on Linux the depth buffer is not being cleared. However I can't think of anywhere that has changed. The `glDepthRange` was just my best shot in the dark.

**Comment by impaktor** [comment]
Perhaps something to do with #3306, as that does introduce changes to some of the code I looked at when following your advice.

**Comment by fluffyfreak** [comment]
I've checked that before but I can't see any reason it would fail on Linux and not on Windows. Also there's no changes to the depth clearing.

I need to try this out on a Linux machine and just debug it.

**Comment by impaktor** [comment]
Happy hunting!

**Comment by fluffyfreak** [comment]
I am now having to compile older versions to find when the problem started. I'm totally baffled by this one :/

If you can find which version it actually started with that would help me greatly.

**Comment by impaktor** [comment]
Will do.

**Comment by fluffyfreak** [comment]
Ok, I think you're right that it might come in with #3306 but I am baffled as to why. I can't see what would cause it.

**Comment by fluffyfreak** [comment]
Just trying to find the specific commit from that range to see exactly what happened, maybe that will help me figure this out.

**Comment by fluffyfreak** [comment]
@impaktor ok I can't find an intermediate commit between https://github.com/robn/pioneer/commit/84ef0d774640011340e45d2774a10e21dcb8e05c and https://github.com/robn/pioneer/commit/8b5c72155ad254aed3558c2d520a17782152fbee that will compile so it's going to be a case of figuring out why it doesn't work.

The only other likely candidate is before the #3306 commits was 81e728fb14319b8bae11e3cbd09eb03928c5b0ab by me but I tested that one and it was ok.

Could you verify my findings?

**Comment by fluffyfreak** [comment]
Looking at it, it's almost like the z-ordering is reversed.

It's too late tonight for me to do any more on this but I'll try to find some time asap.

**Comment by fluffyfreak** [comment]
Hey @robn just wanted you to know about this bug we're having, I can't fathom why it's happening so wanted to loop you in for brighter ideas :)

I had a couple of thoughts before bed last night like:
* possibly calling methods on the wrong renderer?
* compilation/linking issue when dummy renderer not in project?
* not setting depth order / range / clearing correctly?

That last one though I would expect to affect all systems but it seems to only be certain Linux machines/builds.
I'm testing the second idea right now but don't know how to test the first yet.

**Comment by impaktor** [comment]
I can confirm that 81e728fb14319b8bae11e3cbd09eb03928c5b0ab works for me.

Also, I should mention that not all Linux systems experience this bug, as @jmf confirmed last night that master works for him.

**Comment by fluffyfreak** [comment]
Do you have an AMD/Ati GPU?
What GPU does @jmf have?

I just tried it (I have AMD GPU) and it's like everything is ok for the first frame, and trashed after that.

**Comment by impaktor** [comment]
% glxinfo | grep OpenGL
    42:OpenGL vendor string: NVIDIA Corporation
    43:OpenGL renderer string: GeForce 210/PCIe/SSE2
    44:OpenGL version string: 3.3.0 NVIDIA 340.32
    45:OpenGL shading language version string: 3.30 NVIDIA via Cg compiler

**Comment by fluffyfreak** [comment]
Damn, I was starting to hope it was we could track that way.

**Comment by fluffyfreak** [comment]
Ok that's interesting, if I disable planet rendering then everything works ok. I wonder if this is state being persisted when it shouldn't.

**Comment by robn** [comment]
Is the repro is to start game, open BB, request launch, and note bits of terrain shape hanging around?

If so, its working fine here on:

* `OpenGL version 3.1.0 NVIDIA 340.65, running on NVIDIA Corporation GeForce GTX 770M/PCIe/SSE2`
* `OpenGL version 3.3 (Core Profile) Mesa 10.4.2, running on Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile`

@fluffyfreak testing the first point means just shoving calls to `abort()` in every method on the dummy renderer. But I'm beyond 100% sure that its not calling it - it wouldn't make any sense at all since there's nothing that can actually instantiate it.

**Comment by fluffyfreak** [comment]
Yeah I've eliminated everything else now. 
It's definitely the `GeoSphere` rendering. I just cannot fathom out why now :/

Nothing has changed in that section that I can see. Especially not with the dummy renderer changes. The biggest change I can see is an `int` to `Uint32` in `GeoSphereMaterial.cpp`... that's about it.

**Comment by robn** [comment]
Yeah, that looks rather benign.

Also couldn't reproduce it on the Mesa software renderer: `OpenGL version 3.3 (Core Profile) Mesa 10.4.2, running on VMware, Inc. Gallium 0.4 on llvmpipe (LLVM 3.5, 256 bits)`

@impaktor do you know how to drive `git bisect`? Since you can reproduce it you're probably best placed to try it.

**Comment by fluffyfreak** [comment]
We know it worked in 81e728fb14319b8bae11e3cbd09eb03928c5b0ab and was broken at 8b5c72155ad254aed3558c2d520a17782152fbee it just doesn't make sense as to why it would be.

How can I force it to run with the Mesa software renderer? Might be able to eliminate it as a local build issue.

**Comment by robn** [comment]
`LIBGL_ALWAYS_SOFTWARE=1 ./pioneer`

**Comment by fluffyfreak** [comment]
hmm, I just get "Failed to set video mode". Guess I need the driver.

**Comment by robn** [comment]
Probably `libgl1-mesa-glx`.

**Comment by robn** [comment]
Yeah, I can't see anything interesting between those two commits either. The only vaguely interesting thing I saw (that is, enough to make me check some headers) is that `glDepthRange` takes `GLclampd` args while `SetDepthRange` takes doubles, but these should be compatible.

**Comment by fluffyfreak** [comment]
Possibly range wrapping? I've seen that on some GPUs but not others to do with colours and alpha.
Still might not relevant as I don't think that the `GeoSphere` or related code uses it does it?

**Comment by robn** [comment]
Possibly. But hang on, that's SectorView (yeah, didn't read properly). What could the UI be doing to bollocks it up?

**Comment by robn** [comment]
Depth testing?

Grr, but I still don't understand what's changed.

**Comment by fluffyfreak** [comment]
Exactly, there's nothing that should affect what we're seeing.
Later on I'll try just blitzing all of the rendering state before and after rendering the terrain to see if I can work back from a known good thing and identify it. 

I find it rather telling though that it behaves differently for different makes/models of GPU/driver.

**Comment by fluffyfreak** [comment]
That software rendering still doesn't work for me. I'll try again this evening.

**Comment by impaktor** [comment]
> @impaktor do you know how to drive git bisect? Since you can reproduce it you're probably best placed to try it.

Never used it, but I can learn. Is it still needed, since the suspected commits don't compile?

**Comment by laarmen** [comment]
Bad @robn, non-compiling commits are EVIL!

**Comment by robn** [comment]
@impaktor Probably not, if they don't compile. Dang.

@laarmen Maybe. Refactoring in contained chunks with meaningful commit messages can complicate that a little. But bisecting across merges is tough anyway.

**Comment by jmf** [comment]
The bug didn't occur on my computer with nvidia graphics, it occurs on my laptop though.
Maybe it was only working due to an unclean working directory on the nvidia one, I will check that out when I got time.

[john@adrastea pioneer]$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.4.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.4.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.4.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.0
OpenGL ES profile extensions:

_**opengl.txt**_

OpenGL version 3.3 (Core Profile) Mesa 10.4.2, running on Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile 
Available extensions:
Shading language version: 3.30
  GL_ARB_ES2_compatibility
  GL_ARB_ES3_compatibility
  GL_ARB_base_instance
  GL_ARB_blend_func_extended
  GL_ARB_buffer_storage
  GL_ARB_clear_buffer_object
  GL_ARB_clear_texture
  GL_ARB_compressed_texture_pixel_storage
  GL_ARB_conditional_render_inverted
  GL_ARB_copy_buffer
  GL_ARB_copy_image
  GL_ARB_conservative_depth
  GL_ARB_debug_output
  GL_ARB_depth_buffer_float
  GL_ARB_depth_clamp
  GL_ARB_derivative_control
  GL_ARB_draw_buffers
  GL_ARB_draw_buffers_blend
  GL_ARB_draw_elements_base_vertex
  GL_ARB_draw_instanced
  GL_ARB_explicit_attrib_location
  GL_ARB_explicit_uniform_location
  GL_ARB_fragment_coord_conventions
  GL_ARB_fragment_shader
  GL_ARB_framebuffer_object
  GL_ARB_framebuffer_sRGB
  GL_ARB_get_program_binary
  GL_ARB_gpu_shader5
  GL_ARB_half_float_pixel
  GL_ARB_half_float_vertex
  GL_ARB_instanced_arrays
  GL_ARB_internalformat_query
  GL_ARB_invalidate_subdata
  GL_ARB_map_buffer_alignment
  GL_ARB_map_buffer_range
  GL_ARB_multi_bind
  GL_ARB_occlusion_query2
  GL_ARB_pixel_buffer_object
  GL_ARB_point_sprite
  GL_ARB_provoking_vertex
  GL_ARB_robustness
  GL_ARB_sample_shading
  GL_ARB_sampler_objects
  GL_ARB_seamless_cube_map
  GL_ARB_seamless_cubemap_per_texture
  GL_ARB_separate_shader_objects
  GL_ARB_shader_atomic_counters
  GL_ARB_shader_bit_encoding
  GL_ARB_shader_objects
  GL_ARB_shader_texture_lod
  GL_ARB_shading_language_packing
  GL_ARB_shading_language_420pack
  GL_ARB_sync
  GL_ARB_texture_buffer_object
  GL_ARB_texture_buffer_object_rgb32
  GL_ARB_texture_buffer_range
  GL_ARB_texture_compression_bptc
  GL_ARB_texture_compression_rgtc
  GL_ARB_texture_cube_map_array
  GL_ARB_texture_float
  GL_ARB_texture_gather
  GL_ARB_texture_mirror_clamp_to_edge
  GL_ARB_texture_multisample
  GL_ARB_texture_non_power_of_two
  GL_ARB_texture_query_levels
  GL_ARB_texture_query_lod
  GL_ARB_texture_rectangle
  GL_ARB_texture_rgb10_a2ui
  GL_ARB_texture_rg
  GL_ARB_texture_storage
  GL_ARB_texture_storage_multisample
  GL_ARB_texture_view
  GL_ARB_texture_swizzle
  GL_ARB_timer_query
  GL_ARB_uniform_buffer_object
  GL_ARB_vertex_array_bgra
  GL_ARB_vertex_array_object
  GL_ARB_vertex_attrib_binding
  GL_ARB_vertex_shader
  GL_ARB_vertex_type_10f_11f_11f_rev
  GL_ARB_vertex_type_2_10_10_10_rev
  GL_ARB_viewport_array
  GL_EXT_abgr
  GL_EXT_blend_equation_separate
  GL_EXT_draw_buffers2
  GL_EXT_draw_instanced
  GL_EXT_framebuffer_blit
  GL_EXT_framebuffer_multisample
  GL_EXT_framebuffer_multisample_blit_scaled
  GL_EXT_framebuffer_sRGB
  GL_EXT_packed_depth_stencil
  GL_EXT_packed_float
  GL_EXT_pixel_buffer_object
  GL_EXT_provoking_vertex
  GL_EXT_shader_integer_mix
  GL_EXT_texture_array
  GL_EXT_texture_compression_dxt1
  GL_ANGLE_texture_compression_dxt3
  GL_ANGLE_texture_compression_dxt5
  GL_EXT_texture_compression_rgtc
  GL_EXT_texture_compression_s3tc
  GL_EXT_texture_filter_anisotropic
  GL_EXT_texture_integer
  GL_EXT_texture_shared_exponent
  GL_EXT_texture_snorm
  GL_EXT_texture_sRGB
  GL_EXT_texture_sRGB_decode
  GL_EXT_texture_swizzle
  GL_EXT_timer_query
  GL_EXT_transform_feedback
  GL_EXT_vertex_array_bgra
  GL_OES_EGL_image
  GL_OES_read_format
  GL_KHR_debug
  GL_KHR_context_flush_control
  GL_3DFX_texture_compression_FXT1
  GL_AMD_conservative_depth
  GL_AMD_draw_buffers_blend
  GL_AMD_seamless_cubemap_per_texture
  GL_AMD_shader_trinary_minmax
  GL_AMD_vertex_shader_layer
  GL_AMD_vertex_shader_viewport_index
  GL_APPLE_object_purgeable
  GL_ATI_blend_equation_separate
  GL_ATI_texture_float
  GL_IBM_multimode_draw_arrays
  GL_MESA_pack_invert
  GL_MESA_texture_signed_rgba
  GL_NV_conditional_render
  GL_NV_depth_clamp
  GL_NV_packed_depth_stencil
  GL_S3_s3tc

Implementation Limits:
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 96
GL_MAX_CUBE_MAP_TEXTURE_SIZE = 8192
GL_MAX_DRAW_BUFFERS = 8
GL_MAX_ELEMENTS_INDICES = 3000
GL_MAX_ELEMENTS_VERTICES = 3000
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 16384
GL_MAX_TEXTURE_IMAGE_UNITS = 32
GL_MAX_TEXTURE_LOD_BIAS = 14
GL_MAX_TEXTURE_SIZE = 8192
GL_MAX_VERTEX_ATTRIBS = 16
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 32
GL_MAX_VERTEX_UNIFORM_COMPONENTS = 16384
GL_NUM_COMPRESSED_TEXTURE_FORMATS = 5
GL_SAMPLE_BUFFERS = 1
GL_SAMPLES = 4
GL_ALIASED_LINE_WIDTH_RANGE = 1, 7.875
GL_MAX_VIEWPORT_DIMS = 16384, 16384
GL_SMOOTH_LINE_WIDTH_RANGE = 1, 7.875
GL_SMOOTH_POINT_SIZE_RANGE = 1, 255

Compressed texture formats:
  0x86b0
  0x86b1
  0x83f0
  0x83f2
  0x83f3

**Comment by impaktor** [comment]
Just like a married couple, I don't have much to add that hasn't already been said, but to project the illusion of a successful life together, I took git bisect out for a ride today on our drive way to impress the neighbours. These are my findings:

6a0423e8132d60b49cff51f2a626db12a606e10c compiles, had the bug
825918d42b59c1c32d259a16017c8c8d9412fa2d linker error
84ef0d774640011340e45d2774a10e21dcb8e05c segfaults
81e728fb14319b8bae11e3cbd09eb03928c5b0ab works (as previously noted, dear)
008db46c3abd3e3667da8a02020ec72e533344ff segfaults
44be22af0627add699b48b2ac62fc2257a389317 works

**Comment by impaktor** [comment]
Seems like I'm not good enough for anything other than taking out the trash (read: "close issues"). I was wrong in my findings, updated the list accordingly, in the "__Edit__". I reached the same conclusions as @fluffyfreak.

(I want a divorce.)

**Comment by fluffyfreak** [comment]
I'll try to find time to do a `make clean` build this weekend and see if that changes anything.

@impaktor do you still get the bug with @robn new #3339 PR?

**Comment by impaktor** [comment]
> @impaktor do you still get the bug with @robn new #3339 PR?

Oh, I haven't tried. Will test on Monday, if no one else beats me to it.

**Comment by fluffyfreak** [comment]
@impaktor I just grabbed the latest on my LInux box, did a `make clean` and `sudo make -j4` and it now runs fine without any glitches.

Might be worth trying latest and cleaning to see if your problem goes away like @jmf did.

**Comment by impaktor** [comment]
Will do, first thing tomorrow.

**Comment by impaktor** [comment]
Works.
