### ISSUE TITLE
Game freeze

### ISSUE THREAD

**Issue by radius75** [pioneerspacesim/pioneer#3364]
VSE2013 Release build 7901020258ca17ec8ee4fcce2d67da7535d5d7c3
- Run Pioneer
- Start at Earth
- F5 = freeze for long time (hear the ship engine)

If the game will move, it again freezes (after EXIT or SAVE)

Edit
Build 4becd2e871773c0196311e205cfe909bc0677710 works fine for me

Edit2
the problem starts here bf39e997590239d16612cdaf1e6a9ad503ee435d

**Comment by impaktor** [comment]
@nick-the-ninja just updated the save format. Are you sure it is a 100% freeze and not just a longer (auto)save time?

**Comment by radius75** [comment]
Perhaps it autosave. But it takes about 80 seconds.

**Comment by fluffyfreak** [comment]
Relax, there's nothing wrong with the code, it's running the game via Visual Studios Debugger [that is the problem](http://preshing.com/20110717/the-windows-heap-is-slow-when-launched-from-the-debugger/).

It's a little known feature of the windows memory allocator that they're actually fixing for VS2015 because it makes debugging slower and no-one knows how to use it anyway.

Go into the project settings for pioneer, open the 'Debugging' panel, and in the 'Environment' options add '_NO_DEBUG_HEAP=1' for all configurations.

Now it will run normally again.

I hope to add this somehow by default but visual studio makes it a per-user setting currently :(

**Comment by laarmen** [comment]
Mmmmh, that would explain a few performance issues I've had at work
today, actually ! Thanks for the tip, @fluffyfreak.

**Comment by fluffyfreak** [comment]
@laarmen yeah it can really hammer STL containers when debugging in vs2013 :(

**Comment by fluffyfreak** [comment]
Actually integrating dlmalloc into pioneer with vs2013... has proven to be a screaming pit of madness.
Once I got it as far as trying to link, and that took an hour, things went really wrong.

I might try again at another time.

**Comment by impaktor** [comment]
So this "Game freeze" issue is solved, by disabling a debug flag in Microsoft visual studio, right?
Close?

**Comment by fluffyfreak** [comment]
It kind of is, but I want to keep this open a while longer, I'll assign it to me as well.
There shouldn't be a freeze but there's no way to distribute a fix for it because of the way MS have implemented it so I've looked into alternative memory allocators but they have issues with visual studio, linking, dlls etc...

So it's ongoing.

**Comment by fluffyfreak** [comment]
I have noticed whilst testing #3372 on my Mac Mini that OSX suffers this long freeze as well. Clearly they have an intrusive debuggin (`or just shit`) memory allocator as well.

**Comment by fluffyfreak** [comment]
This is an old issue from vs2013, it's not actually Pioneer it's the (old) debugger or external tool anyway. Closing.
