### ISSUE TITLE
Pioneer window not showing when using ratpoison window manager

### ISSUE THREAD

**Issue by jmf** [pioneerspacesim/pioneer#3436]
When starting pioneer on ratpoison wm, the window doesn't show although the commandline output seems okay.
rm-r reported that issue. System specs:
Linux pacb0la 4.1.3-gnu-1 #1 SMP PREEMPT x86_64 GNU/Linux (Parabola)
ratpoison 1.4.8 (built Sep 23 2014 15:37:11)
pioneer git (4a3119c)
Output: https://bpaste.net/show/1b6838574396
I can confirm this issue with ArchLinux, equivalent specs.

**Comment by fluffyfreak** [comment]
You've got several interesting things there, first of all it fails to create a window with multisampling then tries again and, presumably, appears to succeed.

Then you've got a lot of ICMP profile errors from PNG files which is odd as we've fixed all of those in the currently committed png files. The first lot seem to be coming from the facegen/faceparts system.

Then facegen reports this: `FaceParts: unknown directory 'facegen/species_0/backgrounds'` which just flat out shouldn't ever happen.

Then there's more from loading the wave and wave_e, which all use DDS files and not png files so I don't know how that's happening.

I'll need some info about your machine, what GPU do you have and what driver are you running? 
If it's an nVidia and you're using the Nouveau open source driver than you might just be totally out of luck as I've never had a report of that working with any version of Pioneer :(

The next check is to see if you're running any mod's which replace ships or the facegen system and might not be compatible with the current version of Pioneer.

Clean out the checkout out `data` folder and remove anything that shouldn't be in there because it seems you have to outdated data somehow. Perhaps try a clean & build again.

Lastly what version of libpng are you using?

**Comment by jmf** [comment]
It seems that this is a known bug, which is somehow related to SDL fullscreen and ratpoison.
It doesn't appear in windowed mode. Since ratpoison uses borderless windows, there is no visible difference between screen-resolution windowed fullscreen, so setting it to windowed isn't a problem.
To solve the problem, go to ~/.pioneer/config.ini and set StartFullscreen=0 ,

**Comment by fluffyfreak** [comment]
That's good to know but all those other issues are still very strange.

**Comment by impaktor** [comment]
Those other errors just can't happen in master as I see it, so this feels like someone has cluttered up their pioneer build or mods.

**Comment by jmf** [comment]
It could be, that the pioneer version that I listed in the first post isn't correct. 
rm-r couldn't find out the version, so I listed my version and rm-r's output, since I had the same issue.
I didn't think that it would make a difference. 
Here is my output:
https://bpaste.net/show/97537af83e13

**Comment by impaktor** [comment]
@jmf in your output you don't have any of the "weirdness" as in the first one from rm-r. Your output looks sane to me, and doesn't suffer form any of what fluffyfreak listed above. And since we now know what setting to use for ratpoison, the bug is in my opinion solved.

Also, rm-r struck me as very incoherent, difficult to understand / poor English (no offence if you're reading this rm-r), and quite a help-vampire, demanding help the very second something happens, rather than trying to find a solution before asking, and in general didn't seem to know what he was doing. I'm therefore content with not attributing too much into all the "strangeness" seen in his report. He probably downloaded a bunch of new and old mods (e.g. wave_e), and was probably all over the place (like removing facegen parts.)

Closing for now.
