### ISSUE TITLE
Station manager == Player portrait

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#3458]
Just started a new game (in Sol) and the London station manager is the players identical twin. Uncanny, hopefully this can be prevented in future portrait generation code. Portraits are the same, identical, not just similar. But thankfully names differ.

**Comment by joonicks** [comment]
Woops, restarted and it happened again, portraits are identical. Station manager name is same as last game but player name is new. Only after third restart is player portrait different.

**Comment by fluffyfreak** [comment]
They should always be the same. I dont mean every station manager should look like you I mean that each time you visit a place it should be the same person, each game should have the same station manager at the same station regardless of when you run the game.

It doesn't change based on time of day or anything.

**Comment by impaktor** [comment]
If faces are the same (as in clones) in the same BBS, then that would mean the RNG keeps throwing the same state. If so, it makes sense that when starting a new game in London also the player is a clone.

I'm a bit stumped as to what recent change could be causing this, because it hasn't happened before / in a long time.

**Comment by impaktor** [comment]
I'm going to close this for now, as I (hope) it's fixed by #3485
