### ISSUE TITLE
Low resolution scaling shipmarket

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#3459]
At low resolution, shipmarket scales poorly. Because of the icons not being scaled at all?

Screenshot is 640x480

![scalebug](https://cloud.githubusercontent.com/assets/14345157/9977414/6c2e5234-5f07-11e5-9ee7-da58c1e26eb4.jpg)

**Comment by impaktor** [comment]
Yes, pioneer won't look optimal at _any_ resolution. 
I don't consider this a bug.

**Comment by fluffyfreak** [comment]
@impaktor not optimal at _any_ resolution?

**Comment by impaktor** [comment]
> not optimal at any resolution?

NewUI looks good (no disrespect meant regarding NewUI), but since this issue is for nitpicking, what I meant was that it's hard to get it to look _perfect_ on _all_ resolutions; on a big screen there's a lot of blank space, and on smaller ones we see the effect here reported, and text fighting for space. This is a known limitation of the NewUI, and with robn gone, I very strongly doubt anyone will have time or energy to spend on addressing this, for a resolution that very few players use. However, I did not close the issue, since we might want to discuss it or share insights.

@joonicks (in reply to your complaint on bug-reporting) bugreports are welcome, and I'm not stopping anyone from doing them, but by my first comment on this issue, I'm simply trying to "callibrate" you to how we use the bugtracker. From what I've seen in IRC you and @nozmajner were discussing scaleable icons, so you are of course welcome implement this.

And please don't be afraid to report bugs, but also don't get upset if we/I close them.

We're glad to have you here, and hope you'll enjoy being with us.
