### ISSUE TITLE
strange marriage: ground stations overlapping

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3493]
![carvertown](https://cloud.githubusercontent.com/assets/1334989/10443123/20c9254a-7130-11e5-9cf7-10aa1974c8dd.png)

Savegame here: https://dl.dropboxusercontent.com/u/15391580/Pioneer/Carver%20Town

**Comment by walterar** [comment]
This issue begins on the label 20150319
It does not occur in 20150314

The strange thing is that the names of planets and stations is different, as shown.

20150314
![20150314](https://cloud.githubusercontent.com/assets/1334989/10456768/63e0a646-7199-11e5-9dc3-3978560a3fea.png)

20150319
![20150319](https://cloud.githubusercontent.com/assets/1334989/10456781/6dee2ffa-7199-11e5-8eb1-62a853a0b80b.png)

Everything points to # 3355

**Comment by fluffyfreak** [comment]
Thanks for tracking it down @walterar i'll try to find some time to look into it asap!

**Comment by walterar** [comment]
Do not rush. Perhaps they are breeding and make little stations. We need more surface space little stations. :))

**Comment by fluffyfreak** [comment]
There's two separate issues here.
1. You've found a very interesting world there @walterar :)
2. Something changed the galaxy/name generation in #3355 slightly.

What's happening in this bug is that the world is so strange there's only two places on it that it can put a space station, but it needs to place 3 stations. So it just dumps them where it can :/ That has nothing to do with #3355 though.

I think we'll have to live with the name generation change now but I'll see what I can do about the city/station placement code!

**Comment by fluffyfreak** [comment]
This is a tricky one to solve. I'll need to think quite a lot about this.

**Comment by walterar** [comment]
Do not worry, this is not too bad for the player. I did not find another case like this, yet.

We will give a "Notice to Mariners", or perhaps a blacklist of "hard" systems, are not many.

**Comment by fluffyfreak** [comment]
Ok, potential fix that will need testing. It fixes this bug but I'm a bit worried that it might introduce problems with other stations.

If you know of any with multiple orbital stations then they would be worth double checking.

**Comment by walterar** [comment]
Start testing.

**Comment by fluffyfreak** [comment]
Thanks @walterar :)

**Comment by walterar** [comment]
#3498 Fix this.

**Comment by impaktor** [comment]
@walterar you don't need to close your bug reports manually before the fix is merged, since 3498 will auto-magically close this once merged, since it contains the [key phrase](https://help.github.com/articles/closing-issues-via-commit-messages/) _"fixes `<issue number>`_". 

Not that it matters much, I just thought I could mention it. 

You're our number one bug finder and tester :+1:
