### ISSUE TITLE
glLoadGen failed to load functions

### ISSUE THREAD

**Issue by OglahnBah** [pioneerspacesim/pioneer#3494]
I receive this error when launching Pioneer regardless of build version. Was really hoping the latest release would fix this issue, but it doesn't. And I don't even know where to begin to troubleshoot such an error. 

WinXP SP3
Intel T2600 @ 2.1GHz
2GB Ram
nVidia Quadro FX 350M 512MB

**Comment by OglahnBah** [comment]
Alternatively I would try to compile the game myself, but I'm an amateur and the "How to compile Pioneer" included with the download doesn't make very much sense to me.

**Comment by impaktor** [comment]
Looks like you only have support to openGL 2.1
You need a pre 2014-11-19 version, get it here: http://www.moddb.com/games/pioneer/downloads
as described on the [FAQ](http://pioneerwiki.com/wiki/FAQ#I.27m_getting_.22OpenGL_Version_3.1_is_not_supported._Pioneer_cannot_run_on_your_graphics_card..22_error_on_startup) where you can read more on this.

**Comment by fluffyfreak** [comment]
Having an `nVidia Quadro FX 350M 512MB` suggest you're using a laptop which you cannot upgrade so the only way to play is to use an older version.

Of a fork of an older version of the game such as [Genesia](http://spacesimcentral.com/ssc/topic/4304-total-mod-genesia/)

**Comment by impaktor** [comment]
I wonder if it's possible to use some kind of raspberry pi setup for pioneer?

**Comment by fluffyfreak** [comment]
Yes, especially the newer rPI2, but we'd need to convert to OpenGL ES ... 2.0? or 3.0 maybe, not sure.

**Comment by fluffyfreak** [comment]
I'm reopening this issue because it occurs to me that we've had a few people with this lately and the game should be giving a clearer explanation as to why it's failing!!!

**Comment by fluffyfreak** [comment]
@impaktor I did the upgrade to OpenGL 3.x partly so that a conversion to PI2 / Arm based machines would be easier. Converting to OpenGL ES 2/3 should actually be pretty trivial now if you were interested.
The hard part was that the game used the old GL 2.0 way of doing things but ES 2.0 and GL 3.x are very similar especially the way that everything is mapped and uploaded which was the bulk of the conversion work.

The only reason we have these driver problems on Linux/Windows/OSX is because the manufacturers are incredibly fucking lazy and don't update the drivers for older GPUs (_except nVidia_).

**Comment by impaktor** [comment]
So that would be a pi-branch of pioneer? Or would that go into master?

Either way, I don't have a pi, and I was just curious, so don't put any effort on this for my account.

**Comment by fluffyfreak** [comment]
@impaktor worth reading -> [forum thread](http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=242&p=4164#p4164)
