### ISSUE TITLE
Game crash because of destroyed police ship

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#3512]
If a police ship gets destroyed, the game stops with the message
"error: Lua serializer '(null)' tried to serialize an invalid 'Ship' object".

You can reproduce this with the following steps:
1. Take off
2. Fire your gun or do other evil things
3. Try to survive until the police ship is destroyed
4. Dock with station

**Comment by robothauler** [comment]
If autosave is disabled this crash disappears.

**Comment by impaktor** [comment]
Thanks. That's very expected, since it's the number 4 that causes the crash when trying to (auto)save.

**Comment by impaktor** [comment]
`data/libs/SpaceStation.lua` has a `local police = {}` table. The funcion `SpaceStation:LaunchPolice(targetShip)` creates police ships and sends them after the player, storing them in the table `table.insert(police[self], policeShip)`, so we can tell them to land, or do what ever we want with them later.

If saving after having blown up a police ship, we're serializing a police ship that doesn't exist. Judging by the comment that is in current master, I think I knew about this bug :facepunch: 

```lua
Serializer:Register("SpaceStation",
	function ()
		local data = {
			equipmentStock = equipmentStock,
			equipmentPrice = equipmentPrice,
			police = police,  --todo fails if a police ship is killed
			shipsOnSale = {},
		}
```

Not sure what the best route is here? Ìntroduce an `onShipDestroyed()` that removes the ship? Would serializing a table with a `nil` element also crash? What would @laarmen do? Or just check in the serialization that there is something to serialize? Probably easy to solve, I'm just not brave enough to make a decision on my own.

**Comment by fluffyfreak** [comment]
I'm not sure what a `policeShip` is, or how these objects are kept in sync with the C++ side actual ships! 
What happens to a `policeShip` object when the C++ ship is deleted?
Do we actually use the `police` table in Lua or is it just there because someone might want too use it one day?

If it's not being used then can we just remove it?
If we must have list of ships then can we get it by querying the `SpaceStation` and asking for it's police ships, it can then just ask for all ships nearby, pick out the police ones and return that. That way it is stateless and doesn't require keeping an object around which may, or may not, point to an existing ship.

**Comment by laarmen** [comment]
"what would @laarmen do?" seriously? :)

Don't we already have a onShipDestroyed event? If not, we should.

The problem with the "query the station for the police ships" approach is that it solves this particular instance of the problem, but not the variants where we store a ref to a ship which then crashes.

I'll have a go at it tonight.

**Comment by laarmen** [comment]
PS: a table with a nil element technically doesn't exist (or, all tables have a nil element, depending on your PoV)

**Comment by walterar** [comment]
@laarmen  #3709 does not correct this.
