### ISSUE TITLE
Recent Linux build from source fails to start

### ISSUE THREAD

**Issue by TeddyDD** [pioneerspacesim/pioneer#3574]
I pulled source recently but new build don't want to start 
I'm using Linux Arch
```
new ModelCache
Shields::Init
BaseSphere::Init
pioneer: GeoSphere.cpp:48: static void GeoSphere::Init(): Assertion `s_patchContext->GetEdgeLen() <= detail_edgeLen[4]' failed.
fish: './pioneer' terminated by signal SIGABRT (Abort)
```

**Comment by Tichy** [comment]
I can confirm this. Same error and same distribution.

**Comment by fluffyfreak** [comment]
I've just done this on my Ubuntu test box and it builds and runs just fine.

Wonderful. I'm not sure how it could ever get into that state given the line preceeding that either.

**Comment by fluffyfreak** [comment]
Perhaps try deleting your `config.ini` from the `./pioneer` folder in your home directory so that it has to recreate it.

**Comment by johnbartholomew** [comment]
This will happen any time the planet detail level is set to "very high", because the code creates a GeoPatchContext passing in `detail_edgeLen[detail]` (with detail between 0 and 4 inclusive), then GeoPatchContext adds 2 to the passed in value, and then the code checks that the result is <= the maximum `detail_edgeLen` value.

**Comment by TeddyDD** [comment]
Removing config.ini fixed this. And I see PR is already waiting :) Thank you @johnbartholomew
