### ISSUE TITLE
Update `NameGen.lua`

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#3601]
It's been a while since `NameGen.lua` was updated so maybe we should do a pass and make sure we've got all the contributor names added.

Also there's more male than female names, probably as we're mostly male on the project (?), so if anyone can think of family members names that aren't in there then mention them in a reply post as we can fix that up too.

**Comment by impaktor** [comment]
Funny, this is exactly what I'm working on, and been tumbling in my head for the past weeks.

I have compiled a shit load of data with most common first and last names from most "big" countries, (Spanish, French, German, Russian, Japanese, Chinese, Greek, Italian, UK, ...).

I've been talking with @laarmen about how to best implement it. I want each system to have its own "culture"-constant, so BBS is dominated by Chinese names if the system has a Chinese culture.

 @laarmen suggested storing names/cultures as json, since it's data, but that has the downside of not being able to tweak names, like Russian last names are suffixed with "a" if it's a female first name (e.q. impaktov, impaktova). And don't get me stared on those Hungarian bastards, who are all backwards! 

So I'm still thinking about how each culture should define its own `firstname` and `lastname` function. My problem is thinking through which strategy is best for all of this. (How/when is culture assigned to a system? In C++? Culture constans are exposed to both C++ and Lua? From where? etc.)

So I'm still a bit in Lua-C++ limbo.

Also, I don't have a branch of this yet.

**Comment by impaktor** [comment]
For some reason, I though this link fits in here: http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

and why not http://www.bbc.com/future/story/20160325-the-names-that-break-computer-systems as well.
