### ISSUE TITLE
Distance given when asking "Where do I find the target?" for search and rescue mission is inaccurate

### ISSUE THREAD

**Issue by wafehling** [pioneerspacesim/pioneer#3650]
Distance told when asking about taking job:
![ixt7bso](https://cloud.githubusercontent.com/assets/1471082/13719533/b62ecd4e-e7bc-11e5-8107-03e39d47da26.png)

Distance told when looking at mission info:
![7u5nuce](https://cloud.githubusercontent.com/assets/1471082/13719536/c4c87166-e7bc-11e5-8fc9-1c5495049d0f.png)

Savefile to reproduce issue:
[bad_distance.zip](https://github.com/pioneerspacesim/pioneer/files/170195/bad_distance.zip)
F4, bulletin board, select the search and rescue mission.

**Comment by wafehling** [comment]
The distance appears to be (roughly) 1000x off in the "where do I find the target?" section, so poking around any variable that's * or / 1000 seems like a good place to start.

**Comment by wafehling** [comment]
I found a focal point of the error: Changing line 687 from
`dist = string.format("%.2f", ad.dist/1000)`
to
`dist = string.format("%.2f", ad.dist/1)`
produces proper flavor text. I don't know if this breaks other missions. I'll crank up the frequency of them and do some checks.

**Comment by wafehling** [comment]
Error appears to be fixed based on every possible test I can throw at it.

**Comment by wafehling** [comment]
Branch pr/3651 holds the fix, but I can't submit pull requests (More than understandable), so... there it is.

**Comment by impaktor** [comment]
> I can't submit pull requests 

Yes you can. When looking in your branch there should be a green *submit new pull request" button, assuming you forked the pioneer source code. Check our wiki and/or consult the Internet.

Would be good if we get it as a propper pull request.

I assume this bug is due to the distance for in-system bodies is given in meters, while if the mission is for another system the distance is given in light years. Just something to look out for.

(E.g. In `onClick` the script author seems to be aware of this.)

**Comment by impaktor** [comment]
> ... assuming you forked the pioneer source code. 

...and implemented it on its own branch.

**Comment by wafehling** [comment]
I implemented it on its own branch, but not on a new fork. 

Github is so obtusely confusing.

**Comment by impaktor** [comment]
Looking at your github account it looks to me like you have a [pioneer fork](https://github.com/wafehling/pioneer), but no branches beyond master: `https://github.com/wafehling/pioneer/tree/master`, and the latest commit on that is from upstream pioneer source. Did you push your changes to your github?

Git takes a while to get into but is most amazing once you get the hang of it. On the plus-side: there are many tutorials for github and git. And we have our own on the wiki as well.

**Comment by wafehling** [comment]
I branched off from the project itself, not a fork.

**Comment by impaktor** [comment]
> I branched off from the project itself, not a fork.

Yes this is exactly what a fork is. To make a pull request, so that we can see your changes, and merge them into pioneer you need to do the following:

1. Fork pioneer master to your own github repo. (This you have done)
2. Create a branch of your fork, so you're not on master-branch (remains to be done)
3. commit changes to that branch
4. push changes to your github repo. (called "origin" in the pioneer wiki on git )

Alternativley, you could skip 2,3 and push changes to your master branch. It's less ideal, but that way we can at least see the changes. At the moment your changes are only on your own computer, and not visible to us. At least I can't see anything.

**Comment by impaktor** [comment]
Should be fixed in master now.
