### ISSUE TITLE
Differentiate available services on stations

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3736]
All stations seem to have the same services, which doesn't make them really unique. I suggest
to make them a bit more individual by limiting the number of services a station has.

All stations should have at least:
- Lobby
- Automatic refueling
- Missions/News

All stations may or may not have:
- Police
- Repair service
- Equipment market
- Ship market
- Commodity market (if not present, this also disables all black markets in the mission panel, or it makes them less likely)

The more “anarchic” a system is, the less likely the stations are to have a police.
Stations without a police are less likely to have fake black markets (but not impossible, so there's still a risk).

Smaller stations should tend to have less of the other “features” while larger stations (esp. on planets) should tend to have a more “complete” set of services.

The lobby can be used to indicate the various “services” available.

Example for the text in the lobby (remove sentences which don't fit to the station):

“This station has a landing and refueling fee of $6.00.
You can trade goods on this station.
You can buy equipment to upgrade your space ship here.
This station's equipment market has a level 1 technology certificate.
You can buy new space ships here.
Your space ship can be repaired here.
This station is guarded by a police.”

(The basic idea is: Every bit of information is written in one simple sentence.)

The “technology level” line is tied to the fact that the station has a equipment market in the first place. If there is no equipment market, there's also no tech level, of course.

**Comment by impaktor** [comment]
Please use our dev forum for posts like these, that are not bugs, as this clutters up the bugs we're actually in need of fixing.

> [All stations may or may not have:] Police

I think law must always be present. Almost. I have a branch with a pirate system, where there is no police. This is something I consider to be "very rare", like a secret lawless place where anything goes.

> [All stations may or may not have:] Repair service

Most important for stations must be refueling and repairing, so I don't think that's a good idea.

> [All stations may or may not have:] Equipment market

This is just a more binary version of PR #3505 which introduced tech levels, which does limit the amout of equipment in each station. By default it used same setting as Frontier. We felt that was too restrictive, e.g. not allowing auto-pilot for tech level 1 worlds, so we (re)enabled that. Thus having _no_ equipment is (probably) not of interest. (tech level = 0?)

> [All stations may or may not have:] Ship market

Smaller stations have far fewer ships for sale, so in a way this is also already in place.
    
> [All stations may or may not have:] Commodity market 

Players kind of want to refuel. Also, the station will consume goods, and need supplies, which the player will provide. Disabling some commodities makes it difficult for the player to know if he/she really can sell those precious metals in this-or-that system. I don't think that would add to the game experience.

> Stations without a police are less likely to have fake black markets 

Black markets are far more expensive since they're "black", and operate against the law. In a "pirate" system, all goods are legal (thus traditionally illegal goods are cheap), thus no black market

> The lobby can be used to indicate the various “services” available.

Yes, I've been thinking along the same lines, that is why they show tech level, at the moment. I have/had an ambition to have different stations (and factions) sell ships from different manufacturers. Lobby would say something like "Licensed Mandarava Csepel retailer", or similar.
