### ISSUE TITLE
Stars not visible since 20160814

### ISSUE THREAD

**Issue by Libross** [pioneerspacesim/pioneer#3888]
Hello, firstly thanks a lot to all developers for this sim. Great work.

Now to the problem - two days ago I have installed the sim first time (latest version - 20161129-win32 ) and immediately noticed something is not OK - there were missing stars in the outer space - there were visible just background texture of Galaxy ring - see the screenshot (the galaxy texture on the left).

I tried all various video settings, but I found that stars are OK in older versions, so I focused to stars improvement in change log and identified the last working version - that is 20160724 - where all is OK (test proved that in the next version 20160814 the problem appeared first time).
 - Ah and I just remember another observation - it is not only stars which are missing, but also the flashing lights on the bases and ships which stopped working since that version as well.

My OS is Windows 10 and HW is Lenovo T420 with Intel HD 3000 graphics (OpenGL 3.1 fully supported, latest available video driver). Attached is also the openGL.txt file
I am available for further testing, if it can be fixed by some config tweaking or mods...
(if it is caused by some new star feature, maybe there could be option in menu to use old stars...)

### Observed behaviour
Missing stars in game and in the Main menu, missing stations/ship lights.

### Expected behaviour
Stars should be visible as it is in version 20160724 and older.

### Steps to reproduce
it happens always with version 20160814 and higher.

![no_stars_and_lights](https://cloud.githubusercontent.com/assets/24441395/20987930/c72b9a9a-bcce-11e6-9a78-d7c97db8ec10.jpg)

[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/637826/opengl.txt)

**Comment by Libross** [comment]
For better overview - these are the new features and changes between the 20160724 and 2016814 taken from the changelogs differences:

August 2016
   * New Features
     * F3 and F4 Toggles between worldview and their thing (#3765)
     * Navbutton added to mission screens (#3736)
     * Add a TCP Lua console (#3768)

   * Fixes
     * Fix crash in by Search & Rescue missions (#3770)
     * NaN in your numbers (#3772)
     * Fix hyperspace star streaks (#3773)
     * prefix std:: to isnan so it builds on Linux (#3775)
     * Use ImageMagick to fix the iCCP profile problem (#3778)

   * Internal Changes
     * Add a function for typesetting time intervals (#3764)
     * Restore Starfield colourisation (#3774)
     * Animated city buildings, instancing improvement (#3777)

July 2016
   * New Features
     * Point sprite background stars (#3757)

**Comment by jaj22** [comment]
Almost certainly the same core problem as #3478. The background star point sprite is loaded as a PNG, stored with a compressed internal format and then auto-mipmapped. Apparently various Intel drivers didn't implement mipmap generation for compressed textures. 

As a workaround, setting `UseTextureCompression=0` should fix the background stars. This should probably be the default setting (or possibly the only setting), and textures that benefit from compression should be pre-converted. There are not many of them remaining.

You don't get a GL_INVALID_ENUM popup or similar? If not, then my suggested solution for detecting the problem drivers wouldn't work.

**Comment by Libross** [comment]
Thanks for quick reply!

I am not receiving any errors or popups when starting or during gameplay on the versions 20160814 and higher.

I tried to change the suggested parameter `UseTextureCompression=0` in config.ini - indeed it was set to 1 (that's maybe default unless I have changed it within Settings in GUI when I was trying different options).

Unfortunately the issue still remains...

**Comment by jaj22** [comment]
Ok, I was baffled by that, but I eventually figured that the UseTextureCompression parameter doesn't go anywhere, so texture compression is always enabled regardless of settings. 

I'll need to check how that functionality is supposed to work.

**Comment by fluffyfreak** [comment]
@jaj22 it's definitely used but yes the usage is confusing :)
In 'RendererGL' it's used to set the 'm_useCompressedTextures' flag which is then used in 'RendererOGL::CreateTexture' as the second parameter.

**Comment by fluffyfreak** [comment]
@Libross there's a much newer version (`20161129`) out now at http://pioneerspacesim.net so is there any reason you're running the older `20160814` build?

**Comment by jaj22** [comment]
Ok nevermind, I replicated this with a clean Win10 install on my G620 box. I suspect it's an issue with the billboard colouring. 

Annoyingly, Windows 7, 8 and 8.1 have an updated driver that works fine on the same hardware. The Win10 driver is backwards for some reason.

**Comment by jaj22** [comment]
Ok, it looks like gl_PointCoord is coming out as zero in the fragment shaders. Replace it with vec2(0.5,0.5) and you get somewhat oversized stars.

I'm not sure whether this is correct behaviour. Apparently on compatibility profiles you still need to call `glEnable(GL_POINT_SPRITE)` for gl_PointCoord to work, and the driver in question does appear to include the extension `GL_ARB_COMPATIBILITY`. Of course, we don't have GL_POINT_SPRITE because we're using the core defines. Maybe a case for a fudge.

By the way, the Win 7 driver has the same problem (and it's probably the same driver). I didn't notice due to dark-monitor related observation errors.

**Comment by fluffyfreak** [comment]
We call `glEnable(GL_PROGRAM_POINT_SIZE);` in RendererGL but `GL_POINT_SPRITE` isn't defined in our profile. I can regenerate it so that it is i guess.

The instructions for doing so are located in `graphics\opengl\OpenGLLibs.h` and I think they should generate the same output as we currently use.

**Comment by jaj22** [comment]
Ok, I'm pretty sure this is an Intel driver bug. I made a minimal SDL2+GL3 point-sprite test and tried various cases. With the forward compatibility context flag set, `gl_PointCoord` is always 0,0, regardless of whether `glEnable(0x8861)` or `glDisable(0x8861)` are called (0x8861 = GL_POINT_SPRITE).

What does work with that driver is removing the forward compatibility context flag _and_ setting `glEnable(0x8861)`. So the driver's definitely capable of providing gl_PointCoord, but it's forcing it to disabled instead of enabled with the forward compatibility context.

The full workaround would look something like this:
1. Add a config file setting to disable forward compatibility.
2. Pass that setting in Graphics::Settings.
3. WindowSDL uses that setting to toggle the forward compatibility.
4. Call glEnable(0x8861) in the RendererOGL constructor if the flag is set.

It's possible to autodetect the bad driver, but that's a pain because we can't interrogate the driver version before creating the GL context. A simpler option might be to warn the user that the config file setting might be necessary.

**Comment by fluffyfreak** [comment]
I don't suppose that there's a newer driver for that chipset from Intel? I just had a look myself but it seems the last driver they released was only for Windows 7/8/8.1 without 10 support mentioned at all.

It might be worth reporting that driver bug to them since there's probably millions of chipsets/driver installations in the wild that have it.

**Comment by impaktor** [comment]
With risk of stating the obvious, but if the bug is with Intel, then it would be preferable if they fix it so that the pioneer source don't need to have various ugly hacks.

> It might be worth reporting that driver bug to them since there's probably millions of chipsets/driver installations in the wild that have it. 

My thinking also. (although I hadn't planed to do it myself)

**Comment by fluffyfreak** [comment]
I think we might have to be practical about it though, although submitting a reproducible bug with a minimal version (*such as @jaj22 point-sprite test*) is the gold standard way of doing it, it's unlikely that Intel would actually bother to do anything about it.

Especially as they haven't even gotten feature parity with the OSX or Linux drivers.

I would prefer to auto-detect the incompatibility, either by examining the gpu/driver string returned during OpenGL initialisation, or via a run-once rendering test at startup. Then use the ini file flag setting for future runs.

That is however the harder option, so perhaps doing as @jaj22 suggests for now is the best approach?

**Comment by fluffyfreak** [comment]
Oh and since these do indeed appear to be driver bugs that makes everyone official game developers ;)
You can put it on your CV's :D

**Comment by jaj22** [comment]
Intel state that [they no longer support GPUs before 4th gen Core (Haswell), and the current driver versions for those chips are the last](https://software.intel.com/en-us/forums/graphics-driver-bug-reporting/topic/532646). So we're probably stuck with it. The implication there is that you shouldn't even report the bugs if they don't occur on later chips. The drivers for the 3rd gen chips (Ivy Bridge) are fine, incidentally.

I'm not sure how you'd implement a rendering test here without using other rare functionality. The (current) faulty drivers all have the same version number, but older drivers may have the same issue, so some test like +"3.1" +"Intel" -"Core" would probably cover it. I'll check what the Ivy Bridge reports.

Any preference on config parameter names? I'm thinking general ("GL3CompatibilityMode") rather than specific ("FixSandyBridgeTrash").

**Comment by fluffyfreak** [comment]
@jaj22 there's an `AMD_MESA_HACKS` one so maybe `INTEL_GL3_HACKS`.

Well for the run-once test I was thinking of something like using a point sprite to render to a RenderTarget, then checking the pixel colour at a specific coordinate within that RT texture to see if it had worked :) that kind of test.
