### ISSUE TITLE
Some fixes needed by PR #3901 to work better

### ISSUE THREAD

**Issue by mike-f1** [pioneerspacesim/pioneer#3907]
There's some changes to stations models to fix pads sizes and
to thin collision meshes in order to have a better result with
PR #3901

**Comment by nozmajner** [comment]
Pad collision meshes got very thin, and pad sizes are fixed. A lot of pads were 500m sized. I fixed those to 70m for the octagonal station and 80 for the new_ground.
Octagonal: https://www.dropbox.com/s/bzdfpqnodg3pgql/starport_docking.dae?dl=0
New_ground: https://www.dropbox.com/s/f8mxlj1ro8j674e/landPad6_docking.dae?dl=0

The pad sizes for the orbitals were already good, and I will provide the proper collision meshes for them when they are needed.

**Comment by jaj22** [comment]
Note that if your code _needs_ thinner collision meshes, it's probably making an incorrect assumption. Pioneer's collision system uses discrete steps, so the point where a ship collides with a flat surface, it may well be partially inside it. Regardless of other fixes (which are required), ships need to be repositioned vertically after landing.

You could argue that Pioneer should be using continuous rather than discrete collisions, but I doubt we have anyone willing to take on that problem.

**Comment by mike-f1** [comment]
@nozmajner, @jaj22  that was related to "min_pad_size" and "max_pad_size", two property attached to pads...

Has been this fixed?

**Comment by mike-f1** [comment]
...or I *think* this could be closed...
