### ISSUE TITLE
Gameplay ideas from Endless Sky

### ISSUE THREAD

**Issue by alugarius** [pioneerspacesim/pioneer#3964]
I started playing space games with [Endless Sky](https://endless-sky.github.io/)
Its 2D but else very similar to Pioneer.
It has a Mission based Story, other Races and a system where Crew makes sense (having a fleet controled by bots).

I recommend to take a look at it to gain more background.

For example, we could add wormholes where we find other species and better ships and technology.

**Comment by nozmajner** [comment]
Well, in this current form, this issue is pointless. Not even a feature request, but a general pointer. This kind of stuff really should go onto the [dev forum](https://pioneerspacesim.net/forum/index.php), this place is for concrete implementation work, not ideas ping-pong.

Please come over to the dev forum, and elaborate any given feature you think would be good to have. Ping me on IRC, I'll open up the registration for you (we had to close it, lots of spam).
Development is quite glacial at the moment due to IRL obligations.
We are quite short on people who have much free time on their hands to donate, so if you would like to contribute, you are more than welcome.

**Comment by alugarius** [comment]
How do I register there?
