### ISSUE TITLE
[Licensing] Under what conditions can I use the music from Pioneer?

### ISSUE THREAD

**Issue by aaronfranke** [pioneerspacesim/pioneer#3970]
Hi, I am wondering under what conditions I am allowed to use Pioneer's music. AUTHORS.txt says:

> Pioneer's art, music and other assets are licensed under the terms of the
> Creative Commons Attribution-ShareAlike 3.0 Unported License. See
> licenses/CC-BY-SA-3.0.txt for details.

Is **all** of the music under this license? 

What does this license imply? I looked up the CC-BY-SA license and many people have [said](https://stackoverflow.com/questions/2005207/creative-commons-attribution-share-alike-3-0-commercial-use) something similar to "You can use the by-sa licensed product (the icons in this case) in your project on the condition that you provide your product to your client under the same or a similar license". 

What is a similar license? Other CC licenses? Other copyleft licenses like the GPL and LGPL?

**Comment by nozmajner** [comment]
Hi!
The "similar license" part isn't really true. (Strange that our version that licence ships with the game says that, it not supposed to). Ping @robn ?
Here's is the [official summary](https://creativecommons.org/licenses/by-sa/3.0/) of the license, and the [whole license text](https://creativecommons.org/licenses/by-sa/3.0/).

So to answer your question: you can only use these music with the same license, CC-BY-SA-3,0

You could also find and contact the original contributor(s) who made them and ask for another kind of license if CC-BY-SA isn't good for your purposes. But the hard part is finding out who made them, because they came before the project being on github, so the history doesn't show who made them, nor our contributors.txt which doesn't list the roles, just the names.
[This PR might be helpful.](https://github.com/pioneerspacesim/pioneer/pull/543) 
[Or the older pages of the community forum.](http://spacesimcentral.com/forum/categories/pioneer/p24)

**Comment by impaktor** [comment]
Out of curiosity, what will you use it for?

**Comment by robn** [comment]
Yeah, you're right: `licenses/CC-BY-SA-3.0.txt` should be the full license text from https://creativecommons.org/licenses/by-sa/3.0/legalcode, probably with the summary at the top. Could someone please submit a PR that makes that change?

Not sure where the summary we have came from. [The summary on 26 September 2012](http://web.archive.org/web/20120916010106/http://creativecommons.org/licenses/by-sa/3.0/) hasn't changed substantially. Probably just a screwup at the time, probably mine!

CC-BY-SA-3.0 is definitely the correct license though. Basically, we wanted something like the GPL3, but suitable for non-software content. As with the GPL the intent is that you can use the assets for any purpose, including commercial, as long as you (a) give credit back to the project and (b) distribute any changes you make under the same license.

If you do that, please let us know - we'd like to see where you use our work! 🙇

**Comment by impaktor** [comment]
> Could someone please submit a PR that makes that change?

I'm on it.

**Comment by fluffyfreak** [comment]
@aaronfranke the license has been updated now to the correct one.
