### ISSUE TITLE
assimp 4.0.0 support

### ISSUE THREAD

**Issue by ilovezfs** [pioneerspacesim/pioneer#4054]
https://github.com/assimp/assimp/releases/tag/v4.0.0 was just released, but pioneer's configure rejects it:
```
configure: error: "assimp version >= 3.2 not found. Get it from https://assimp.sourceforge.net/"
```

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4890/version=sierra/testReport/junit/brew-test-bot/sierra/install_pioneer/
https://github.com/Homebrew/homebrew-core/pull/15763

**Comment by fluffyfreak** [comment]
That's a lot of changes, I wonder if there's any compatibility issues with 3.2 which we currently target.

Well the cause of the issue is easy to see anyway as it's the line https://github.com/pioneerspacesim/pioneer/blob/master/configure.ac#L305 which requires the major version to be greater than or equal to 3 and the minor version to be greater than or equal to 2. 

Both those must be true, but of course 4.0 has a minor version number less than 2 👍

**Comment by ilovezfs** [comment]
@fluffyfreak indeed: https://github.com/Homebrew/homebrew-core/commit/3721a70d3f40637a1ba1d14f384e4f459413f3d3#diff-3af166d5e31c98c65209bed059805ec5R35

I shipped it with 4.0 since it built fine. Hopefully, no issues.

**Comment by ilovezfs** [comment]
@fluffyfreak thanks!

**Comment by fluffyfreak** [comment]
@ilovezfs no problem, thanks for pointing it out to us.
