### ISSUE TITLE
Strobe during conflicting sunsets

### ISSUE THREAD

**Issue by macksting** [pioneerspacesim/pioneer#4094]
### Observed behaviour
Red and yellow strobe over the town when observing a sunset with two conflicting and odd suns on Morales's Mine, Vetiar (-14, -12, -11) as Vetiar A, the smaller yellow sun, was sinking below the horizon.

### Expected behaviour
Probably shouldn't have had so much influence from Vetiar A at that point anyway, but on a part of the world more in view of both suns the lighting was more orange, a pleasant combination of the two, I think.

### Steps to reproduce
Go to Vetiar A's colony Brennan Base on the world Morales's Mine and wait until 3204 Apr 25 around 2:53:07.

__My pioneer version (and OS):__
git 858629b, lubuntu 16.04

### Files
I have a video, but apparently they don't support mp4 here, oddly enough.

**Comment by impaktor** [comment]
> I have a video, but apparently they don't support mp4 here, oddly enough.

Convert to gif? Would be interesting to see.

**Comment by fluffyfreak** [comment]
Set one of the system start locations in `main.lua` to `-14, -12, -11,1,14` and i'll will spawn a ship on the pad at Brennan Base for you to observe this happening.

Interesting, it seems to be because of both stars being very low on the horizon so they each flicker in/out as they pass beyond the horizon. If we had a more gradual fade by treating them as area lights rather than point sources this wouldn't be so noticeable but that would be more complex.

**Comment by fluffyfreak** [comment]
I am going to close this as there is no reasonable solution to the problem currently.
It will always happen for stars that cross the horizon slowly at very shallow angles I'm afraid.
