### ISSUE TITLE
Autosave bugs: Cargo Run mission not completed after loading game with ship docked to city port

### ISSUE THREAD

**Issue by Fixer-007** [pioneerspacesim/pioneer#4127]
Autosave enabled, took delivery job (Cargo Run) to city starport on random planet, completed it without problem, continued playing, then decided to go back to previous autosave.
After loading autosave ship appears landed and docked to that city, BUT mission page says my delivery to this very same city is not completed. So I have to redock to it, to finish the mission.

Very annoying, please fix, will attach faulty save for inspection.

Faulty save: [_autosave7.zip](https://github.com/pioneerspacesim/pioneer/files/1267444/_autosave7.zip)

Other missions are probably affected as well. Probably autosave is made before mission gets marked as saved?

Pioneer 20170827 / win7

**Comment by impaktor** [comment]
I think what happens is (without looking at the code), that since there is no
way for pioneer to know the order to run the hooks/triggers, such as the
on-docked-hook, sometimes (always?) the save hook happen to be executed before
the mission hook that checks if it's completed. Thus the finish state of the
mission is only set after the save has been done.

When you load, the game restores the variables from the save, but the check
that the mission was completed is only triggered when docking.

Question is, if all missions should treat the onLoadGame as a onDocking, or if
there's a better fix. Ping @laarmen.

**Comment by Bodasey** [comment]
confimed with actual master for postal delivery (no mass), but cargo transport is cleared correctly.

**Comment by impaktor** [comment]
Cargo system has been re-written since this was reported. Not sure what the status of this bug is.

**Comment by Bodasey** [comment]
not observed any more with actual master

**Comment by Bodasey** [comment]
Observed not long enough - may still happen.

**Comment by impaktor** [comment]
@Bodasey If it does, please open a new issue. Since this was from 2017, I assume "things have changed".
