### ISSUE TITLE
Feature request: police immobilize your ship / go to jail

### ISSUE THREAD

**Issue by manolollr** [pioneerspacesim/pioneer#4132]
This request is related to pull request:
https://github.com/pioneerspacesim/pioneer/pull/4089
So you commit a litle crime with a $500 fine and police kill you. Is this correct? Wooowwww!!! It's very very heavy. Haven't right to a fair judgement?
I think it's better Police blocks you with a tractor beam, like in Star Trek:
http://memory-alpha.wikia.com/wiki/Tractor_beam
Then you have two choices: pay fine or escape. If you escape then police shoot at you and try to kill you in every star system you go, but please, first give me an opportunity to pay the fine.
Perhaps, if fine is very high, you go to jail and game ends, with and image of a jail similar to current tomstone when game ends.

**Comment by nozmajner** [comment]
I'll close this, because we don't really use the tracker for feature requests, especially for more complex matters like this. The forum or IRC is a better place for that. IRC moreso.
I'm pretty sure tractor beam is out of the plate, too magitech. But the question worth proper discussion, so come along to IRC. :)
