### ISSUE TITLE
Hyperdrive less likely to fail the longer the time since warranty expired?

### ISSUE THREAD

**Issue by antonspace** [pioneerspacesim/pioneer#4158]
### Observed behaviour

Hope I am understanding this correctly, apologies if not. Been flying around in a Venturestar fitted with a class 9 hyperdrive. Over 4 years have passed since the warranty expired.

This is the console output from a sequence of jumps, plus the latest jump at the end. 

DEBUG: Jumps since warranty: -546, chance of failure (if > 0): 1/801
DEBUG: Jumps since warranty: -549, chance of failure (if > 0): 1/804
DEBUG: Jumps since warranty: -561, chance of failure (if > 0): 1/816
DEBUG: Jumps since warranty: -568, chance of failure (if > 0): 1/823
DEBUG: Jumps since warranty: -568, chance of failure (if > 0): 1/823
DEBUG: Jumps since warranty: -578, chance of failure (if > 0): 1/833
Latest jump...
DEBUG: Jumps since warranty: -1311, chance of failure (if > 0): 1/1566

__My pioneer version (and OS):__

a614c6f

Linux Mint 18 64-bit

**Comment by impaktor** [comment]
Interesting. This code has been untouched for many years, so it's been un-noticed for long time.

I've only looked very quickly at the code, and I suspect your drive had a malfunction, but was repaired by you  or crew (this happens automatically), and when that happens this is called:

```lua
-- Rewind the servicing countdown by a random amount based on crew member's ability
local fixup = saved_by_this_guy.engineering - saved_by_this_guy.DiceRoll()
if fixup > 0 then service_history.jumpcount = service_history.jumpcount - fixup end
```
Nothing prevents the `jumpcount` from turning negative. Also, to me it looks like _if_ you have an engineer capable crew member (do you?), it tests the breaking down of the engine every time you jump, and repairs your engine every jump (thus the irratic numbers in "jump since warranty"). 

I'll have to look into this code, but later.

**Comment by antonspace** [comment]
Yes, there is an engineer on board, she states after every jump "I fixed the hyperdrive before it broke down", I noticed this message also appeared immediately after the last time the hyperdrive was serviced, which seemed strange, assumed it was just for amusement, to justify the large wages I pay her.

**Comment by impaktor** [comment]
Yeah, that confirms my understanding of the code: If there's an engineer aboard, they will repair the drive in a manner that is uncoupled to the wear and tear of it. 

But I assume the engineer has been doing this repairing ever since she boarded your ship.

**Comment by antonspace** [comment]
Not initially, as you said above there must have been a time when the drive had a malfunction, which was fixed by the crew, and it snowballed from then on.

**Comment by impaktor** [comment]
@antonspace could you please use this file instead, that is a bug fix:
https://raw.githubusercontent.com/impaktor/pioneer/fix_breakdown/data/modules/BreakdownServicing/BreakdownServicing.lua

However, to get your counter back to right side of zero you need to either buy new engine, or have some maintenence on it, which will reset the jumpcounter.

**Comment by antonspace** [comment]
@impaktor Thanks, I replaced BreakdownServicing.lua, performed a few jumps, serviced the hyperdrive,  then did some more jumps. Looks good.

DEBUG: Jumps since warranty: -1324
Warranty expires: 10:13:25 9 Aug 3207
DEBUG: Jumps since warranty: -1323
Warranty expires: 10:13:25 9 Aug 3207
DEBUG: Jumps since warranty: -1322
Warranty expires: 10:13:25 9 Aug 3207

Hyperdrive serviced...

DEBUG: Jumps since warranty: 0
Warranty expires: 05:55:24 17 Jul 3212
DEBUG: Jumps since warranty: 0
Warranty expires: 05:55:24 17 Jul 3212

**Comment by impaktor** [comment]
Nice. Would be interesting to see if it will fail / get repaired after waranty time has expired. Since these variables are `local` to the script, I know not how to get at them from the Lua terminal, so if you want to test, do some long hyperjumps so time progresses fast.

[_Time flies like an arrow, fruit flies like banana._](https://en.wikipedia.org/wiki/Time_flies_like_an_arrow;_fruit_flies_like_a_banana)

**Comment by impaktor** [comment]
> Thanks, I replaced BreakdownServicing.lua

I did a minor update to the code in #4161 to clean it up a bit (removed redundant code), but behaviour should be unchanged.
