### ISSUE TITLE
Earth tech certificate differs in 32-bit vs. 64-bit compiles

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4249]
When compiling pioneer in visual studio as Release/Win32, everything is normal, but if you compile it as release/x64, London, earth, gets downgraded to a level 1 tech certificate.

previously on #4238 it was discussed and presumed that pioneer should be platform independent. this issue points out that its not.

**Comment by fluffyfreak** [comment]
Not 100% sure about this code here: https://github.com/pioneerspacesim/pioneer/blob/master/data/libs/SpaceStation.lua#L29

Looks like it could be suspect between Win32 & x64

**Comment by fluffyfreak** [comment]
@impaktor would it make sense to have a weighting of some kind so that planets closer to the homeworld have a higher tech level?

Also about the bug itself what do you think?

**Comment by impaktor** [comment]
> would it make sense to have a weighting of some kind so that planets closer to the homeworld have a higher tech level?

I don't think we should put that into the algorithm, instead, systems that are "core playground" to the player should be custom systems, where tech level can be set manually to what we explicitly want.

(I don't think we can set tech level explicitly atm, so that's something we want to have)

Also, if we put into the procedural code to put higher tech level closer to earh (where I assume players start from), then they instead of "unlocking" new featurs to buy when they travel further out into the universe, see the opposite: they get less equipment to buy the further out they go. Granted, that can simply be thought of as the game scaling up the difficulty level as the player has learned it and made more money.

**Comment by zonkmachine** [comment]
> Not 100% sure about this code here: https://github.com/pioneerspacesim/pioneer/blob/master/data/libs/SpaceStation.lua#L29

Lua? https://www.lua.org/bugs.html#5.2.3-1

If [hash_random](https://github.com/pioneerspacesim/pioneer/blob/9f14a5fe5589a06b02cd0c58d40d1be4014df96f/src/LuaUtils.cpp#L31) overflows it will go negative and this will result in a tech level of '1'.

**Comment by jaj22** [comment]
Don't like the hash_random code either, but there's a clear bug before that in `l_body_attr_seed` (LuaBody.cpp). `lua_pushinteger` is used to push the C-side seed value (unsigned 32-bit), but lua_pushinteger takes a `lua_Integer`, which is typedef'd to a `ptrdiff_t`: 32 bit signed integer on x86 (at least in MSVC) and a 64 bit value on x64. As a result, half of the seeds are negative numbers from the lua side in x86.

Possible solutions:
1. Mask out the top bit in l_body_attr_seed.
2. Push the seed as a lua number (double) instead.
3. Always typedef lua_integer to the same type.

May want to implement 2 to preserve the seed value and 3 for sanity elsewhere. Regardless of the fix chosen, there may be some effect on savegame compatibility.

**Comment by fluffyfreak** [comment]
Using `lua_pushunsigned` or `lua_pushnumber` leaves London with a tech level of 1 instead of 8 interestingly. Not sure what the value really should be...

I mean if we can set the tech level for a station then this becomes moot for Sol I'm just pointing it out 😄

**Comment by jaj22** [comment]
Ok, there's also a horror show involving the input of 2^31 to hash_random (LuaUtils.cpp, as used by SpaceStation.lua). The value's loaded as an integer, and so wraps around to negative, hence the result is a random value between -(2^31) and +1.

As far as I can tell, the result's the same on x86 and x64 because it's passed through an int, but it's not sane behaviour. Could just fix the SpaceStation.lua value to 2^31-1, although it seems a bit clumsy when it'd be straightforward to add a string input to Rand.New.

**Comment by joonicks** [comment]
> (I don't think we can set tech level explicitly atm, so that's something we want to have)

tech level is based off station seed, which can be manually set in custom systems. so, there is already a way to set the techlevel. if the rand is consistent over platforms...

**Comment by impaktor** [comment]
> tech level is based off station seed, which can be manually set in custom systems. 

that's a very "hacky" way of doing it. Ideally, we would like to specify both station model type (which we now can! (un-documented on wiki, I think, used for London)), and station tech level, in custom systems.

**Comment by fluffyfreak** [comment]
@impaktor I had a go at adding the tech leve then decided to keep the PR simple.
It generates the tech level in Lua in the spacestation constructor using the rand stuff and I couldn't think (_brain very tired_) of a way to get it cleanly from the C++

**Comment by johnbartholomew** [comment]
@jaj22 I don't want to derail the conversation, but:

> Don't like the hash_random code either

Don't like the concept? Or don't like the implementation? (Or both?)

**Comment by fluffyfreak** [comment]
It's the lack of clarity in what it's doing and why for me. 
Some comments about the choice of values etc would have been much appreciated. 
Especially when I'm only getting to look at the code after work when my brain is mush 🙄

**Comment by jaj22** [comment]
@johnbartholomew I was baffled by hash_random initially because it seemed inappropriate for this usage case. If the desired result was an integer seed value then you'd just take the first param straight from the lookup3 function, rather than doing mixed double/integer arithmetic with a range input. It looks like the intended purpose is to generate a random integer in a small range, and the usage in SpaceStation.lua is a bit of a hack.

I'm also not sure that the results are hardware-independent in corner cases. The value of x should be consistent but x*integer may not be. Consider that 3*(2^53-1) needs more than 53 bits of precision. If the code's being used to generate an RNG seed value then even a single bit error will completely change the output.

I would recommend separating the functionality: One function for 0-1 output (which can use the current double arithmetic), another for an integer range with only integer calcs (the aliasing problem is insignificant if you use the whole 64-bit hash as input), and another to return a simple seed. The latter could instead be implemented as a string input to Rand.New.
