### ISSUE TITLE
Lots of clang warnings

### ISSUE THREAD

**Issue by yurivict** [pioneerspacesim/pioneer#4309]
Getting these warnings and a lot more in version 20180203 on FreeBSD (in the port):

```
/usr/local/include/assimp/types.h:174:51: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        {return r != other.r || g != other.g || b != other.b;}
                                                ~ ^  ~~~~~~~
/usr/local/include/assimp/types.h:179:35: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        return r < other.r || ( r == other.r && (g < other.g || (g == other.g && b < other.b ) ) );
                                ~ ^  ~~~~~~~
/usr/local/include/assimp/types.h:179:68: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        return r < other.r || ( r == other.r && (g < other.g || (g == other.g && b < other.b ) ) );
                                                                 ~ ^  ~~~~~~~
SectorView.cpp:635:59: warning: format specifies type 'unsigned long' but the argument has type 'size_type' (aka 'unsigned int') [-Wformat]
        Output("SectorView::AutoRoute, nodes to search = %lu\n", nodes.size());
                                                         ~~~     ^~~~~~~~~~~~
                                                         %u
SectorView.cpp:696:79: warning: format specifies type 'unsigned long' but the argument has type 'size_t' (aka 'unsigned int') [-Wformat]
        Output("SectorView::AutoRoute, total times that nodes were skipped = %lu\n", totalSkipped);
                                                                             ~~~     ^~~~~~~~~~~~
                                                                             %zu
```

**Comment by jbeich** [comment]
GCC/Clang ignore warnings in system headers (see [`#pragma GCC system_header`](https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html)), so assimp issue can probably be hidden by `-isystem/usr/local/include` (aka `USES=localbase` in ports).

**Comment by senderghost** [comment]
Hello.

To @yurivict:
I appreciate your attention to compiler's warnings and some report to upstream about this.

Actually, there are different warnings for FreeBSD versions, based on used Clang compiler. For example:
FreeBSD 10.3-RELEASE amd64 (Clang 3.4.1)
https://github.com/freebsd/freebsd/blob/releng/10.3/lib/clang/include/clang/Basic/Version.inc#L3
http://beefy6.nyi.freebsd.org/data/103amd64-default/461453/logs/pioneer-0.0.20180203.log
FreeBSD 11.1-RELEASE amd64 (Clang 4.0.0)
https://github.com/freebsd/freebsd/blob/releng/11.1/lib/clang/include/clang/Basic/Version.inc#L3
http://beefy9.nyi.freebsd.org/data/111amd64-default/461460/logs/pioneer-0.0.20180203.log
FreeBSD 12.0-CURRENT amd64 (Clang 6.0.0)
https://github.com/freebsd/freebsd/blob/eae4eb0a6c2f5a4fff6a702c8f27751f3e0253bc/lib/clang/include/clang/Basic/Version.inc#L3
https://beefy12.nyi.freebsd.org/data/head-amd64-default/p461354_s329096/logs/pioneer-0.0.20171001_1.log
In last case, the build for 20180203 version wasn't ready (but listed/queued):
https://beefy12.nyi.freebsd.org/build.html?mastername=head-amd64-default&build=p461678_s329188

Some assimp's related warnings also listed on Travis build log(s):
https://travis-ci.org/pioneerspacesim/pioneer/builds/340744754
I guess, developers aware about them.

**Comment by senderghost** [comment]
To @jbeich:
If for some reason there are no interest about these warnings (or someone concerned about size of poudriere build logs with many warnings), there is a [--without-extra-warnings](https://github.com/pioneerspacesim/pioneer/blob/7225e9c723e1afe2b737c8ec1421e2c60d9b6257/configure.ac#L186-L219) configure option:
```
./configure --help | grep warnings
  --without-extra-warnings
                          Disable lots of extra compiler warnings
```

I can propose something like following for [games/pioneer](https://www.freshports.org/games/pioneer) port, if needed:
```
OPTIONS_DEFINE+=	EXTRA_WARNINGS
EXTRA_WARNINGS_DESC=	Enable extra compiler warnings
EXTRA_WARNINGS_CONFIGURE_OFF=	--without-extra-warnings
```

But if this will be not a default port's option (it's default for configure), it may be hard to check such warnings on FreeBSD build cluster (for various compilers).

The USES+=[localbase](https://github.com/freebsd/freebsd-ports/blob/f493fce6a3261de0136fe170a7b704c4fe236b88/Mk/Uses/localbase.mk#L19-L26) is not needed, because there are [enough](https://github.com/pioneerspacesim/pioneer/blob/7225e9c723e1afe2b737c8ec1421e2c60d9b6257/configure.ac#L284-L322) "/usr/local" for include and library directories on FreeBSD.
Excerpt from generated configure file:
```
<..>
pkg_cv_ASSIMP_CFLAGS=`$PKG_CONFIG --cflags "assimp" 2>/dev/null`
<..>
pkg_cv_ASSIMP_LIBS=`$PKG_CONFIG --libs "assimp" 2>/dev/null`
<..>
```
```
% pkg-config -cflags assimp
-I/usr/local/include 
% pkg-config -libs assimp
-L/usr/local/lib -lassimp 
```

and even some work was done to fix some source code for related [issue](https://github.com/pioneerspacesim/pioneer/issues/3869).

**Comment by impaktor** [comment]
I expect this to be very low hanging fruit for anyone wanting to pick them.

**Comment by Web-eWorks** [comment]
Most of these issues should be fixed by 3a3a13edec758fbfa9b1eae0e488a528ebb27468, specifically by the changes to files in `src/scenegraph`.

@yurivict @senderghost if you could test against latest master and report any errors you find back here?

@impaktor if this doesn't see any activity by end-of-year, I think it's safe to close.

**Comment by senderghost** [comment]
As I already said, the possible reason of this issue is usage of [extra-warnings](https://github.com/pioneerspacesim/pioneer/blob/7225e9c723e1afe2b737c8ec1421e2c60d9b6257/configure.ac#L186-L219) configure option by default, which added `-Wformat -Wstrict-aliasing=2 -Wmissing-format-attribute -Wmissing-noreturn -Wdisabled-optimization -Wfloat-equal -Wshadow -Wcast-qual -Wcast-align` compiler options to CFLAGS and CXXFLAGS.

The possible fix was to disable "extra-warnings" configure option by default (but enable for travis builds, for example). At least, this is what I wanted to propose for games/pioneer port for next (possibly stable, without "_test" as in latest [20181127_test](https://github.com/pioneerspacesim/pioneer/releases/tag/20181127_test) tag) release.

Personally, I didn't notice "-Wformat" warnings for [20180203](https://github.com/pioneerspacesim/pioneer/releases/tag/20180203) release tag on FreeBSD 10.4 amd64 (Clang 3.4.1). The same shows current build logs for FreeBSD 11.2-RELEASE-p6 amd64 (Clang 6.0.0):
https://github.com/freebsd/freebsd/blob/releng/11.2/lib/clang/include/clang/Basic/Version.inc#L3
http://beefy9.nyi.freebsd.org/data/112amd64-default/486731/logs/pioneer-0.0.20180203_1.log
and FreeBSD 12.0-RELEASE amd64 (Clang 6.0.1):
https://github.com/freebsd/freebsd/blob/releng/12.0/lib/clang/include/clang/Basic/Version.inc#L3
http://beefy6.nyi.freebsd.org/data/120amd64-default/486908/logs/pioneer-0.0.20180203_1.log

But there were a lot of warnings for "-Wfloat-equal" compiler option, which was related to some assimp's include file(s) (4.1.0 version). For example:
```
% clang++ --version | head -1
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512

% pkg info assimp | grep ^Version 
Version        : 4.1.0_1

% cat > test.cpp << EOF
#include <assimp/types.h>
int main() { return 0; }
EOF

% pkg-config -cflags assimp
-I/usr/local/include 

% clang++ `pkg-config -cflags assimp` -Wfloat-equal test.cpp
In file included from test.cpp:1:
/usr/local/include/assimp/types.h:169:19: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        {return r == other.r && g == other.g && b == other.b;}
                ~ ^  ~~~~~~~
/usr/local/include/assimp/types.h:169:35: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        {return r == other.r && g == other.g && b == other.b;}
                                ~ ^  ~~~~~~~
/usr/local/include/assimp/types.h:169:51: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        {return r == other.r && g == other.g && b == other.b;}
                                                ~ ^  ~~~~~~~
/usr/local/include/assimp/types.h:174:19: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        {return r != other.r || g != other.g || b != other.b;}
                ~ ^  ~~~~~~~
/usr/local/include/assimp/types.h:174:35: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        {return r != other.r || g != other.g || b != other.b;}
                                ~ ^  ~~~~~~~
/usr/local/include/assimp/types.h:174:51: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        {return r != other.r || g != other.g || b != other.b;}
                                                ~ ^  ~~~~~~~
/usr/local/include/assimp/types.h:179:35: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        return r < other.r || ( r == other.r && (g < other.g || (g == other.g && b < other.b ) ) );
                                ~ ^  ~~~~~~~
/usr/local/include/assimp/types.h:179:68: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        return r < other.r || ( r == other.r && (g < other.g || (g == other.g && b < other.b ) ) );
                                                                 ~ ^  ~~~~~~~
8 warnings generated.
```

Almost the same "-Wfloat-equal" warnings showed [travis build log](https://travis-ci.org/pioneerspacesim/pioneer/builds/336897349) for [20180203](https://github.com/pioneerspacesim/pioneer/releases/tag/20180203) release tag.

> Most of these issues should be fixed by 3a3a13e, specifically by the changes to files in src/scenegraph

There is no travis build log for 3a3a13edec758fbfa9b1eae0e488a528ebb27468 commit, but if compare logs for successful travis builds [before](https://travis-ci.org/pioneerspacesim/pioneer/jobs/439112928) and [after](https://travis-ci.org/pioneerspacesim/pioneer/jobs/440328232) 3a3a13edec758fbfa9b1eae0e488a528ebb27468 commit, there are much less warnings, especially for "-Wfloat-equal", which warning was disabled for GCC (compatible) compiler in [src/scenegraph/Loader.h](https://github.com/pioneerspacesim/pioneer/blob/3a3a13edec758fbfa9b1eae0e488a528ebb27468/src/scenegraph/Loader.h#L13-L23) file:
https://github.com/pioneerspacesim/pioneer/commit/3a3a13edec758fbfa9b1eae0e488a528ebb27468#diff-ae30fdc43f6555c06d3111b51f34cc42L12

The same patch also disables it for (supported) Clang compiler:
```
% cat > test.cpp << EOF
// Disable some GCC diagnostics errors.
#ifdef __GNUC__
	#pragma GCC diagnostic push
	#pragma GCC diagnostic ignored "-Wfloat-equal"
	#pragma GCC diagnostic ignored "-Wshadow"
	#pragma GCC diagnostic ignored "-Wold-style-cast"
	#include <assimp/types.h>
	#pragma GCC diagnostic pop
#else
	#include <assimp/types.h>
#endif
int main() { return 0; }
EOF

% clang++ `pkg-config -cflags assimp` -Wfloat-equal test.cpp
```

The latest 0e3f077441ba6a2dc7592817ad5924de5cafd550 commit doesn't build with using Clang 3.4.1 compiler, because it was stuck on [src/scenegraph/ModelSkin.cpp](https://github.com/pioneerspacesim/pioneer/blob/4be499f98f3915795edfcc7fc7c8022429d605cc/src/scenegraph/ModelSkin.cpp) file (for more than 20 minutes, after which I stopped the build). It builds, if update [contrib/json/json.hpp](https://github.com/pioneerspacesim/pioneer/blob/ec70cd27bd7e3d50db97c07f85ea8693b22dad25/contrib/json/json.hpp) file from 3.2.0 to [latest](https://github.com/nlohmann/json/blob/v3.4.0/single_include/nlohmann/json.hpp) [3.4.0](https://github.com/nlohmann/json/releases/tag/v3.4.0) version.

Also it builds ok (with and without contrib/json/json.hpp update) with using Clang 6.0.1 compiler (from [devel/llvm60](https://www.freshports.org/devel/llvm60) port). Some examples for Clang 6.0.1 warnings:
```
In file included from Loader.cpp:20:
In file included from /usr/local/include/assimp/scene.h:53:
/usr/local/include/assimp/light.h:244:36: warning: use of old-style cast [-Wold-style-cast]
        ,   mAngleInnerCone       ((float)AI_MATH_TWO_PI)
<..>
Background.cpp:277:64: warning: use of old-style cast [-Wold-style-cast]
  ...const size_t numSystems = std::min(sec->m_systems.size(), (size_t)(NUM_BG_STARS - num));
                                                               ^       ~~~~~~~~~~~~~~~~~~~~
<..>
FixedGuns.cpp:116:23: warning: declaration shadows a local variable [-Wshadow]
                                const std::string tag = stringf("tag_gunmount_%0{d}", num); //"gunmount_0";
                                                  ^
<..>
JsonUtils.cpp:472:24: warning: use of old-style cast [-Wold-style-cast]
                binStr = std::string((char *)pDecompressedData, outSize);
                                     ^       ~~~~~~~~~~~~~~~~~
JsonUtils.cpp:27:11: warning: unused function 'pack4char' [-Wunused-function]
        uint32_t pack4char(const uint8_t a, const uint8_t b, const uint8_t c, const uint8_t d)
                 ^
JsonUtils.cpp:32:7: warning: unused function 'unpack4char' [-Wunused-function]
        void unpack4char(const uint32_t packed, uint8_t &a, uint8_t &b, uint8_t &c, uint8_t &d)
             ^
<..>
PiGui.cpp:557:23: warning: using integer absolute value function 'abs' when argument is of floating point type
      [-Wabsolute-value]
        const ImVec2 up(0, - abs(leftupper.y - rightlower.y) * 0.4);
                             ^
PiGui.cpp:557:23: note: use function 'std::abs' instead
        const ImVec2 up(0, - abs(leftupper.y - rightlower.y) * 0.4);
                             ^~~
                             std::abs
<..>
In file included from Sound.cpp:11:
/usr/local/include/vorbis/vorbisfile.h:75:3: warning: use of old-style cast [-Wold-style-cast]
  (size_t (*)(void *, size_t, size_t, void *))  fread,
  ^     
<..>
ShipType.cpp:55:41: warning: more '%' conversions than data arguments [-Wformat]
                Output("couldn't read ship def '%s': %s\n", path.c_str());
                                                     ~^
<..>
In file included from versioningInfo.cpp:11:
In file included from /usr/local/include/freetype2/freetype/freetype.h:34:
In file included from /usr/local/include/freetype2/freetype/fttypes.h:26:
/usr/local/include/freetype2/freetype/ftimage.h:717:5: warning: use of old-style cast [-Wold-style-cast]
    FT_IMAGE_TAG( FT_GLYPH_FORMAT_NONE, 0, 0, 0, 0 ),
    ^                                   ~
<..>
```
But there were no "-Wfloat-equal" warnings.

On the other hand, the pioneer runs ok, but after quit showed following [assertion](https://github.com/pioneerspacesim/pioneer/blob/9f60062f99f9f0dd8f9b439b0de8063d048702b4/contrib/imgui/imgui_draw.cpp#L1411) (in console):
```
Assertion failed: (!Locked && "Cannot modify a locked ImFontAtlas between NewFrame() and EndFrame/Render()!"), function ~ImFontAtlas, file imgui_draw.cpp, line 1411.
Segmentation fault (core dumped)
```

**Comment by Web-eWorks** [comment]
@senderghost Thanks. I'll investigate compilation with Clang (pioneer officially supports GCC) and work out what's the best method to move forward from there.

The IMGUI segfault is a known bug that is (or will be) tracked in a separate issue.

**Comment by impaktor** [comment]
@Web-eWorks status on this?

**Comment by Web-eWorks** [comment]
@impaktor IMGUI segfault fixed by fluffy, will try to compile Pioneer with clang and determine best route today.

**Comment by Web-eWorks** [comment]
`FenderQ` on IRC was kind enough to compile pioneer on OpenBSD to test the status of this issue. As evidenced by [the log](https://pastebin.com/6ucZxc5Y), the build process only generates two warnings, one that's also thrown by GCC, and one libcpp warning.

@impaktor this issue can be closed.

**Comment by impaktor** [comment]
@Web-eWorks thanks!
