### ISSUE TITLE
Auto Pilot Bug

### ISSUE THREAD

**Issue by FronteirUser** [pioneerspacesim/pioneer#4325]
### Observed behaviour
Occasionaly when flying to distant planets / space stations, the Auto Pilot will loose its focus, and over shoot where it is supposed to be going.  Case in point I was jumping to a planet that was 12,au distance away, and got to less then 1AU away, then the auto pilot crashed and took me back to 2AU and getting further and further away and would not work again, making me abort my cargo run.  I think this bug was also in the Original Frontier too.    

### Expected behaviour
At least get me where i am going with our loosing my target.

### Steps to reproduce
Jump to a planet or Space Station of 10AU or more, and OCCASIONALLY, it will crash.

__My pioneer version (and OS):__ 
Running Windows 10  
Pioneer Build February 2018

**Comment by nozmajner** [comment]
I suspect it is a known bug/limitation. The autopilot doesn't lead the target, but adjusts all the way to the target. Which makes it using way more propellant than it should, especially when going towards objects in a tight orbit, since they are moving around their planet quite fast.
At least I think that's the problem in this case, based on your description. 
You could try two workarounds:
- Target the parent body of your target and set the autopilot to approach, and only change target and instruct to approach/dock, when you are reasonably close.
- Cut your autopilot when the acceleration phase is over, wait until the right white bar is almost filled (if red, you will overshoot), then engage the autopilot again. This way the autopilot won't waste fuel for course corrections during the coasting phase.
I'd say, try to learn to fly manually, it's much more interesting than watching the autopilot doing it, and it's not that hard. [There's a tutorial on it on the wiki](https://pioneerwiki.com/wiki/How_to_fly_without_autopilot).

**Comment by impaktor** [comment]
Not sure if we should keep this open? @jaj22 is the auto pilot expert: is this a bug or just a limitation?

**Comment by FronteirUser** [comment]
It's not a bug I ran out of fuel silly me.
