### ISSUE TITLE
Mouse target and pointer misalignment

### ISSUE THREAD

**Issue by quickdudley** [pioneerspacesim/pioneer#4481]
![mousepointer](https://user-images.githubusercontent.com/5417572/47272698-dd30f380-d5e5-11e8-9593-770692b3181a.png)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/2499632/opengl.txt)
[imgui.ini](https://github.com/pioneerspacesim/pioneer/files/2499634/imgui.ini.txt)

Bug is absent in 7d64219900, and present in 9f60062f99f and all descendants.

### Observed behaviour
All parts of the game consistently behave as if the mouse pointer were lower than it actually is.

### Expected behaviour
The tip of the mouse pointer should be the same as the program's internal representation of the mouse position.

### Steps to reproduce
Run Pioneer

__ver git (b360ab0) on: Linux__

**Comment by Web-eWorks** [comment]
In your screenshot, the WM is responsible for positioning that cursor, and it is the values reported by said WM that SDL is reading. I'm going to need some more information: what distro and DE/WM are you running, and have you had issues of this type with other SDL applications before?

There's a possibility that this is being caused by a specific code section; can you change: https://github.com/pioneerspacesim/pioneer/blob/173b11adff1bb384586077810f897bd460dcd207/contrib/imgui/examples/imgui_impl_sdl.cpp#L274 to read `#if 0` and re-test?

**Comment by quickdudley** [comment]
Yes, disabling that code section resolved the issue on my machine. I am using Linux Mint with the Cinnamon DE. I think Pioneer might be the only SDL application I've run since switching distro a few months ago.

I had suspected this bug might have been a Wayland issue, but turns out I'm not actually running Wayland.

**Comment by Web-eWorks** [comment]
It seems that bug's related to several issues we have.

@quickdudley, @ecraven, @fluffyfreak:
Can you test the fix I listed above and confirm whether it causes any strange issues and/or resolves the issue with the mouse snapping to center when using a right-click radial menu? I *think* we're not going to have any major issues with this change, but I want to be sure.

**Comment by quickdudley** [comment]
I didn't notice any additional issues while playing with this fix applied.
