### ISSUE TITLE
Zenith indicator pointing somewhere wrong

### ISSUE THREAD

**Issue by CylonicRaider** [pioneerspacesim/pioneer#4587]
### Observed behavior

The zenith indicator does not always point away from the current reference body. The deviation varies from nearly none to rather extreme, with a sample leaning towards the latter seen in the following screenshot:

<p align=center>
<img src="https://user-images.githubusercontent.com/12989435/57587790-396c4e00-750b-11e9-8655-9e566490e8e3.png" alt="Zenith indicator pointing the wrong way">
</p>

(observe how the indicator is some mere (estimated) 30° away from the nadir).

### Expected behavior

The zenith indicator *should* always point away from the current reference body.

### Steps to reproduce

As noted in https://github.com/pioneerspacesim/pioneer/pull/4583#issuecomment-491272837,
1. Start a new game on Mars.
2. Blast off and use the autopilot to enter a low orbit around Mars (time acceleration may be used to reduce your wait).
3. Point the ship's bow at the zenith indicator: Ensure you are looking forward (w.r.t. the ship); holding the right mouse button, move the mouse until the yellow double circle [and the forward direction indicator] coincides with the zenith indicator.
4. Look backward (w.r.t. the ship; in a default install, this is bound to the `Down` arrow key).
5. Observe how the icon representing Mars (a dot with the text “Mars” besides it) is *not* in the center of the reticule.

Remark that this does not lead to as extreme an instance of this bug as the screenshot above. (Perhaps, entering and leaving the frame of an in-orbit starport might “help”.)

### My Pioneer version

Observed on the current commit of #4583, i.e. be341d43a94136aa669a05f579c1aeb7dbb50443, (where the screenshot was taken) and on current `master`, i.e. ea0126494f4e93287a1f5ce74d5971e411f77d43. If my memory serves me right, this bug is, however, much older than either commit.

**Comment by jaj22** [comment]
Fairly straightforward error. displayFrameIndicators in game.lua calls the function:

`local awayFromFrame = player:GetPositionRelTo(frame) * 1.01`

A->GetPositionRelTo(B) returns the relative position in B's frame. In this case, B is the planet, and planets are placed in the rotating frame. As the camera is outside the rotating frame, that's not what you want. Semi-correct version is:

`local awayFromFrame = frame:GetPositionRelTo(player)`

I'm not sure the reason was for the 1.01, but it's probably not a good one.

I say "semi-correct" because UI code should be using interpolated rather than physics positions and orientations to avoid jitter, but I'm not sure whether that functionality has been exposed to lua.

**Comment by CylonicRaider** [comment]
The incorrect `local awayFromFrame = ...` was introduced in commit 3fe0836a2da980cb5169465893658ac8c0f9706c as part of #3868, with — apparently — no equivalent having existed before.

**Comment by CylonicRaider** [comment]
@jaj22's “semi-correct version” works well for me; in which way is it only *semi*-correct?

**Comment by mike-f1** [comment]
I'm just guessing @jaj22 refers to these functions:

https://github.com/pioneerspacesim/pioneer/blob/d4c1ba4f6bc0e63ed29244f03882c03f5f87fa3d/src/Body.h#L91-L104

And to the fact that these functions should be used during render calls
because rendering isn't in sync with physics updates. Thus when render
happens these functions should be used instead of the "physical"
counterparts.

**Comment by CylonicRaider** [comment]
So... to correct the issue, one should provide Lua wrappers for the “interpolated” functions and do `local awayFromFrame = -frame:GetInterpPositionRelTo(player)`?

**Comment by jaj22** [comment]
@CylonicRaider Yeah. In this case the direction of the frame body isn't vulnerable to interpolation jitter so it doesn't really matter, but ideally you set an example.
