### ISSUE TITLE
Venus (ringless) has rings in pioneer

### ISSUE THREAD

**Issue by jmf** [pioneerspacesim/pioneer#4652]
Venus is a ringless planet. It has rings in the game though.
Pioneer version: git master d72e4e9dc9dbd1f48109419d36ca322ebc7ec2d2

![venus](https://user-images.githubusercontent.com/1857532/61999719-cd839580-b0b6-11e9-8af4-f5d3af3953af.png)

**Comment by nozmajner** [comment]
That's rather odd. It does not have a ring entry in the system file.

**Comment by fluffyfreak** [comment]
ah, I know why, it's because it defaults to `RingStatus::WANT_RANDOM_RINGS` in the `CustomSystemBody` ctor

**Comment by fluffyfreak** [comment]
@johnbartholomew do you recall why you set it to random by default? It's not a problem either way I'm just curios what the motivation was.

**Comment by impaktor** [comment]
> Venus (ringless) has rings in pioneer

I know there's a joke in here somewhere, but can't find it right now.

> do you recall why you set it to random by default?

I remember hearing "rings" being very common, so having a 50-50 chance as default might make sense? If so, we need to set all Sol planets explicity to correct on/off on the rings.

**Comment by fluffyfreak** [comment]
The randomness of rings is 1/10 for terrestrial planets, 1/2 for gas giants. So common for gas giants but not that common for planets for example, not sure if having a moon affects it too.

However yeah we could either eliminate them manually, or since the default for custom systems is random I could just change that to no rings by default in the ctor. That way custom systems have a little less randomness in them, since they are authored after all.

**Comment by johnbartholomew** [comment]
>
> @johnbartholomew <https://github.com/johnbartholomew> do you recall why
> you set it to random by default? It's not a problem either way I'm just
> curios what the motivation was.
>
I can't look at the code history right now, but my recollection is that I
wanted custom systems to be able to rely on the generator for details where
possible, so that a system author could just set a few things that they
care about for whatever they're doing and still end up with an
interesting/unique system.

**Comment by impaktor** [comment]
I think the most sane fix is to explicitly state ring state for all planets in Sol system, as it makes sense to have random generation if ring state omitted in custom systems, unless I'm missing something.

So this should be low hanging fruit.

**Comment by fluffyfreak** [comment]
I've put exactly that fix in, just told it that those worlds don't want rings
