### ISSUE TITLE
Sector Map: Auto Route button crashes game when no hyperdrive fitted

### ISSUE THREAD

**Issue by craigo-** [pioneerspacesim/pioneer#4667]
### Observed behaviour
With a ship that is not fitted with a hyperdrive, pressing the "Auto Route" button on the sector map results in a game crash:

![image](https://user-images.githubusercontent.com/4467963/63200154-44b7b280-c0d4-11e9-9444-32752ec26a18.png)

### Expected behaviour

That the game doesn't crash 😄

Perhaps for ships without a hyperspace drive, pressing the "Auto Route" button could generate an informational alert (e.g. "No hyperdrive"), or perhaps simply do nothing at all.  

### Steps to reproduce

1. Start at Barnard's Star (Xylophis, no hyperdrive)
2. Switch to Sector Map
3. Select any system distant from Barnard's Star
4. Click "Auto Route"

NB: when doing the above with a hyperdrive-equipped ship, the game does not crash.

__My pioneer version (and OS):__

Pioneer 20190203, and compiled from master (commit 4bc31eef4700b343256cb1dae604622680c534d8)

Windows 10 Enterprise 1809 x64

**Comment by mike-f1** [comment]
The bug raise in
 https://github.com/pioneerspacesim/pioneer/blob/4bc31eef4700b343256cb1dae604622680c534d8/src/SectorView.cpp#L595

when a `GetMaximumRange` is searched in an empty table, as the previous line is
getting an engine which is not present.

In particular, when `PushValueToStack` (in `LuaTable.h`, line 311) calls `lua_gettable`, it (eventually) fail.

A fast workaround is to check in Lua if there's an engine, but a better solution may be to put a general mechanism to check if there's a value that should be returned.

What's your thoughts?

Ping @Web-eWorks , @ecraven and @laarmen

**Comment by impaktor** [comment]
I assume C++ side shouldn't fail with a crash, but fail with grace, like a ballerina falling on her ass.

**Comment by laarmen** [comment]
(I'm not claiming authorship of the autorouting code, just the bit fetching
the hyperspace range)

**Comment by mike-f1** [comment]
> If that's the case, that's IMO a bug.

:+1:

> However, a method to actually check that it is the case, that would be called explicitly,
would be a great addition.

This line:
https://github.com/pioneerspacesim/pioneer/blob/4bc31eef4700b343256cb1dae604622680c534d8/src/SectorView.cpp#L593

is initializing a `ScopedTable` from a `LuaRef`, which already has a `IsValid()` method.
However, that method seems not working: splitting that line in
```
	LuaRef lua_ref = LuaObject<Player>::CallMethod<LuaRef>(Pi::player, "GetEquip", "engine", 1);
	if (!lua_ref.IsValid()) return;

	const ScopedTable hyperdrive = ScopedTable(lua_ref);

```
doesn't prevent the error as a `LUA_NOREF` is -2 whilst `lua_ref.m_id` is -1 ([here the link](https://github.com/pioneerspacesim/pioneer/blob/4bc31eef4700b343256cb1dae604622680c534d8/src/LuaRef.h#L28))

And here I start having troubles understanding why the above happens and what's the logic behind :worried: 

...If I may suggest something, all the above could be helped with a check on lines:

https://github.com/pioneerspacesim/pioneer/blob/4bc31eef4700b343256cb1dae604622680c534d8/src/LuaTable.h#L310-L316

which print if there's no value for the given key improving (or I hope so) debugging...

**Comment by laarmen** [comment]
I can think of a number of ways to do fix all this. First off, we should be
able to directly return a ScopedTable from CallMethod by using move
semantics to avoid the destructions triggered by the returns. That would
mean getting rid of the LuaRef, whose use is way overkill here. However,
this means that we still need a way to report back to the caller that there
is no hyperdrive. Is there an Option<T> type in C++ these days ?

**Comment by Web-eWorks** [comment]
@laarmen maybe I'm reading this wrong, but I don't see a way to directly return a ScopedTable from `LuaObject<T>::CallMethod()` - not only does CallMethod delete the return value from the stack, but there's no `pi_lua_generic_pull` overload for ScopedTable or LuaTable for that matter. How are you thinking of rectifying this?

**Comment by mike-f1** [comment]
> Is there an Option<T> type in C++ these days ?

https://en.cppreference.com/w/cpp/utility/optional ...but it needs C++17, which is quite an(other) overkill...

My question is when an "empty object" wrapped in a `LuaRef` should be considered valid? ...Which is similar to your thought:

> "why is the hyperdrive an empty table and not `nil`"

...because if there's no need for an empty object/table then that is a design (and logic) flaws...

@Web-eWorks , you should consider that that method is working if an `hyperdrive` is present:
indeed it calls [this function](https://github.com/pioneerspacesim/pioneer/blob/4bc31eef4700b343256cb1dae604622680c534d8/src/LuaObject.h#L393-L411) in order to retrieve a "valid" `LuaRef`...

Thus all this issue is about "how to handle error when C++ needs Lua", and "how to crash in your feet" (= giving right hints to devs and useful messages)

**Comment by laarmen** [comment]
I might have been talking out of my arse the entire conversation here,
since I only had access to the code via Github, but yeah I foresaw
this answer :-)

In this specific case, we could insert a copy of the table under all
the return values in the _generic_pull() for ScopedTable. Sure, it
would break the tacit invariant that we leave the stack the way we
found it. I *think* ScopedTable wouldn't mind such a solution, I dunno
about LuaObject though.

**Comment by Gliese852** [comment]
So, maybe we just won't call this function if we don't have a drive and check it in lua-side? Anyway, we will not be able to correctly calculate the optimal route, not knowing for which drive we are calculating.
