### ISSUE TITLE
texts are rendered to big

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4689]
OS: Linux
Version: 24-04-2019

![Bildschirmfoto vom 2019-10-07 19-57-38](https://user-images.githubusercontent.com/8317797/66336315-208e8a00-e93d-11e9-8d76-c4f47acd25ac.jpg)

**Comment by Web-eWorks** [comment]
@Cyborgscode we're going to need more information than that to debug the issue. Please provide us your screen resolution, graphics card and driver information, and the output from `xrandr -q` run on the affected system.

**Comment by Cyborgscode** [comment]
Resolution: 1920x1080 
GFX: Nvidia GTX-1050 with Nvidias own drivers: v430.40
 


$ xrandr -q
Screen 0: minimum 8 x 8, current 3200 x 1080, maximum 32767 x 32767
DVI-D-0 connected 1280x1024+1920+0 (normal left inverted right x axis y axis) 380mm x 300mm
   1280x1024     60.02 +  76.00    75.02*   72.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32  
   640x480       75.00    72.81    59.94  
   640x350       70.07  
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+  59.94    50.00    60.05    60.00    50.04  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
HDMI-2 disconnected (normal left inverted right x axis y axis)

**Comment by Web-eWorks** [comment]
Alright, thanks @Cyborgscode. We'll look into the issue. I suspect it's caused by the extra monitor running at 1280x1024; it appears something in the Pioneer<->ImGui stack is scaling the fonts larger than they should be.

By chance, is your system set at a higher DPI scaling than normal? We've never quite been able to track down what causes this scaling problem, but that *might* be responsible.

If you get the chance, please try compiling the latest master branch; it's possible the issue has been resolved since the 2019-04 release.

**Comment by Cyborgscode** [comment]
No, DPI-Scale is 100%.

**Comment by Cyborgscode** [comment]
FIXED in 20191009
