### ISSUE TITLE
Linux: 100% cpu usage of Xorg at end of hyperjump

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4707]
OS: Fedora 29/64/Xorg
Version: 20191009-2
Resolution: 1920x1080 + 1280x1024 ( dual display )
GFX: GTX-1050
Drivers: original Nvidia 430.40-1
Settings: attached / all is set at max

While performing a 27lj hyperjump, the cpu usage of the Xorg process reaches 100%  on a single core at > ~85% of the jump . This results in skips and jumps while  i.e. video playback on the second display and it slows down the hyperjump counter itself. The later could be intended ;) 

It's only noticeable at long jumps.

[config.ini.tar.gz](https://github.com/pioneerspacesim/pioneer/files/3720949/config.ini.tar.gz)

**Comment by fluffyfreak** [comment]
This might just be because of the number of lines rendered. The actual jump counter is *supposed* to slow down, but it's drawing a lot of lines and updating a lot of buffers.

Go into the options and try reducing the density of the starfield to it's minimum, does that get rid of the slowdown and CUP usage? If so just bring it back upto an amount that you're ok with.

**Comment by impaktor** [comment]
Does the number of lines draw increase with distance / time in hyperspace?

If so, I assume one could just have number of lines as function of distance be a sigmoid function
![An-illustration-of-the-signal-processing-in-a-sigmoid-function](https://user-images.githubusercontent.com/619390/66717202-a9427580-edd6-11e9-90ee-34cbedf814c3.png)

**Comment by fluffyfreak** [comment]
It's a constant number of lines (_though I like the idea of it varying_) it's just that's there's a fucktonne of them!

**Comment by Cyborgscode** [comment]
CPU: FX-8350

Decreasing it to "lowest" made it much better.
