### ISSUE TITLE
gl info request

### ISSUE THREAD

**Issue by Askmewho** [pioneerspacesim/pioneer#4727]
Hi! whats the gl profile required for this project? does support gles too? thanks on advance

**Comment by fluffyfreak** [comment]
GL required is approximately 3.1, it's actually 3.0 with extensions. This was so it could run on the versions of OSX that most of our users seemed to have.

There is a Vulkan renderer in the works but future features/plans are never guaranteed to happen.

It doesn't have a GLES renderer because tutorials on them are, at as far as I can find, pretty rubbish.

Please don't use the GitHub issues to contact us there are a number of other ways to do so:
Forum: https://pioneerspacesim.net/forum/
IRC: https://webchat.freenode.net/#pioneer
