### ISSUE TITLE
[Feature Request] Add retroreflectors to the shading

### ISSUE THREAD

**Issue by HybridDog** [pioneerspacesim/pioneer#4734]
As far as I know, pioneer does not yet support retroreflective surfaces; I have not played it for a long time, so please correct me if I am wrong.
https://en.wikipedia.org/wiki/Retroreflector
![retro exampl](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/CarWithReflectiveStickers.jpg/640px-CarWithReflectiveStickers.jpg)
The retroreflector reflects the light (almost) independent of the surface's normal vector, and the intensity depends on the angle between the view and light vector.
Since in pioneer you can fly around in space, park, etc. (resemblance to road traffic), retroreflectors could be used in many situations, for example they could appear on the landing platforms. If your spaceship has headlights and you are in first person view, the retroreflectors can be as bright as emissive lights.
I think a retroreflection has the same colour than the diffuse light, but the intensity is different, and there is some angle falloff parameter similar to the specular reflection's shininess. 

> Feature request? Please consider IRC, player- or dev-forum instead 

I have tried IRC and it told my `Cannot send to nick/channel`.

**Comment by nozmajner** [comment]
Could be a nice addition. @Web-eWorks what do you think?
You can't speak on freenode unless your nick is registered. Appearently there were/are lot's of spambot issues.

**Comment by Web-eWorks** [comment]
@HybridDog do a quick web search on freenode's NickServ and that should turn up the method to register your account. Freenode sadly receives a lot of spam, so measures have to be taken.

@nozmajner this is perfectly doable - it's just some shader magic and a new material type. As far as utility goes, I'm not sure if it's worth it to implement; we don't have much in the way of movable lights, so the main benefit of modelling a retroreflector instead of e.g. an emissive light plane is pretty much lost.

That could change, however; I've been wanting to up the visual quality of Pioneer for a while, and part of that is more / better lighting on ships, stations, and planets. For now, this is probably a lower-priority feature request.

**Comment by impaktor** [comment]
@HybridDog Please use dev-forum or IRC if you want to discuss new features to add.

**Comment by HybridDog** [comment]
> @HybridDog do a quick web search on freenode's NickServ and that should turn up the method to register your account.

I'm going to do this next time.

**Comment by impaktor** [comment]
I'm going to close this, unless this is something @fluffyfreak / @Web-eWorks wants to work on this, since long term "plans" / stuff that should not be dealt with promptly belong on wiki or forum.

**Comment by Web-eWorks** [comment]
Closing for now; we'll revisit and re-evaluate once the new shading model is in place.
