### ISSUE TITLE
20200203 : can't load old game - crashing

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4793]
__My pioneer version (and OS):__

Version: 20200203
OS: Fedora 30

### Observed behaviour

decompressed model file venturestar.sgm (584.70 KB) -> 1083.24 KB
decompressed model file wave.sgm (386.94 KB) -> 717.74 KB
decompressed model file xylophis.sgm (125.83 KB) -> 275.90 KB
Game::LoadGame('_exit')
Loading saved game '_exit' failed: wrong save file version.
error: [string "[T] @pigui/views/mainmenu.lua"]:138: This saved game cannot be loaded because it contains errors.
stack traceback:
	[C]: in function 'LoadGame'
	[string "[T] @pigui/views/mainmenu.lua"]:138: in function 'callback'
	[string "[T] @pigui/views/mainmenu.lua"]:92: in function 'mainTextButton'
	[string "[T] @pigui/views/mainmenu.lua"]:215: in function 'fun'
	[string "[T] @pigui/pigui.lua"]:97: in function 'window'
	[string "[T] @pigui/views/mainmenu.lua"]:214: in function 'fun'
	[string "[T] @pigui/pigui.lua"]:146: in function 'withStyleColors'
	[string "[T] @pigui/views/mainmenu.lua"]:213: in function 'showMainMenu'
	[string "[T] @pigui/views/mainmenu.lua"]:260: in function 'mainMenu'
	[string "[T] @pigui/pigui.lua"]:187: in function <[string "[T] @pigui/pigui.lua"]:185>
... UI Crash Notification ...
Exit()

### Expected behaviour

able to load  old games

**Comment by Web-eWorks** [comment]
`Loading saved game '_exit' failed: wrong save file version.`
This happens, every once in a while, when we update the internal save format version. Old saves become no longer compatible, and new saves are not backwards compatible. Coincidentally, that happened between 20190203 and 20200203.

The solution to this is to use an older version of Pioneer if you wish to continue that save, otherwise simply start a new one.
Closing as WONTFIX.
