### ISSUE TITLE
Landing fee charged when starting a new game

### ISSUE THREAD

**Issue by pcercuei** [pioneerspacesim/pioneer#4804]
### Observed behaviour

I am being charged 6 credits at the very beginning of the game, for "landing". This is unacceptable. How could I have been landing before starting the game?

### Expected behaviour

The player should start with 100 credits, as advertised in the main menu. Anything else is just false advertising.

### Steps to reproduce

Start a new game. Get unjustly charged. Complain.

__My pioneer version (and OS):__
Latest master (e25517163) on Debian x64.

**Comment by impaktor** [comment]
StationRefuelling only triggers for `onShipDocked`, not `onGameStart`, so question is if the former event is triggered when starting a new game, when already having played another, because I assume this doesn't happen when starting a new game from just started pioneer instance? (I've never seen it happen, and I usually don't start several new games in a row without restarting pioneer)

**Comment by pcercuei** [comment]
It happens even after a cold boot.

**Comment by Echoes91** [comment]
`onShipDocked` is being triggered also when starting a new game. I've proposed a simple fix.
