### ISSUE TITLE
segfault when loading save

### ISSUE THREAD

**Issue by robintown** [pioneerspacesim/pioneer#4848]
I'm experiencing a segfault when I try to load the save file that I have attached. This was an autosave from landing at a station on a planet after completing a search and rescue mission in another system. Nothing particularly unusual was happening in game, and I was able to continue playing, with several other autosaves after this (all of them segfault). It could possibly be related to #4670 since the star in this system is a type M, but I doubt it since the backtraces don't look similar and I was able to play in this system for about an hour without issues before quitting.

[_autosave9.gz](https://github.com/pioneerspacesim/pioneer/files/4399764/_autosave9.gz)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/4399767/output.txt)

__My pioneer version (and OS):__

Pioneer c7638df
Also occurs with latest master (2e44d93).
Linux 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux

**Comment by impaktor** [comment]
And this was loading saves that had been made on the same version of pioneer?

**Comment by robintown** [comment]
Yes

**Comment by Web-eWorks** [comment]
From what I can see, this is happening when the AI is being told to orbit a body that doesn't exist anymore - an invalid body index is being serialized into JSON and loaded correctly, and is then causing a segfault because an invalid body index cannot be translated into a body pointer.

This will require significantly more work to fix on the save-to-disk side as we cannot do anything but patch the crash on the load side.

**Comment by Web-eWorks** [comment]
Closing this, the segfault behavior was fixed by a PR from Fluffy a while ago and it's unclear if the issue that was resulting in invalid body indices still exists.
