### ISSUE TITLE
Lost hypedrive equipment and capability after landing (but not its mass)

### ISSUE THREAD

**Issue by Echoes91** [pioneerspacesim/pioneer#4854]
### Observed behaviour
I departed for a mission with class 3 hyperdrive fitted on. After the flight (which involved 2 jumps by the way) I landed and found that ship had no jump capability and no hyperdrive fitted on (both from ship information and equipment list).
The 20 tons however are still occupied, so there's no room to replace it.

### Expected behaviour
Have my hyperdrive still there (or, if it exploded after the last jump, receive some kind of warning and have its space/mass freed).

### Steps to reproduce
Open the [first autosave](https://drive.google.com/open?id=1hRQB7x2BToHK-9Yl3Xrfg93E7QbMs5ds), do the mission and land on Riggs Station in Urla, otherwise check directly the [last autosave](https://drive.google.com/open?id=1CRpZYA8Za5M0aWlUcJyjC2VNEDS2mG5t).

pioneer 20200404 (2e44d9302) on Arch Linux x86_64

**Comment by rledgister** [comment]
Check your cargo hold, when the BreakdownRepair module decides it has been too long past the warranty, it removes your drive and then adds a comparable amount of mass of rubbish to your cargo hold. It does this without telling you, so that's still an issue, but this is just a feature of the game that doesn't give very clear explanation. It should perhaps record when this happens and have a bit of flavor from the repair team saying "Your drive is nothing but scrap, clear it out and you can buy a new one." Or make a scrapped engine equipment that it costs money to remove.

**Comment by Gliese852** [comment]
There should have been a message in the CommsLog, stating that the hyperdrive has been destroyed.

**Comment by impaktor** [comment]
Probbably triggered by #4909 

I don't see any statement that there wasn't any comms message about this, as you will get a message in your comms:

`Comms.Message(l.THE_SHIPS_HYPERDRIVE_HAS_BEEN_DESTROYED_BY_A_MALFUNCTION)`

Please (re-)open, if it can be confirmed that broken hyperdrive doesn't display the message above.
