### ISSUE TITLE
Visual Studio Project Doesn't Build

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#4884]
I know about the Visual Studio project file not building.

The CMake version is probably ok.

I'm just making this issue to force myself to find the time to update it.

**Comment by The-EG** [comment]
I was thinking about this project, and decided to check out the current state of things since I had a couple of hours to toy around with...I did get it to build in VS2019, included updated pioneer-thirdparty, but that took up the couple of hours I had to spare and it's going to take a few more to separate everything out into separate pull requests and what-not.

If you get to working on this before I have a chance to do that, here's what I found:

Source files missing in some of the projects (or were moved and need to be fixed):
  - src/core/GZipFormat.cpp
  - src/core/LZ4Format.cpp
  - src/core/Log.cpp
  - src/core/IniConfig.cpp

A new sub-project needs to be created for fmt, source files from contrib/fmt/src, output as a .lib. This needs to be set as a dependency for pioneer, modelcompiler (and maybe others?).
Add '../../contrib/fmt/include' and '../../../contrib/fmt/include' to include dirs to the subprojects that reference fmt (most of them). 
Add 'fmt.lib' to the additional linker dependencies to the pioneer, modelcompiler (& savedump?) projects.

It seems that SIZET_FMT should always be set to "%zu" now that fmt is being used: (src/libs.h: 44-47). This was set to "%Iu" on WIN32, but that causes an unhandled fmt::v6::format_error exception from fmt::sprintf ("%zu" seems to work fine).

If I get a chance I'll see if I can get everything setup again to submit fixes for all of this.

**Comment by fluffyfreak** [comment]
That's great work @The-EG thanks for doing that, I'm hoping to take a look Thursday as I've taken a couple of days off.

**Comment by impaktor** [comment]
@The-EG welcome back, good work, we'd love to see you make a PR of your progress! I suspect things are slow among the rest of us, at the moment.

**Comment by The-EG** [comment]
Thanks! And sorry for all of the commits...it's taking me a bit to figure out how to do all of the git stuff properly again.
