### ISSUE TITLE
FrameID Crash when Loading Saves on Debug Build

### ISSUE THREAD

**Issue by The-EG** [pioneerspacesim/pioneer#4898]
### Observed behaviour
Pioneer crashes due to an assertion failure when loading a saved game, when built on Windows x64 (VS 2019 Project) in the Debug configuration.

The failed assertion is `assert(s_frames.size() == 0 || (s_frames.size() - 1) != f->m_thisId.id());` within `Frame::FromJson`. (https://github.com/pioneerspacesim/pioneer/blob/master/src/Frame.cpp#L191)

Loading a save works as expected in Release configuration.

### Steps to reproduce
 - Build Pioneer in Debug-x64 configuration within Visual Studio
 - Run Pioneer-x64-debug.exe
 - Start a new game
 - Save game
 - End game
 - Load saved game
 - (crash)

__My pioneer version (and OS):__
Windows 10
Visual Studio 2019
current master (https://github.com/pioneerspacesim/pioneer/commit/033964b711d1f8b350923816e8b700a61709f83a)

**Comment by Web-eWorks** [comment]
Can confirm this happens on Linux x64 Debug as well, as it works fine (gameplay wise) in Release builds, I've not made the time to track it down.

It's related to sanity-checks in Frame.cpp testing that frames are loaded in the same order they were serialized; I think there might still be an off-by-one error in that code, but I've been unable to summon the energy to debug it due to the massive bloat of our savefile data (saves are multiple megabytes of useless Model Visitor data, and I've not had time to understand and fix that behavior either...)
