### ISSUE TITLE
Windows (Visual Studio) 32bit builds broken

### ISSUE THREAD

**Issue by The-EG** [pioneerspacesim/pioneer#4899]
The Visual Studio project can't be build in Win32 (x86) configuration. The build fails in FrameId.h, on the overloaded definitions of `operator const` (member function already defined or declared).

In Win32 configuration, `size_t` and `uint32_t` both evaluate to `unsigned int`.  In x64 `size_t == unsigned long long` and `uint32_t == unsigned int`

__My pioneer version (and OS):__
Windows 10 (VS 2019)
current master

**Comment by The-EG** [comment]
I'm not really familiar with what this class is doing or why that operator needs to be overloaded like that...but a solution could be to add a preprocessor directive to only declare the `uint32_t` version if it's different from `size_t` (or vice versa):

```
#if uint32_t != size_t
constexpr operator uint32_t() const { return m_id; }
#endif
constexpr operator size_t() const { return m_id; }
```

With that, Pioneer builds and runs in both Win32 and x64 (building in Win32 requires some extra unrelated fixes to linker options), but I have no idea how to test the impact of the change.

**Comment by Web-eWorks** [comment]
Aha. This operator is defined to silence GCC compiler warnings about comparisons between incompatible integers: STL-native types (`std::size_t`) and the FrameId which is a `uint32_t` internally. It'd definitely be possible (and correct) to simply:

```c++
#if sizeof(size_t) != sizeof(uint32_t)
constexpr operator size_t() const { return m_id }
#endif
```

**Comment by The-EG** [comment]
@Web-eWorks Hrm....can't use `sizeof` in preprocessor `#if`s. Which does make sense, the preprocessor has no idea about architecture or sizes. Which also means that my initial solution would probably bring the GCC warnings back.

Something like `#if (defined(_WIN32) && defined(_WIN64)) || !defined(_WIN32)` would work for Windows...but ew. 

Maybe it's time to remove the 32bit build configurations? Are they used?

**Comment by impaktor** [comment]
> Maybe it's time to remove the 32bit build configurations? Are they used?

Good question. I don't know what the status is on this in the windows world. Ping @fluffyfreak

**Comment by fluffyfreak** [comment]
I have questions about that whoile FrameId thing, like why does it exist and is it a good idea? It went in with one of the mega-commits and I just couldn't review it properly.

Anyway, do any other platforms still build in 32-bit?
Why isn't FrameID just a uint32 anyway? I doubt we're getting more than 4 billion Frames in a single star system!

**Comment by Web-eWorks** [comment]
You'll have to blame me for the FrameId struct - it's much *much* safer than just passing around a raw integer (although it is a raw `uint32_t` internally). I do take some slight umbrage, because I was very careful to split it out into its own PR and even waited a few days before merging :stuck_out_tongue: 

The reason it exists is to clean up a category of errors we were encountering directly in the wake of the frame-rearrange PR, to enforce programmer correctness when working with frame identifiers (we still have some issues with that in debug assertions).

The reason it's not building is because 32-bit Windows seems to think that a 32-bit `size_t` is appropriate, and thus the conversion operator for a 32-bit integer gets defined twice. I can think of a few ways to clean it up, the easiest of which is to simply remove the `size_t` overload (it's only there to make strict-mode compiler warnings go away) as it's no longer a signed integer internally.

I'll get that PR'd... soon. Alternatively @The-EG can do it as well - just remove the `operator size_t` and verify everything compiles and runs correctly and I'm good with merging it.

**Comment by fluffyfreak** [comment]
@Web-eWorks No offense meant, it was the big change in mikes PR that I meant and I don't even mean to insult him either ;)

My only point was it changed, was a very complex change, seemingly because of perceived "betterness" than the raw pointer, but we've now got a more complicated system that has more issues than we did with the "worse" system.

As for "_32-bit Windows seems to think that a 32-bit size_t is appropriate_", yes, and it's the same on 32-bit Linux/OSX/iOS/Android/etcetcetc.

Those type conversion operators aren't something I'm keen on seeing.
I'd prefer explicit named accessors like you already have below them as `valid` and `id`, and remove the conversion to `size_t` from the whole class so that callers know to expect a `uint32_t`
