### ISSUE TITLE
Configuring controller "View Zoom" does not expand

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4915]
### Observed behaviour
The very bottom option in configuring controller, "View Zoom" can not be expanded to be altered

### Steps to reproduce

__My pioneer version (and OS):__
Windows, Git version July 14th, 2020

**Comment by The-EG** [comment]
I can not figure out why that's happening. 
ImGUI is ignoring the click on that one in a way...but it's not completely ignoring it because the color changes on mouse down and changes back on mouse up. I can add a dummy collaspingheader at the end, and it works, so it's not like it's some issue with being last. I can rename the header, just for that one, and it still does it. I can force them all to be open by default and it is open, but won't close. This is weird!

**Comment by Web-eWorks** [comment]
It's because the localized name of the binding is being used as the ID and there are two "View Zoom"s in the list. It's fixed in the linked PR.
