### ISSUE TITLE
GUI: System View: Orbits are not drawn in system view if camera is to close

### ISSUE THREAD

**Issue by PtrMan** [pioneerspacesim/pioneer#4918]
Orbits are not drawn in system view if camera is to close.

### Observed behaviour
Orbits of planets are not drawn if camera is to close.

### Expected behaviour
correctly drawn orbits.

### Steps to reproduce
a) start new game at mars
b) focus on neptune
c) move camera back and forth, close up.

__My pioneer version (and OS):__
pioneer-20200203 linux

**Comment by nozmajner** [comment]
On one hand I'd say it is a feature, not a bug, because up close the orbit of the given body isn't that important, at least when there are lots of moons:
![orbitmap2](https://user-images.githubusercontent.com/4182678/87847475-f957e680-c8d8-11ea-9fa8-acd7a4397497.png)
But for some planets, like Neptune you mention the cutoff is quite excessive:
![orbitmap1](https://user-images.githubusercontent.com/4182678/87847502-168cb500-c8d9-11ea-880d-002f968c6028.png)

**Comment by impaktor** [comment]
![not a bug](https://image3.slideserve.com/5579598/it-s-not-a-bug-it-s-a-feature-l.jpg)

**Comment by Web-eWorks** [comment]
This is intentional behavior and is (IIRC) documented in code as such. The idea is for the body's orbital lines to avoid cluttering up child bodies and the eventual terrain view (which is a planned but totally unimplemented feature).

If you'd like to do some work, the "exclusion radius" is currently statically defined, you're welcome to add some code to SectorView.cpp that calculates the radius based upon the body and its children if you think the cutoff distance is too large.

**Comment by PtrMan** [comment]
I was actually running the old release version from the download page where the rendering of the orbits looks different. It's much better in master.
Thanks for the comment!
