### ISSUE TITLE
Bad alignment on some screens at 1152x864 (for example)

### ISSUE THREAD

**Issue by Gliese852** [pioneerspacesim/pioneer#5040]
### Observed behaviour
everything on animation:
![ezgif-4-ee13914edd7e](https://user-images.githubusercontent.com/18342621/100903546-18959000-34d7-11eb-8ed9-f908e3529440.gif)

__My pioneer version (and OS):__
60b80bccb Ubuntu

**Comment by gunchleoc** [comment]
I think we need a width parameter for `textWrapped` to fix that.

**Comment by Gliese852** [comment]
@gunchleoc maybe we can use `ui.nextItemWidth` ?

**Comment by gunchleoc** [comment]
I don't know - I just navigated to the C++ code from Lua to check whether there was a width parameter and didn't find any. So, the text wrapper doesn't seem to know how much width it really has available.

I'm happy to keep doing smaller fixes as I notice them while testing my translation, but I can't afford the time right now to learn a new code base.

**Comment by Gliese852** [comment]
@gunchleoc try to write `ui.nextItemWidth(desired_width)` immediately before `ui.textWrapped(....)`, this way you tell the next widget its width.

**Comment by Web-eWorks** [comment]
The `textWrapped` call does in fact know it's width; this is ImGui-internal information that can be queried by `ui.getColumnWidth()` or `ui.getContentRegion().x`. The problem is that something in our code or ImGui's code is calculating a different width when we're querying the width of a line of text vs. when we're actually rendering it. It's possible (and looking at that screenshot, I'd say very probable) that we're actually not giving it enough width to render the entire line of text on a single line when we're doing the initial calculation and thus we're getting the width of the first line of wrapped text back.

**Comment by gunchleoc** [comment]
Looking at the 1MW pulse canon, there also seems to be an alignment problem - maybe some extra whitespace nodes that it can't handle properly when right-aligned?
