### ISSUE TITLE
System viev: Ship vanishes when the reference system is an orbital starport

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5062]
Another detail you may correct if you feel motivated:

### Observed behaviour
The ship vanishes from the system view when the reference system is an orbital starport: (20 km around)

![Sysmap_SpacestationReference](https://user-images.githubusercontent.com/60466586/101563390-6fb0ce80-39c9-11eb-82df-cc558556dc31.png)

![Mainview_SpacestationReference](https://user-images.githubusercontent.com/60466586/101563349-658ed000-39c9-11eb-9250-8048884df0e6.png)

### Expected behaviour

A ship's position should still/(always?) be visible in the system map

__My pioneer version (and OS):__
20201206 master and Gliese852's version on SuSE Linux

**Comment by Gliese852** [comment]
Yes, this happens because the spaceport has no gravity, so the orbit of the ship is not calculated, so the ship is not shown. The ship also disappears if it stops completely in space. In both cases, there are not very trivial orbits. (or vice versa, too trivial). thought to do it after #4860 is merged, it would be desirable to also implement the display of the cargo on the system map.

**Comment by impaktor** [comment]
Might be very cluttered to have cargo in the map, but we'll see, I guess.

**Comment by nozmajner** [comment]
Maybe limit cargo visibility to a certain distance in the map?

**Comment by Gliese852** [comment]
@nozmajner definitely, information can get into the system map from different sources. the location of the planets is clearly taken from the database. the position of ships - especially distant ones - from the transmitters on these ships. but non-transmitting objects, apparently, should be determined by some kind of locator, and the range should depend on the size of the object.
But in a cargo scoop mission, you buy information about the location of this cargo, apparently its ephemeris, therefore, I think it should be visible in the system map at any distance, but, probably, a limited time, since the accuracy of the ephemeris is constantly decreasing, and after some time they become meaningless.

**Comment by nozmajner** [comment]
True, known cargo should be visible from any distance on the map. I was assuming random cargo container. Known ones won't be that numerous to clutter up the map much I'd guess.

**Comment by Web-eWorks** [comment]
Regarding the cargo mission I'd expect an encrypted beacon of some sort instead of orbital information, but that's a matter for another time.
