### ISSUE TITLE
The moment of emergence of the hyperspace arrival cloud is not defined.

### ISSUE THREAD

**Issue by Gliese852** [pioneerspacesim/pioneer#5067]
This is a game lore issue.
How long before the arrival of the ship does the cloud appear? At the moment there is no certainty with this question, some modules create NPC ships in the arrival clouds, and the time of their stay there is chosen randomly.

There is a point of view that the arrival cloud appears simultaneously with the departure cloud. What I think:
- it seems reasonable, the ship opens a "corridor" between two points in space
- the arrival cloud hangs at the point of arrival for many days, this explains how the police or mafia are already waiting at the exit. 
- instant transmission of information becomes possible. (pros for me)
- sudden arrival in the system becomes impossible: for several days, while the cloud hangs, you can overlay it with thermonuclear mines, for example.
- unclear how this cloud is moving all these days? Does it hang motionless relative to the star, or does it orbit? why?
- it is almost impossible to pirate in civilized systems, because the police can be waiting for you right at the exit
...

There is also a position that the arrival cloud appears at the time of arrival.
- it is clear how it should move, apparently, it is just a clot of matter, let it just fly in orbit
- it is unclear how the police and the mafia find you immediately upon exiting hyperspace (but I think it's worth removing it altogether, the police should contact you and scan from afar, and the mafia should intercept along the way.)
- it is somewhat easier to generate ships, if you do not need to calculate how long before arrival to create this cloud
- also, mechanics of sudden, hidden penetration into the system become possible
- flourishing of piracy, slave trade and everything else - bad guys get much harder to catch
...

Maybe some middle decision will be correct. Maybe I'm wrong I deduce consequences.

I created this issue to discuss and define exactly how it should work as it kind of blocks #4984. Also, this question strongly influences what the game universe is like, imho.

**Comment by nozmajner** [comment]
How about the middle way you mention? It doesn't pop up immediately, but after the ship has spent some time in Hyperspace. Like the corridor "moves" faster than what it brings. Or maybe it does emerge when you jump, but it's so faint, it can't be detected until you are closer to the exit in the corridor. (Which could also explain, how the cloud analyzer deduces the time of arrival if it does)
My reasoning is that if you can enter a system without notice, then surprise attacks would be very devastating: Jump some heavy ships loaded to brim with deltaV and concrete, and accelerate until you smash into the enemy planet. Or instead of concrete, a good bunch of tungsten poles, aka rods from the gods if you want to be more surgical. Our travel times from the point of arrival are sufficiently short for a good chance that defending forces might not be able to shoot down all the intruders in time I think.
I just tried it and I was at 5880 Km/s accelerating towards Earth with a Pumpkinseed. I won't calculate how many nuclear bombs that would equate to, because we fudge with the energies of engines anyway, and it would be a fittingly absurd number I suspect. And even if you'd blow the attackers to smithereens, if you aren't fast enough, then you just have a lot of smaller debris hurtling towards your planet at the same speed, instead of one large.

But on the other hand, should the Hyperspace Cloud Analyzer be able to give you the exact time of arrival? Police and pirates would sure love that, and then arrival patrols could also be done in a planned manner, instead of patrols all the time because they fear that an enemy would launch

**Comment by Gliese852** [comment]
@nozmajner 

> Our travel times from the point of arrival are sufficiently short

Now I tried to ram a NewHope on a Sinnonatrix, to fly to the planet at permanent forward acceleration from the exit point, it took 14 hours, and this is before the rebalance-03. in my opinion, this is a lot of time to react somehow, from the side of the defense. Laser systems can be installed in the planet's orbit, which will burn the ram long before it picks up sufficient speed ( if we say that we have *a lot* of energy), I want to say that the defending side still has an advantage, Even when the enemy suddenly appears.
It is also the motivation to place important objects further from the star, and to develop interplanetary transportation.

But if the exit cloud hangs in space long enough, these ships are completely helpless in front of those who meet. Isn't that too much of an advantage for defense? Doesn't this negate any possibility of taking over the system?

> should the Hyperspace Cloud Analyzer be able to give you the exact time of arrival?

I think no, and it doesn't matter, I don't know what this information gives you, you will wait until the victim ship leaves hyperspace anyway.

> Police and pirates would sure love that

I think the pirates will not like this very much, since it will be very easy for the police to catch them.

> arrival patrols could also be done in a planned manner, instead of patrols all the time because they fear that an enemy would launch

And why do you need patrols at all, a dozen automatic satellites in orbit of a star are enough, I think.

> I won't calculate how many nuclear bombs that would equate to

4.67e17 J for 27t Pumpkinseed at 5880 km/s ~ 319 modern nuclear bombs (I take 350 kt TNT or 1.46e15 J) this is a lot.

> How about the middle way you mention? <...> Or maybe it does emerge when you jump, but it's so faint, it can't be detected until you are closer to the exit in the corridor.

I like the idea that the brightness of this cloud is gradually increasing, and the probability of cloud detection depends on the parameters of the locators, there may be some special technologies that make these clouds less bright, for example. Need to think it over.

**Comment by fluffyfreak** [comment]
First of all I appreciate the effort for lore building however this is _why_ we have a [dev forum](https://pioneerspacesim.net/forum/) for discussing ideas.

**Comment by Web-eWorks** [comment]
Closing this in favor of the forum! Please feel free to transcribe your posts over there.
