### ISSUE TITLE
Fatal: Failed to set video mode: Could not create GL context: GLXBadFBConfig

### ISSUE THREAD

**Issue by Pythonic456** [pioneerspacesim/pioneer#5079]
Compiled pioneer, then did ./pioneer. Output:
```pi@raspberrypi44g:~/pioneer/pioneer $ ./pioneer 
[  0%] Built target profiler
[  1%] Built target lz4
[  2%] Built target fmt
[  4%] Built target pioneer-core
[ 71%] Built target pioneer-lib
[ 84%] Built target pioneer-lua
[ 84%] Built target glew
[ 86%] Built target imgui
[ 86%] Built target jenkins
[ 86%] Built target picodds
[ 95%] Built target lua
[ 96%] Built target pioneer
[ 97%] Built target modelcompiler
[100%] Built target savegamedump
Init!
ver 20201216 (334990c70) on: Linux

System Name: Linux
Host Name: raspberrypi44g
Release(Kernel) Version: 5.4.79-v7l+
Kernel Build Timestamp: #1373 SMP Mon Nov 23 13:27:40 GMT 2020
Machine Arch: armv7l
Domain Name: (none)

--------------------
SDL Version (build) 2.0.9
SDL Version (dynamic) 2.0.9
SDL Versions match
SDL_image Version (build): 2.0.4
SDL_image Version (dynamic): 2.0.4
SDL_image Versions match
Assimp Version: 4.1.0
FreeType Version: 2.9.1
GLEW dynamic version: 2.0.0
--------------------

Fatal: Failed to set video mode: Could not create GL context: GLXBadFBConfig
pi@raspberrypi44g:~/pioneer/pioneer $ 
```
`Fatal: Failed to set video mode: Could not create GL context: GLXBadFBConfig` not sure what to do. Help will be appreciated. 

My pioneer version (and OS):
Latest git version, as of post
Raspberry Pi OS 32-bit

**Comment by impaktor** [comment]
Pioneer doesn't run on Raspberry pi

**Comment by impaktor** [comment]
Here's our raspberry pi thread, for more info / discussion:
https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=242

Closing this, as we don't support arm. Thanks for reporting, though.

**Comment by Pythonic456** [comment]
No, I want to do this with box86.

**Comment by The-EG** [comment]
This is actually an issue with OpenGL rather than processor architecture. Outside of the OpenGL requirements, I *think* Pioneer would run on arm.

As mentioned in the thread Impaktor linked:
> Performance is certainly an issue, but the main problem is finding out what verison of desktop OpenGL it supports.
OpenGL ES (3.0) is not the same thing, that's been pretty much thr only thing stopping us supporting the Pi.

Currently Pioneer requires and only supports full OpenGL 3.1 (maybe 3.2 these days?). As far as I'm aware a Raspberry Pi only has OpenGL 2 or OpenGL ES 3, and recently Vulkan. 

Unfortunately, I don't believe box86 would help that since the underlying hardware/drivers still don't support the correct OpenGL specifications and software rendering probably wouldn't end up being useable.

**Comment by laarmen** [comment]
Isn't there an implementation of OpenGL on Vulkan ?
https://www.collabora.com/news-and-blog/blog/2018/10/31/introducing-zink-opengl-implementation-vulkan/

**Comment by The-EG** [comment]
> Isn't there an implementation of OpenGL on Vulkan ? https://www.collabora.com/news-and-blog/blog/2018/10/31/introducing-zink-opengl-implementation-vulkan/

Well that's neat. It sounds like that could work with the latest update (https://www.collabora.com/news-and-blog/blog/2020/11/06/bringing-near-native-performance-to-zink/). From that post, it also sounds like 3.x support hasn't hit release yet, so it'd probably require building mesa from that source branch...

That said, this still isn't an issue with Pioneer itself and this isn't the proper place to getting a solution like that setup. I'll post a link to that in the Raspberry Pi dev thread though, because I suspect it will be of interest.
