### ISSUE TITLE
A landing pad the station granted permission to dock to was occupied

### ISSUE THREAD

**Issue by maxcrystal** [pioneerspacesim/pioneer#5086]
When I arrived to my destination the landing pad was already occupied. When I docked nearby the NPC's ship exploded (?), I guess. And some strange graphical glitch occurred.

[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/5737252/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/5737253/output.txt)

Just before docking to pad 2:
![Pioneer Screenshot 2020 12 24 - 00 25 50 95](https://user-images.githubusercontent.com/13114986/103039710-9999f180-4582-11eb-8bcb-002a3267bcd4.png)

Just after docked to pad 2:
![Pioneer Screenshot 2020 12 24 - 00 33 16 14](https://user-images.githubusercontent.com/13114986/103039712-9b63b500-4582-11eb-9a61-a30924b4e859.png)

Undocked pad 2 and docked to pad 1:
![Pioneer Screenshot 2020 12 24 - 00 46 22 25](https://user-images.githubusercontent.com/13114986/103039713-9b63b500-4582-11eb-9609-2f634ed5607e.png)

__My pioneer version (and OS):__
20201222-rc1 (Windows 10)

**Comment by nozmajner** [comment]
Hmm, it seems like the ship hyperjumped. Probably it was unable to climb, although that planet shouldn't be high-G to cause that I think.

**Comment by Web-eWorks** [comment]
CC @Gliese852 - seems this might be related to the TradeShips module.

**Comment by Gliese852** [comment]
@Web-eWorks I think it's more of an autopilot problem.
I think I'm starting to understand what problem the @impaktor  was referring to when talking about the queues at the station. Autopilot asks for a pad at the very beginning of the path. The duration of the flight is usually tens of hours. But the station does not guarantee that the pad will be free the entire time. While we have few ships, this problem is not very noticeable, but if we manage to establish the flow of ships at least 1 ship per hour, while the player reaches the station, dozens of ships will land there, and most likely the place will already be taken.
the question arises - how should this work ? Apparently, a landing booking system is needed.

**Comment by maxcrystal** [comment]
The part with the ship occupying the pod may be reproduced: load the save file, take some missions to OPLI Awakening. When you arrive there you will be asked to dock to pad 2 - the only occupied pod (also I had a crash once when tried to save the game as soon as I arrived there with objects serialization error, but I can't reproduce it).

[Pioneer-2.zip](https://github.com/pioneerspacesim/pioneer/files/5738535/Pioneer-2.zip)
