### ISSUE TITLE
Game crashes when saved

### ISSUE THREAD

**Issue by maxcrystal** [pioneerspacesim/pioneer#5089]
### Observed behaviour
![12_25_20 @1_50_17](https://user-images.githubusercontent.com/13114986/103107926-0e892c00-4654-11eb-9464-d71f59718944.PNG)

### Steps to reproduce
It is the second time it crashes with this error, but I can't reproduce it.

__My pioneer version (and OS):__ 20201222-rc1 (Windows 10)

**Comment by impaktor** [comment]
Come to think of it, I never tested save/load with that module, so there might be some cruft left over there triggering this crash.

Probably hard to reproduce because it doesn't spawn that often on space stations.

(For future reference, to experiment to reproduce: add an `and true` to the two if statements in `onCreateBB()` in data/modules/SoldOut/SoldOut.lua, that will create one BBS advert for each commodity) 

but I assume you've at least done a save-load cycle to trigger the bug. I'll look into it in the coming days, if when I have time, if no one else beats me to it (please do).

**Comment by The-EG** [comment]
> (For future reference, to experiment to reproduce: add an `and true` to the two if statements in `onCreateBB()` in data/modules/SoldOut/SoldOut.lua, that will create one BBS advert for each commodity)

It should probably be `or true` so that is always evaluates true...I did that and got a bunch of the 'sold out' ads on a new game. Saved, ended the game, and then loaded again with no issues other than #5090 popping up in the loaded save.

@maxcrystal Was this the first time you tried saving? If not, do you have a save that was working before and stopped working? Where were you at? (system/station)

**Comment by maxcrystal** [comment]
@The-EG It was the second time. The first time it happened was when I docked to a station and tried to save. The second time was when I hyperjumped to another system and tried to save right after that. I tried to reproduce this error, but next time everything was OK.

The last save that crashed after I jumped to another system: 
[Pioneer-3.zip](https://github.com/pioneerspacesim/pioneer/files/5741352/Pioneer-3.zip)

**Comment by impaktor** [comment]
@The-EG ha, yes, I realized my error (of `and` instead of `or`) shortly after I wrote it (tired, in bed), but had already turned my lights out for the day by then. Thanks for catching the ball.

**Comment by impaktor** [comment]
@maxcrystal can you recall if all of your other crashes also mentioned "soldout" like in your screenshot?

I'm thinking this might be related to recent changes introduced in #5075, but then I'd expect this bug for many other kind of adverts, like Taxi, Deliver package, cargo, and such.

**Comment by maxcrystal** [comment]
@impaktor I can't unfortunately. But the last part was the same.

**Comment by Web-eWorks** [comment]
@impaktor I did actually see this bug pop up, though it was tied to creating advertisements in the `onStartGame` event causing stations to reference C++ station objects from the *previous* game. To point you in a likely direction, my guess is there are some advertisements not being cleaned up after the previous game that are then being serialized...

**Comment by maxcrystal** [comment]
@impaktor I've got the third crash with exactly the same error mentioning "soldout".

**Comment by impaktor** [comment]
@maxcrystal thanks for letting me know.

@Web-eWorks Yeah, I had had the feeling this is related to something with stations no longer existing until player visits them. 

I think adding this at the end of data/modules/soldout.lua might do the trick (I'm heading to bed now, so will sleep on this):
```lua
local onGameEnd = function ()
	loaded_data = nil
end

Event.Register("onGameEnd", onGameEnd)
```

I'll do a pull request tomorrow. @maxcrystal you could add the above manually, if interested.

**Comment by impaktor** [comment]
Actually, I change my mind: I don't think I understand this anymore. the `load_data` is set to `nil` in onGameStart, so it should  never be able to survive into the next session, thus the code above should not be needed.

**Comment by impaktor** [comment]
OK, next, I thought `ads` wasn't reset, but as far as I can tell, it's reset just as in the other adverts, meaning, it has an `onDelete` trigger, that runs when player jumps out of the system, and thus clear out stale references to non-existing stations.

However, I see a small bug: if player sells all the stock the "sold out advert" wants to buy, the advert was removed from the BBS, but not its reference in the `ads` table (I'll fix this later). I'd expect that mistake/bug would simply make the advert re-appear on the BBS next load, but wouldn't cause a crash, I think.

Update: OK, I see now that the `onDelete` function is referenced before it's defined, I think/hope that's it.

**Comment by impaktor** [comment]
@maxcrystal fix is merged, please let us know if this didn't fix the error.
