### ISSUE TITLE
Could not find model: ground_station

### ISSUE THREAD

**Issue by ZikZakFR** [pioneerspacesim/pioneer#5117]
### Observed behaviour
Compiling from GIT source, everything completes without any error.
make -C build
make -C build/ build-data
./pionner

Loading [69%]: SpaceStation::Init started
Could not find model: ground_station
couldn't initialize station type 'stations/ground_station.json' because the corresponding model ('ground_station') could not be found.
Fatal: Error while loading Space Station data (check stdout/output.txt).

### Expected behaviour
./pionner launches.

### Steps to reproduce
make -C build
make -C build/ build-data
./pionner

__My pioneer version (and OS):__
Archlinux
Kernel 5.10.5
GNU Make 4.3
Latest pioneer git

**Comment by impaktor** [comment]
Do you have some old mod hanging around in ~/.pioneer/ ?

**Comment by The-EG** [comment]
Another thing to try: start with a clean checkout and skip the `cmake -C build/ build-data` step.

**Comment by ZikZakFR** [comment]
Strangely, after a make install I can run teh game just fine from outside the git folder.
Then when I went back into the git folder and ran ./pionneer it worked too.

I guess impaktor was right and the make install fixed something too.

**Comment by Web-eWorks** [comment]
@ZikZakFR this is happening because the game prefers to load data from your `/usr/share/pioneer` directory first before the `./data` folder in the local directory. For best results, please temporarily uninstall the system-wide version of Pioneer when compiling from source.

I'll look into adjusting the logic that looks for the data directory, but at the moment that's a caveat that you'll have to keep in mind.
