### ISSUE TITLE
Pressing V crashes game

### ISSUE THREAD

**Issue by ProgramRAM** [pioneerspacesim/pioneer#5136]
### Observed behavior
Pressing V triggers game to lock up for a second and then it crashes

### Expected behavior
Pressing V allows toggle speed control mode without crashing

### Steps to reproduce
Load up the game as normal no settings changed (Beyond graphical) and press V while flying (Also happens when just sitting in a station)

__20210203 142693b __Windows 10 Pro 10.0.19042 Build 19042

**Comment by The-EG** [comment]
Unfortunately I can't get this to happen on my system.

Can you attach output.txt (found in My Documents\Pioneer) to this issue?

**Comment by ProgramRAM** [comment]
[output.txt](https://github.com/pioneerspacesim/pioneer/files/5925544/output.txt)
There we go, if theres anything else I can provide let me know happy to help

**Comment by The-EG** [comment]
Sorry, I should have specified, after triggering the crash. It overwrites that file every time you run it.

**Comment by ProgramRAM** [comment]
Yeah that might be a slight problem I can't get the issue to happen again, perhaps I had a program running and a conflict happened? Odd because I don't recall changing anything since it happened I will definitely be sure to nab the output file if it does happen again

**Comment by Sthrenor** [comment]
It happens to me too... I will be uploading output.txt. when happens to me again.

**Comment by impaktor** [comment]
If any of you who can produce it, can run pioneer through gdb (if on Linux), and do a backtrace, that would be helpful

**Comment by Sthrenor** [comment]
I'm on windows. Got the output.txt
Game crashed just after hitting V. 

[output.txt](https://github.com/pioneerspacesim/pioneer/files/5939459/output.txt)

**Comment by The-EG** [comment]
> I'm on windows. Got the output.txt
> Game crashed just after hitting V.
> 
> [output.txt](https://github.com/pioneerspacesim/pioneer/files/5939459/output.txt)

That looks like it didn't flush the output...boo..

Also:

> [16:55:42]    Info: ver unknown on: Windows

Are you running copy you compiled in Visual Studio? If so, if you can get this to happen regularly, you can give us a better look by running it in debug mode.

(`Info: ver ...` should only say unknown when built through the VS solution btw)

**Comment by Sthrenor** [comment]
Visual Studio compiled. I compiled in debug mode and here is the output.txt.
[output.txt](https://github.com/pioneerspacesim/pioneer/files/5939692/output.txt)

**Comment by Sthrenor** [comment]
How do you run it in debug mode?
Thx

**Comment by The-EG** [comment]
> How do you run it in debug mode?
> Thx

After building it, press F5 or go to Debug->Start Debugging. 

*Warning:* it will run *slowly*, starting a new game or loading a new one in particular. That's normal.

Instead of a full out crash, you'll get a freeze and it should automatically switch back to Visual Studio. If it freezes and doesn't switch back, do that manually.

At that point, Visual Studio should have opened a couple new panes/sub windows at the bottom. One of these is 'Call Stack.' Right click in it, select 'Select All.' Then right click in there again and select 'Copy with source paths.'

Then you can paste that into here. 

After that you can Debug->Stop to shut down Pioneer again.

**Comment by impaktor** [comment]
Added:
https://pioneerwiki.com/wiki/FAQ#Debug_backtrace

**Comment by Sthrenor** [comment]
![image](https://user-images.githubusercontent.com/39418775/107227595-e004bc00-6a1b-11eb-85e6-14e9f674602e.png)

When I start the debug the game loads and stop with this message.

Thx. Tell me what to do.

**Comment by The-EG** [comment]
Ah, no matter how many times I fix that it seems to pop up now and again. 

In the Solution Explorer pane, right click on the 'pioneer' project select Properties. Set the Configuration dropdown to 'All Configurations' and Platform dropdown to 'All Platforms.'

Select Debugging from the tree and set 'Working Directory' to `$(ProjectDir)\..\..\`

![image](https://user-images.githubusercontent.com/7342077/107236604-dbc4a880-69f3-11eb-85e6-17793dcf515d.png)

I'll see if I can fix and push it up again, but I suspect this may be getting saved per user or something since it keeps changing back.

**Comment by Sthrenor** [comment]
Got it!
Well, I can copy paste the stack coz the game freezes the SO and I can't change app. Fortunately I can snapshot what happenede.
![image](https://user-images.githubusercontent.com/39418775/107287000-a22a8680-6a61-11eb-90d3-2310fd3f46e1.png)

While the game got this state:
![image](https://user-images.githubusercontent.com/39418775/107287052-b1a9cf80-6a61-11eb-8ded-0dd2b35a95f0.png)

I can't get task manager to front so I will have to reboot.

Hope it helps. Thx for helping me...

**Comment by The-EG** [comment]
Thanks! This is the bit we need:
![image](https://user-images.githubusercontent.com/7342077/107293958-895aaa80-6a3a-11eb-9c94-4122f8b0736e.png)

**Comment by Web-eWorks** [comment]
@The-EG ah, this is because signals connected to actions are accidentally persisted past the destruction of the object that attached them. Line 107+ of PlayerShipController.cpp should be amended to:
```diff
PlayerShipController::~PlayerShipController()
{
+	m_setSpeedMode.disconnect();
+	m_fireMissileKey.disconnect();
+	m_connRotationDampingToggleKey.disconnect();

	Pi::input->RemoveInputFrame(&InputBindings);
	m_connRotationDampingToggleKey.disconnect();
	m_fireMissileKey.disconnect();
}
```

My working tree is a bit cluttered right now so I can't commit that directly, but it should solve the issue.

**Comment by impaktor** [comment]
@ProgramRAM could you please verify that the fix works, and the bug no longer exists, by installing this nightly build: https://github.com/pioneerspacesim/pioneer/actions/runs/581095702
