### ISSUE TITLE
Joystick axes finetuning no more possible in v20210203

### ISSUE THREAD

**Issue by gerrygk** [pioneerspacesim/pioneer#5146]
Hi all,

in v20200203 it was possible to set the sensitivity and deadzone of all joystick axes, but not anymore in the actual official version.

I'm using PSS @ Linux Mint 20 x86-64.

Greetings

**Comment by Web-eWorks** [comment]
The mechanism for defining and using joystick axes was entirely rewritten during the last release cycle, but I was unable to write a replacement GUI in time for the release date. It will be coming, rest assured! Until then, you can set sensitivity curve and deadzone values in your `config.ini` file following this guide: https://pioneerwiki.com/wiki/FAQ#My_joystick_is_.22drifting.22

**Comment by gerrygk** [comment]
Ah great! Looking forward.

**Comment by Keeper1st** [comment]
What it reaaaaally needs is a way to make the game translate the ranges of two axes into plus and minus of another -- or simply allow separate axes for forward and reverse thrust. While there's no practical reason a pilot would use both at the same time, in terms of game controllers, it's necessary in many cases.

While sticks used for rotational or translational thrusters naturally return to center and work fine, a joystick throttle wheel is designed to be at one end of its input when "at rest". While it is possible for a user to try to find the "zero" point on a throttle wheel, with a gamepad it's another story.

Having the two control sticks for rotation and translation control on a gamepad is nice, but it is impractical to set a trigger axis to forward or reverse thrust, because the game expects one trigger to do both functions and for the user to hold the trigger down halfway to get to a neutral position. If the game could read the values of two axes (left trigger and right trigger) and convert the delta between the two into a single out for the forward/reverse thrust (so the two would cancel each other out if both held down though in typical use the player would not do so), then using a gamepad would be an excellent control method as only yaw would be forced into buttons only.

That assumes the game is not equipped to handle having forward and reverse thrusters firing at the same time (the model viewer suggests this, at least). If it can, then just the ability to set those to separate axes and for the game to use the full range of motion for each instead of assuming each axis has a center point would do the trick.

Maybe this should be posted as a separate issue, but rather than clutter the issues page, it's here as a related "oh by the way..."
