### ISSUE TITLE
Station Menus Ocassionally Unusable

### ISSUE THREAD

**Issue by RL-10** [pioneerspacesim/pioneer#5149]
### Observed behaviour
Occasionally, some of the station menus will disappear and not be usable. The following workarounds were attempted without success.
1. Leave and redock at the same station.
2. Restart the game.
3. Go to another station within the same system.
4. Load an earlier game save where the player is docked in another system. 

There seem to be two ways around this bug. One is to jump to different systems until the station menus appear again. However, this can be difficult because the Lobby and Commodity Market menus are not usable, and therefore fuel cannot be purchased normally. Another is to go to a different station within the system and keep reloading the save until the menus work again. 

This screenshot demonstrates what the station menus look like in their broken state. 
![Station Menu Bug](https://user-images.githubusercontent.com/79066000/109876742-bc5a1d80-7c37-11eb-9fa2-0e2a0dda7622.png)

### Expected behaviour
Station menus should always be functional. 

### Steps to reproduce
I'm not sure how to reproduce this given that it seems to happen randomly. 

__My pioneer version (and OS):__
ver 20210203 (142693b), Ubuntu 20.04 LTS

**Comment by Web-eWorks** [comment]
Without a log file (`~/.pioneer/output.txt`) we cannot really diagnose the problem, especially without consistent reproduction steps. However, if you can zip the log file and the save file together and attach it to this issue we can definitely look into it - my guess is there's an error in the menu code that made it into the live build that's occasionally being triggered on loading the save.

**Comment by RL-10** [comment]
@Web-eWorks I'll do that the next time the bug occurs.

**Comment by RL-10** [comment]
I encountered the problem again so here's my output.txt. This time, it was the Commodity Market and Equipment Market menus that weren't working. It looks like the relevant lines start at line 257. 
[output.txt](https://github.com/pioneerspacesim/pioneer/files/6093340/output.txt)

**Comment by Web-eWorks** [comment]
> I encountered the problem again so here's my output.txt. This time, it was the Commodity Market and Equipment Market menus that weren't working. It looks like the relevant lines start at line 257.
> [output.txt](https://github.com/pioneerspacesim/pioneer/files/6093340/output.txt)

Can definitely confirm there's an error there that's being caught and *not* crashing your game - good to see that's working in the wild. Eventually when that happens we'll display an error message in that space, but for right now the error is only written to the log.

I would really appreciate it if you could upload your savefile as well (`~/.pioneer/savefiles/<savefilename>`), as that will help diagnose the root cause of this issue. Additionally, any information you have about the precise conditions in which you first get this error (e.g. jumped to a different system than the starting system, saved and loaded the game, etc...) would help to track down the issue.

**Comment by Web-eWorks** [comment]
To anyone who might be looking into fixing this issue - it's another case in which a ship docks at a station and SpaceStation's `equipmentStock` cache isn't initialized for that station. My best guess (take it with a grain of salt) is that something's creating an advert for that station *before* the player docks, and as a result the logic that should be initializing the station's data store when the player docks thinks it's already initialized. There are a few ways around this behavior - probably the best one is to introduce a separate cache for visited (and initialized) stations that isn't tied to the advertisement logic, although that's fixing the symptoms instead of the underlying problem.

**Comment by RL-10** [comment]
@Web-eWorks 

Here's the savefile that this bug occurred on. I had docked at this station then quit. I then loaded the exit autosave when the bug occurred. I'll admit that I did modify the Lunar Shuttle to accept a hyperdrive, but I experienced this bug before I did that. 
[_exit.zip](https://github.com/pioneerspacesim/pioneer/files/6094023/_exit.zip)

**Comment by impaktor** [comment]
@RL-10 your zip is corrupted. Perhaps it didn't finish uploading?

**Comment by RL-10** [comment]
@impaktor It's not corrupted. I just added ".zip" to the end of the save file so it would upload to Github. You should be able to just remove the .zip extension.

**Comment by tropicalpioneer** [comment]
If it helps, I am experiencing this as well from time to time, and I have not understood particular steps to reproduce it. Do you need any file from me too?

**Comment by Web-eWorks** [comment]
> If it helps, I am experiencing this as well from time to time, and I have not noticed particular steps to reproduce it.
> Do you need any file from me too?

Not at this time, but thank you for offering! At the moment fixing this issue is a matter of being able to devote the time needed to track down the root cause, and that's something I just don't have right now.

**Comment by tropicalpioneer** [comment]
The Bulletin Board sometimes turns suddenly empty, and it is not a matter of speeding up time to load new missions. 
If I reload the savedgame, the Bulletin Board is still empty.
If I reload Pioneer, then load the saved game, the Bulletin Board is not empty.

version 20210513 (0c84df0)
