### ISSUE TITLE
Game crashes on arriving on system with News Event (no crop).

### ISSUE THREAD

**Issue by jimishol** [pioneerspacesim/pioneer#5173]
On touching down on land, by autopilot, game crashed.
Game was compiled on opensuse tubleweed.

https://paste.opensuse.org/54713712 for opengl.txt
https://paste.opensuse.org/9003116 for output.txt

I do not know version but Changelog.txt starts with April 2021

Second try same crash. I read on news that Arethve computers failed. Both time i bought a computer and entered Arethve system. There is only Kelly's post if i can recall right.

**Comment by impaktor** [comment]
Looks like it's on me, if it's News Event
```
[15:02:00] Verbose: XO-5473 enters frameStone's Folly
[15:02:57]   Fatal: [string "[T] @libs/SpaceStation.lua"]:144: attempt to index field '?' (a nil value)
stack traceback:
        [string "[T] @libs/SpaceStation.lua"]:144: in function 'GetEquipmentStock'
        [string "[T] @modules/NewsEventCommodity/NewsEventComm..."]:356: in function 'cb'
        [string "[T] @libs/Event.lua"]:34: in function '?'
        [string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>
```

Not sure I understand how the first line could work but then fail on the second:
```lua
L355			local price = station:GetEquipmentPrice(n.cargo)
L356			local stock = station:GetEquipmentStock(n.cargo)
```

**Comment by impaktor** [comment]
OK, I've reproduced the crash from your save. I notice there are two News Events simultaneously. Maybe that's a case I've never tested. I don't have time to look at it today though.
```lua
WARNING: planetary mass has overflowed! (child of Phiessti A)
Fatal: [string "[T] @libs/SpaceStation.lua"]:144: attempt to index field '?' (a nil value)
stack traceback:
	[string "[T] @libs/SpaceStation.lua"]:144: in function 'GetEquipmentStock'
	[string "[T] @modules/NewsEventCommodity/NewsEventComm..."]:356: in function 'cb'
	[string "[T] @libs/Event.lua"]:34: in function '?'
	[string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>Fatal: Frame instance deletion outside 'DeleteFrame' [0]
terminate called after throwing an instance of 'fmt::v6::system_error'
  what():  cannot write to file: Bad file descriptor
[1]    39734 abort (core dumped)  ./build/pioneer
```

**Comment by impaktor** [comment]
OK, interestingly, there's a function, `updateEquipmentStock()` in libs/SpaceStation.lua, that supposed to populate a station's `equipmentStock` table, which holds number of each commodity, if the table hasn't been generated yet. It's called by `createStationMarket()` when player docks, but only if `SpaceStation.adverts`(!) table hasn't already been spawned. The two tables are (sort of) unrelated so checking one table if the other should be spawned doesn't make much sense.

I don't think this bug would be triggered back when we spawned all stations when entering a system, since the update function runs once per in-game hour, which would then have populated the `equipmentStock` table. But some time ago we made stations only spawn their data objects (ships for sale, commodity, BBS adverts) when player docked with them, so now, the News Event module is trying to zero out the "sold out" commodity, from a table that doesn't yet exist.

**Comment by Web-eWorks** [comment]
> f the table hasn't been generated yet. It's called by createStationMarket() when player docks, but only if SpaceStation.adverts(!) table hasn't already been spawned. The two tables are (sort of) unrelated so checking one table if the other should be spawned doesn't make much sense.

Hey, you found it! If you check the comments on #5149 I've roughly outlined why that's happening; the check for adverts was a time-limited hack that worked *well enough* to get our savefile size down, but clearly it needs more thought - this is where I'd recommend a different table that stores information about whether a station has been generated, and if it hasn't at the point that you're trying to add an advert or check equipment stock, then completely generate it at that time. The only issue that might occur is that current code that adds advertisements (as I remember) also handles creating the advert table for the station, so that logic will likely need to be moved into a separate function.

**Comment by jimishol** [comment]
I am afraid the bug resurrected.

https://susepaste.org/33237998
Load the above file save
Read NEWS about Gliese 644
Full fuel and buy 1t for hyperdrive
Buy 2t of grain, Request launch and jump to Gliese 644 system.
Land to any station. Upon docking the output.txt must be similar to the following
https://susepaste.org/24168872

From the above save file, game crashed 3 times in a row, so i assume it crashes always.

**Comment by impaktor** [comment]
@jimishol please open as new issue, as News event has been edited since the original report. Also, your link to save file(?) is 404.
