### ISSUE TITLE
Repeated Strings - Taxi Module

### ISSUE THREAD

**Issue by RacerBG** [pioneerspacesim/pioneer#5194]
### Observed behaviour
Some strings (I had not made a detailed observation yet) are repeated multiple times in the "Taxi" module of the game.

### Expected behaviour
These strings should be removed.

For example (probably more strings are affected as I mentioned already):

`Where are we? I've waited enough - take me to the nearest station NOW!`

`Thank you for the fast ride. You have been paid in full.`

`Thank you for the nice trip. You have been paid in full.`

`Hi, I'm {name} and I need passage for a small group to {system} ({sectorx}, {sectory}, {sectorz}) system, a distance of {dist} ly. I will pay {cash}.`

`My name is {name}. I need fast passage to {system} ({sectorx}, {sectory}, {sectorz}) system, a distance of {dist} ly. Will pay {cash}.`

`Unacceptable! You took forever. We are not willing to pay you.`

`Unacceptable! You took forever. I'm not willing to pay you.`

### Steps to reproduce
1. Open the "Taxi" module in Transifex and inspect the strings.

Regards,
Georgi

**Comment by impaktor** [comment]
Indeed, many of those strings are repeated. 
Once translated one, will not the other identical auto-complete in transifex?

The reason for these repeated strings is because each mission flavor specifies a full set of success/failure/adtext, etc. an alternative way to re-structure it so each flavor has their "unique" strings, and can the pull from a pool of "mission successful" strings, and such, so it's not a 1:1 correspondence.

It's low hanging fruit / easy to fix.

**Comment by RacerBG** [comment]
> Indeed, many of those strings are repeated.
> Once translated one, will not the other identical auto-complete in transifex?
> 
> The reason for these repeated strings is because each mission flavor specifies a full set of success/failure/adtext, etc. an alternative way to re-structure it so each flavor has their "unique" strings, and can the pull from a pool of "mission successful" strings, and such, so it's not a 1:1 correspondence.
> 
> It's low hanging fruit / easy to fix.

Yes, they are automatically translated, it's not a big deal anyway. I noticed that in the other modules a few strings are repeated too. If you are willing to remove them I can try to "hunt down" the other ones as well but it will take time.

**Comment by RacerBG** [comment]
@impaktor On second thought, I could make a PR which will make the responses different. What is your opinion on the subject?

**Comment by impaktor** [comment]
It's not as simple as just removing the strings and the "problem" is fixed, as the sting variables need to be renamed, and then the code updated. I don't have any motivation to do that work, since it's not a bug to begin with. Maybe someone else looking to get into pioneer's source might. 

I'm half thinking we can close this issue.

**Comment by RacerBG** [comment]
> It's not as simple as just removing the strings and the "problem" is fixed, as the sting variables need to be renamed, and then the code updated. I don't have any motivation to do that work, since it's not a bug to begin with. Maybe someone else looking to get into pioneer's source might.
> 
> I'm half thinking we can close this issue.
> 
> > On second thought, I could make a PR which could make the responses different. What is your opinion on the subject?
> 
> That would add more work to the translators, with little "reward", I don't think it would improve player's experience much. I'd just let it be.

I'm fine with closing this issue.
