### ISSUE TITLE
Floating point exception while cruising to destination

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5200]
### Observed behaviour
While travelling to destination, the game crashes with output:

```
Game::LoadGame('bluenose mission')
savefile version: 87
Creating new galaxy generator 'legacy' version 1
Clearing and re-using previous Galaxy object
StarSystemCache: misses: 0, slave hits: 0, master hits: 0
SectorCache: misses: 101, slave hits: 0, master hits: 1
Stars picked from galaxy: 183416
Final stars number: 500000
Hosobi A:
    height fractal: Ellipsoid
    colour fractal: StarG
    seed: 2097508729
Hosobi A a:
    height fractal: MountainsVolcano
    colour fractal: Desert
    seed: 139585229
Hosobi B:
    height fractal: Ellipsoid
    colour fractal: StarG
    seed: 2473717441
Hosobi B a:
    height fractal: HillsCraters2
    colour fractal: Rock
    seed: 4286993555
Hosobi B b:
    height fractal: RuggedDesert
    colour fractal: Desert
    seed: 2898156491
Hosobi B c:
    height fractal: Barren Rock 2
    colour fractal: Rock
    seed: 666147143
Hosobi A,B a 1:
    height fractal: Asteroid4
    colour fractal: Asteroid
    seed: 2851529373
Hosobi A,B a 2:
    height fractal: Barren Rock 3
    colour fractal: Rock
    seed: 4281332000
Hosobi A,B b 1:
    height fractal: Barren Rock 3
    colour fractal: Rock
    seed: 2986009267
Hosobi A,B b 2:
    height fractal: MountainsCraters2
    colour fractal: Rock
    seed: 3369114528
Hosobi A,B b 3:
    height fractal: MountainsCraters2
    colour fractal: Rock
    seed: 2489344644
Hosobi A,B b 4:
    height fractal: MountainsCraters2
    colour fractal: Rock
    seed: 694969596
Hosobi A,B b 5:
    height fractal: MountainsCraters2
    colour fractal: Rock
    seed: 1488627882
Stars picked from galaxy: 183416
Final stars number: 500000
Color Fractal name: GGSaturn
Color Fractal name: GGSaturn
Floating point exception
````

### Steps to reproduce
load game
[issue floating point exception.zip](https://github.com/pioneerspacesim/pioneer/files/6561635/issue.floating.point.exception.zip)
fastforward time
crash

__My pioneer version (and OS):__
Mint Cinnamon 20.1
20210513 (0c84df0)

**Comment by Damjan94** [comment]
This seems to be an issue with integer underflow/overflow in the [fastfloor](https://github.com/pioneerspacesim/pioneer/blob/1a8201a6edf22ea587b0796edf3412c0e27f3563/src/perlin.cpp#L56) function (the double x has a very larger value than the casting int could hold) called from [here](https://github.com/pioneerspacesim/pioneer/blob/1a8201a6edf22ea587b0796edf3412c0e27f3563/src/perlin.cpp#L118).
It happens when a ship is launching, presumably the enemy one that you have a mission to kill.
Interestingly, sometimes, when going to the system view, it manages to get past the crash, and I actually get to be owned by the incoming enemy :D

hope this helps the person fixing this :p

**Comment by impaktor** [comment]
Did #5204 fix this issue?

**Comment by Web-eWorks** [comment]
Going to mark this as closed, as I haven't run into the specific issue noted (likely a hardware/distro-specific bug).
