### ISSUE TITLE
Main window: Limited slots for flight mode buttons

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5320]
### Observed behaviour

At the bottom of the main window, only two ship flight mode buttons are visible

### Expected behaviour

All buttons shall be visible if available

### Steps to reproduce

Start new game
have a look to the main window
![Screenshot_20220111_150223](https://user-images.githubusercontent.com/60466586/148956929-dde1dbd7-661a-4f8b-bbdb-a856f91a4f61.png)
set a hyperjump route
have a look again
![Screenshot_20220111_150148](https://user-images.githubusercontent.com/60466586/148956960-5ae32181-208d-45f9-a3f2-3036af313820.png)

__My pioneer version (and OS):__
July stable on openSuSE Linux 15.3 and others

**Comment by nozmajner** [comment]
@Gliese852 You might want to take a look at this. Not sure if it is relevant to your flight modes stuff.
@Bodasey The flight modes will see a quite significant upgrade, and some of those buttons might even be removed/moved.

**Comment by Gliese852** [comment]
@Bodasey the problem is that these buttons lie on an invisible window, and it is configured so that its size is set automatically at the start of the game, when there are 2 buttons, if a third one appears, it pushes the one on the far right. I think I will fix it in the next few days, since I have to do a little button refactoring.
