### ISSUE TITLE
If you buy then sell a laser cooling booster lasers will stop cooling completely

### ISSUE THREAD

**Issue by aladar4** [pioneerspacesim/pioneer#5348]
### Observed behaviour

I swapped a Sinanotrix with a laser cooling booster for a Skipjack stripped of hardware. I installed all sorts of cannons and laser and weapons would not cool down anymore. 

### Expected behaviour

Weapons should cool down (heat meter decreases) even without a cooling booster installed.

### Steps to reproduce

Buy a laser cooling booster for your ship, then sell it (or lose it in a ship-trade). Weapons won't cool down anymore until you buy another cooling booster. You can try in the attached zipped savefile.

20220203 Win 7
[nnns17xxx.zip](https://github.com/pioneerspacesim/pioneer/files/8103251/nnns17xxx.zip)

**Comment by impaktor** [comment]
Was easy to reproduce:
- Start on Mars
- Ctrl-i give money to player
- buy laser cooler
- sell laser cooler
- take off, pew-pew-pew, no cooly-cooly

**Comment by impaktor** [comment]
I've skimmed through the code, looking at `laser_cooler`, `RemoveEquip`, and the like. 

I'm guessing `m_cooler_boost = 0` (instead of it's default value of 1, in absence of a cooler?) in `FixedGuns::UpdateGuns()` if one has sold a laser cooler. So `Ship::UpdateGunsStats` should set it back to 1, from lua, I'm guessing.
