### ISSUE TITLE
Hyperspace departure clouds accumulate

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5471]
Something who may be all right (future development?), but looks strange for me - what are these objects good for?

### Observed behaviour

Hyperspace departure clouds stay for an unnecessary long time, perhaps accumulate forever? Good to see when leaving spaceports:
![departure_cloud_echo](https://user-images.githubusercontent.com/60466586/212193436-847a72f4-130f-4cac-ba94-c8405d3f30b4.png)

### Expected behaviour

They are cleared after a while or when the hyperjump is completed from data.

_My pioneer version (and OS):__
actual master / long time observation

**Comment by nozmajner** [comment]
I noticed this too. Then I realized while playing that ai ships jump quite aren't beholden to the same jump distance restrictions as the player. Which I think adds to this issue. Maybe tradeships could instruct them to fly away in a random direction and jump when they are out of the restricted range? Might clean up the vicinity of the stations a bit.

**Comment by Web-eWorks** [comment]
Departure clouds remain for at least half duration of the jump IIRC, which can be up to a week long. The problem is that ships are jumping out within 1-2km of the station, when they should be waiting until they're at least 20-50km out to jump.

**Comment by Bodasey** [comment]
Ok, but what's the sense of these objects? I mean, why can a ship not jump without leaving a trace? Or, why is there no counterpart "Hyperspace arrive cloud", both permanent? Then, you had to fly into the cloud to initiate a hyperjump - and it would allow more arrive points in a system, e.g. near Neptune.

By the way: Players are also allowed to hyperjump 1 km away from a space station.

**Comment by nozmajner** [comment]
Departure cloud can be analyzed with an equipment to figure out the destination and arrival time if I'm correct. Not sure if any mission takes advantage of that, or it os even feasible, but in theory with the proper drive you could arrive before the target ship to intercept them. (At least that was the intention in Frontier and FFE, not sure if it worked even in them)

And there is an arrival cloud counterpart, but since the change in hyperspace you arrive at a relatively low orbit around the star. And because of that you fly away from it pretty fast.

**Comment by impaktor** [comment]
Yes, hypercloud analyzer are useful for assassination missions, thus we need the clouds for some time. Either to analyze exit cloud of ship that got away, or ship that's about to enter. I used them a lot in Frontier, (I can't remember for Pioneer, though. Been too long since last time), but assuming it works similarly here, as in Frontier, I'd expect the same usefulness

**Comment by Bodasey** [comment]
not observed any more (July 2024 stable)
