### ISSUE TITLE
disturbed docking sequence event

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5479]
### Observed behaviour

![Docksequenz](https://user-images.githubusercontent.com/60466586/213206485-328e2aa8-69c3-402e-8a53-bb0d2a6c5297.png)

and this can reproduce closed #4127

[_autosave4.txt](https://github.com/pioneerspacesim/pioneer/files/10447813/_autosave4.txt)

The first entry in "Missions" in this autosave game is one of the two not cleared ones.

### Steps to reproduce

I have no idea why or when this happens
what's this? parse_error.112

[output.txt](https://github.com/pioneerspacesim/pioneer/files/10447948/output.txt)

__My pioneer version (and OS):__
Web-eWorks station economy branch / long time observation

**Comment by Web-eWorks** [comment]
> what's this? parse_error.112

This is a benign error thrown when attempting to interpret a gzipped TAR file as a Pioneer savefile.

> I have no idea why or when this happens

This occurs because the order of evaluation of mission event handlers is non-deterministic at runtime. Thus, one mission completes before the event that triggers autosaves when docking, while the other two complete after an autosave.

There is a potential fix for this that may make it into the upcoming release.
