### ISSUE TITLE
Ship info screen shows wrong cargo capacity and usage.

### ISSUE THREAD

**Issue by dhouseholder** [pioneerspacesim/pioneer#5557]
### Observed behaviour
I have 16 tons of cargo in my hold.
The ship info screen says I have 8 tons of cargo capacity of which 0 are used.
![image](https://user-images.githubusercontent.com/116393228/220150467-69669557-ab29-4b02-b89c-c715df6f8cda.png)
![image](https://user-images.githubusercontent.com/116393228/220150595-097a86bf-1d17-4f23-a895-d80a9d0ec021.png)

### Expected behaviour
16 tons of cargo in hold, 16 tons cargo capacity, 16 tons used.

### Steps to reproduce

Issue is evident in this save file.
When starting the game I sold off some starter equipment. Not sure if that is related.
I am also wondering if this is the cause of #5554; could a police ship be trying to scan me but the cargo is corrupted?

[vert.zip](https://github.com/pioneerspacesim/pioneer/files/10785808/vert.zip)

__My pioneer version (and OS):__
e77da96 ; Windows and Steam Deck

**Comment by impaktor** [comment]
@dhouseholder can you confirm if the bug is only there after a save/load? (note: save/load bugs can behave differently depending on whether or not you close pioneer betwee the save/load).

**Comment by dhouseholder** [comment]
@impaktor The bug persists across executions of Pioneer and when loading the save file on separate Windows and Linux machines.

**Comment by Max5377** [comment]
Related #5534
Two ship's properties `totalCargo` and `usedCargo` wasn't initialized beyond constructor after loading the game.
Two fix it this lines needs to be added in `CargoManager:Unserialize()`:
```

self.ship:setprop("totalCargo", self:GetTotalSpace())
self.ship:setprop("usedCargo", self.usedCargoSpace)

self.ship:UpdateEquipStats() - don't know if this line is needed here, I put it as in CargoManager:OnShipTypeChanged()
```

**Comment by Max5377** [comment]
Here I list all occurences of `usedCargo` and `totalCargo` I could find, looks line they are all used only when "operating" with ship.
The only occurences in C++ of `usedCargo` I could find is in `static int l_ship_get_stats(lua_State *l)` in `LuaShip.cpp`. No occurences of `totalCargo` at all in C++.
In the lua:
`CargoManager:Constructor(ship)`:

```
-- Initialize property variables on owning ship for backwards compatibility
ship:setprop("totalCargo", self:GetTotalSpace())
ship:setprop("usedCargo", 0)
```
`CargoManager:OnShipTypeChanged()`:
```
self.ship:setprop("totalCargo", self:GetTotalSpace())
self.ship:setprop("usedCargo", self.usedCargoSpace)
```

`CargoManager:AddCommodity(type, count)`:
```
self.usedCargoSpace = self.usedCargoSpace + required_space
self.ship:setprop("usedCargo", self.usedCargoSpace)
```

`CargoManager:RemoveCommodity(type, count)`:
```
self.usedCargoSpace = self.usedCargoSpace - freed_space
self.ship:setprop("usedCargo", self.usedCargoSpace)
```

`EquipSet:__TriggerCallbacks(ship, slot)`:
```
ship:setprop("totalCargo", math.min(self.slots.cargo.__limit, ship.usedCargo+ship.freeCapacity))
```

`Pirates.lua OnEnterSystem`:
```
local probabilityPirateIsInterested = math.floor(player.usedCargo - discount) / math.max(1,  playerCargoCapacity - discount)
```

`TradeShips\Debug.lua debugView.registerTab('debug-trade-ships', function()`:
```
if ship:exists() then
table.insert(ships, {
	...
	cargo = ship.usedCargo,
        ...
})
```
`TradeShips\Trader.lua Trader.addEquip`:
```
assert(ship.usedCargo == 0, "equipment is only installed on an empty ship")
```

`target-scanner.lua`:
```
local cargo = stats.usedCargo
```

`01-ship-info.lua`:
```
{ l.CARGO_SPACE..":", string.format("%dt (%dt "..l.MAX..")", player.totalCargo, shipDef.equipSlotCapacity.cargo) },
{ l.CARGO_SPACE_USED..":", string.format("%dt (%dt "..l.FREE..")", player.usedCargo, player.totalCargo - player.usedCargo) },
```
`04-shipMarket.lua`:
```
if def.equipSlotCapacity.cargo < player.usedCargo or def.capacity < (player.usedCargo + hdrive) then
```

`system-view-ui.lua Windows.objectInfo:Show()`:
```
local body = obj.ref
...
elseif obj.ref:IsShip() then -- physical body
...
if player:GetEquipCountOccupied('target_scanner') > 0 or player:GetEquipCountOccupied('advanced_target_scanner') > 0 then
	...
	table.insert(data, { name = luc.CARGO, value = Format.MassTonnes(body:GetStats().usedCargo) })
end
```
Maybe we can get rid of them completely, since most of the time they can be replaced with an equivalent in CargoManager?
