### ISSUE TITLE
Multiple crashes in Liacecan

### ISSUE THREAD

**Issue by DynV** [pioneerspacesim/pioneer#5562]
### Observed behaviour
I crashed >= 5X in Liacecan. I thought my gamesave was corrupted considering the multiple crashes I had in the system Liacecan but there was no issue with the next system on my mission-filled path so it seems unlikely to be the case, and more likely the system somehow is causing an issue with either my instillation of the version, or the version itself.

### Expected behaviour
A couple crashes sometimes happen in a system, not that many.

### Steps to reproduce
1. Load the gamesave
2. roam Liacecan similar to me, hopping from station to station using the auto-pilot, you can also go back around its star which was problematic for me
3. with any unluck, you'll crash about as much as it did for me.

__My pioneer version (and OS):__
20230203-win

The attached file was simply renamed so it would go through the upload extension filter, there was no modification to the file content of my save-file.
[Pioneer-Yoan_Faure-20230203-230718-multiple_crashes_in_Liacecan.zip](https://github.com/pioneerspacesim/pioneer/files/10834896/Pioneer-Yoan_Faure-20230203-230718-multiple_crashes_in_Liacecan.zip)

**Comment by impaktor** [comment]
This is not just #5551? (I don't have access to pioneer atm, to double check the system/save).

**Comment by DynV** [comment]
> This is not just #5551?

The majority, if not all, crashes happened while having a frame of reference; < 1Mm from a planet >= 2X, close enough to a star it took > 1/2 my display >= 2X.

**Comment by craigo-** [comment]
The savegame won't even load for me. I get:

This warning:
![image](https://user-images.githubusercontent.com/4467963/221653727-d9375872-e028-4f31-9800-638ddb7b12a2.png)

This error (output looks the same as above):
![image](https://user-images.githubusercontent.com/4467963/221653866-a0e778cb-05ce-4e52-ac03-bb817158d5c3.png)

...and then two of these:
![image](https://user-images.githubusercontent.com/4467963/221653922-a692b695-54dc-488d-a781-bf07627eb770.png)

Pioneer 20230204 Release
Pioneer 20230213 master b4894e6f953357ca08563b706176fd44e5bc593f + PR #5551
Windows 10 Enterprise 22H2

**Comment by DynV** [comment]
What about my latest save, on the next system of my path?
[Pioneer-Yoan_Faure-20230203-230722-Gliese_851.zip](https://github.com/pioneerspacesim/pioneer/files/10843019/Pioneer-Yoan_Faure-20230203-230722-Gliese_851.zip)

**Comment by impaktor** [comment]
Neither of the saves work for me, I get the same error as @craigo-

**Comment by DynV** [comment]
Did the save from my previous (non-OP) post load?

**Comment by DynV** [comment]
Did the save from my previous (non-OP) post load? The version is the first # in the filename.

**Comment by craigo-** [comment]
I concur: both provided savegames produce the same sequence of errors.

**Comment by DynV** [comment]
I guess it's time to create a new game. 😞

**Comment by craigo-** [comment]
Might be a good idea.

NB: you can use the following to recreate your progress if you like; I've done that before after a savebump has rendered a previous save unusable. You won't get things like your flight logs, but you can recreate your money, ship, equipment, reputation etc.

https://wiki.pioneerspacesim.net/wiki/Lua_Console

**Comment by Web-eWorks** [comment]
Just as an FYI, providing your `output.txt` from a Lua error (generally, anything that pops up an error dialog) will give us a lot more information about what is happening and a much better chance of diagnosing it without having to go through the process of changing branches back to the release version to debug your specific savefile.

We do try to triage and address bugs in some semblance of a timely manner, but often I and other developers don't have the luxury of dropping / pausing our current development tasks to test each savefile, so anything that eases that process (whether it be other users attempting to recreate / reproduce the issue, or you providing enough information to diagnose the problem without needing to recreate it ourselves) will increase the chance that the bug is addressed in a timely manner.

Judging by the screenshot you've provided, there's a high chance you inadvertently have a mod that adds a new ship installed, but without the (very detailed) information from `output.txt` I cannot confirm that as the issue in question.

**Comment by DynV** [comment]
I renamed the directory before reinstalling 20230203-win, attached is from it. As for a mod...
>  Directory of C:\Users\[USER NAME]\OneDrive\Documents\Pioneer-issue_5562_closing\mods
> 
> 02/12/2023  04:09 PM    <DIR>          .
> 02/12/2023  04:09 PM    <DIR>          ..
>                0 File(s)              0 bytes
>                2 Dir(s)  17,689,210,880 bytes free

Perhaps I'm reading too much into it but I detect irritation in having to ask for the file, can't you install a bot and insert commands in your reply, ie your 1st 2 paragraphs could be respectively !output !timely
[output.txt](https://github.com/pioneerspacesim/pioneer/files/10858015/output.txt)

**Comment by Web-eWorks** [comment]
```
[23:18:11.280873] Info:     Ship Def found: ac33-3_sensors
```

This extra ShipDef is why your savefile will not load for any other player.

> Perhaps I'm reading too much into it but I detect irritation in having to ask for the file

There's no irritation at having to ask for the file, but I am attempting to address in the first two paragraphs the perceived expectation for something to be addressed or responded to immediately that I'm seeing in your communication across multiple platforms.

> can't you install a bot and insert commands in your reply, ie your 1st 2 paragraphs could be respectively !output !timely

You should read the issue template more closely. We already ask you to provide an output.txt with every single issue you open, and *specifically* ask for one in the case of crashes.

The only thing I need to type repeatedly is the third paragraph - I will not need to retype the first two again.

**Comment by DynV** [comment]
"ac33-3_sensors" was just a backup I copied ac33 then made changes to it, renaming the original (to something alike "ac33-original") and when I wasn't satisfied with the changes I reverted the original while keeping the changes. I uploaded multiple gamesave in which "ac33-3_sensors" was included (in my directory while the gamesave was being created).

**Comment by Web-eWorks** [comment]
> I uploaded multiple gamesave in which "ac33-3_sensors" was included (in my directory while the gamesave was being created).

Unfortunately, that file's presence still creates a valid ship type named "ac33-3_sensors", which is then used by the tradeships module and ships of that type are spawned in space. Those savegames are therefore incompatible with the release version, as an unrecoverable error will occur every time one of those ships is loaded during loading of the savegame.

On a more positive note, I've amended the issue template to more clearly request that `output.txt` be provided when creating a new issue, so that will hopefully clear up friction in that regard.

-----

Taking a wild stab in the dark for an issue post-mortem, it's possible that the root cause behind these crashes is related to ships being created from hyperspace entry clouds as they jump into the system from a previously-visited system. If I can spare the time in the coming days, I'll attempt to jump through the hoops to load the attached saves here and get a callstack from the crash, though if you can reproduce the issue with a "cleaner" save I'd much appreciate it. :smile:

**Comment by DynV** [comment]
> if you can reproduce the issue with a "cleaner" save I'd much appreciate it. 😄

I'll try to remember if I get > 2 crashes in a system.

**Comment by DynV** [comment]
> if you can reproduce the issue with a "cleaner" save I'd much appreciate it. 😄

I'll try to remember if I get > 2 crashes in a system. About the backup file:
```
$ diff -c /cygdrive/C/Program\ Files/Pioneer/data/ships/ac33.json /cygdrive/C/Users/[USER NAME]/OneDrive/Documents/Pioneer-20230203-1st_custom_log_after_issue_5562_closing-ac33-3_sensors.json
*** "/cygdrive/C/Program Files/Pioneer/data/ships/ac33.json"    Fri Feb  3 10:07:24 2023
--- /cygdrive/C/Users/[USER NAME]/OneDrive/Documents/Pioneer-20230203-1st_custom_log_after_issue_5562_closing-ac33-3_sensors.json     Sun Feb 12 16:15:31 2023
***************
*** 11,16 ****
--- 11,17 ----
        "atmospheric_pressure_limit": 7.9,
        "capacity": 920,
        "slots": {
+               "sensor": 3,
                "engine": 1,
                "cabin": 50,
                "laser_front": 1,
```
