### ISSUE TITLE
[Bug] Scans do not resume on game continue

### ISSUE THREAD

**Issue by VorTechnix** [pioneerspacesim/pioneer#5577]
When you close the game or go to main menu during an orbital scan it does not increase progress when you resume the game by clicking the "Continue Game" option in the main menu. I haven't tested this with geographical scan or with resuming from save files but it's probably the same.

In order to resume the scan you have to click on the active scan to move it to pending and then click on it again to move it back to active and then progress will increase again.

**Comment by impaktor** [comment]
Do you have a save?

**Comment by VorTechnix** [comment]
> Do you have a save?

The bug occurs on any save simply by exiting to main menu during an orbital scan and then resuming but here's a bugsave.

[_bugsave_scan_no_update.zip](https://github.com/pioneerspacesim/pioneer/files/11161699/_bugsave_scan_no_update.zip)

**Comment by DarioTD** [comment]
Same, but you can stop the current scanner then resume it again for it to increase again

**Comment by Web-eWorks** [comment]
Most likely caused by failure to register an update callback in `ScanManager.lua`.

**Comment by Max5377** [comment]
During serialization field `activeCallback` of `ScanManager` is saved.
Function `ScanManager:StartScanCallback()` has this check:
`if updateRate == self.activeCallback then`
which will return true, basically meaning that timer for callback is already setted up for `ScanManager`, which is not after loading the save.
To fix it we can simply swap value of `self.activeCallback` just before the call of `ScanManager:StartScanCallback()` in `ScanManager:Unserialize()`, or add argument to `ScanManager:StartScanCallback()`, like `wasUnserialized`, and change mentioned check to:
`if updateRate == self.activeCallback and not wasUnserialized then`
 to differenciate if call to `ScanManager:StartScanCallback()` was being made from `ScanManager:Unserialize()`.

**Comment by Web-eWorks** [comment]
I'd recommend modifying `ScanManager:StartScanCallback()` to take a `force` parameter defaulting to nil, and using it to bypass the `updateRate == self.activeCallback` check (your second proposed option). It's much cleaner and clearer than mucking with the value of `self.activeCallback`.

**Comment by Max5377** [comment]
Also I saw this `FIXME` in `ScanManager:Unserialize()`
```
-- FIXME: the order of component deserialization is undefined
-- The Unserialize() method should only mutate this component's state;
-- these calls should be deferred into a PostLoad() method or event
```
Do I understand right that we can register an event (ex. `onScanManagerUnserialized`) and queue it in `ScanManager:Unserialize()`?

**Comment by Web-eWorks** [comment]
> Do I understand right that we can register an event (ex. onScanManagerUnserialized) and queue it in ScanManager:Unserialize()?

This is currently unimplemented behavior, hence the FIXME nature of the comment. The ideal is for the body component architecture to provide a `PostLoadFixup` analogue for Lua components, so that the component serializers do not make any changes to "external" state during deserialization. It's not yet become a requirement (we currently only have ~2 Lua BodyComponents) so it remains a FIXME to be dealt with at a later time.

Yes, you could technically register event handlers and queue timers in the Unserialize method. It's very much not recommended unless absolutely necessary, as it can present a large number of ordering bugs where e.g. multiple components are trying to modify their parent body during the deserialization process.
