### ISSUE TITLE
Visual Studio CMake build only supports Debug, not release or profiling

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#5683]
### Observed behaviour
Opening the CMake project with Visual Studio (2019) does not allow you to build or run Pioneer in anything other than Debug.

![image](https://github.com/pioneerspacesim/pioneer/assets/825083/2203acd3-b1ce-49df-a00a-9ae937687d27)

### Steps to reproduce
Open the CMake project in Visual Studio 2019, and possibly other versions.

There is a possible answer here although I do not understand CMake well enough to figure out how to fix it.
https://stackoverflow.com/a/24470998

**Comment by Web-eWorks** [comment]
CC @JonBooth78 - unsure how the CMakePresets feature interacts with Visual Studio but I believe this is something that should be possible?

**Comment by JonBooth78** [comment]
Odd, it was working for me last time I tried. I'm on a campsite right now for another week but should be able to give it a go on my laptop soon

**Comment by JonBooth78** [comment]
Ok, so with my workflow, where I open Visual Studio 2019 and then point at the pioneer folder (sibling to the pioneer thirdparty folder), what I've discovered is that Visual Studio 2019 doesn't like our `CMakePresets.txt`.  

Works just fine if you edit it and remove all the `linux` configurations.

Also it works just fine with the same workflow and no modifications in Visual Studio 2022.

So there's something in there that VS2019 isn't playing nice with.

I must admit, I've recently been using the CMake GUI to build native visual studio 2022 solutions and then using that - because I found that ctrl-F7 to rebuild just the current source file didn't work with the CMake configuration and I think (hazy now) I wanted to mess with some compiler flags for some local reason I can no longer remember.

If I get time in the next couple of days I'll try and work out what's tripping up VS2019.  However, I accidentally told VS2019 to update itself and the 4G/wifi on this campsite sucks, especially as more and more people turn up for the New Year party in a couple nights.  Otherwise it might be next week/year before I get to properly look into this.

Sorry.

**Comment by fluffyfreak** [comment]
@JonBooth78 tht's great info thanks, I've decided to switch/update to 2022 and that works with them being available in the configuration dropdown 👍 

![image](https://github.com/pioneerspacesim/pioneer/assets/825083/08e886db-5598-48ec-a136-08b9ea161124)

Thanks, this should do for me and is probably a bug within the VS2019 CMake support

**Comment by Max5377** [comment]
VS2019 shows error that `generator` field is missing. If added back to all `linux` configurations (which was removed by 158672a88f52dce3a3e36f5c3826bc7290f682c5) this will fix it too.
Personally, I just copied it from `Windows` configurations.

**Comment by Web-eWorks** [comment]
Per discussion (read: lack of complaints) on IRC, I'll be resolving this by defaulting the CMakePresets.json file to use the Ninja generator. This setting can still be overridden by invoking CMake from the command line, but VSCode in my testing didn't want to use the user's explicitly-set generator value in combination with presets so the original reason for removing the generator setting is moot.
