### ISSUE TITLE
Reproducible crash shortly after jumping to next star, autopiloting to starbase

### ISSUE THREAD

**Issue by mikehgentry** [pioneerspacesim/pioneer#5712]
### Observed behaviour

Reproducible crash.

Let me know if crash reports from the Steam Deck aren't useful of course, but for now I'll assume it's helpful if they're reproducible.

### Expected behaviour

Gets to Red Cloud without crashing

### Steps to reproduce

From this saved game, fill up with conventional fuel at the station, launch, and hyperspace to Fomalhaut. It's right next to where you are.

When you arrive, set autopilot to dock at Red Cloud, and accelerate time to max. On my Deck it crashes every time.

It is possible to get to Red Cloud, by for example jumping somewhere else first, or by flying towards Fomalhaut for a bit before heading towards Red Cloud.

__My pioneer version (and OS):__

20231206 (from flatpak), SteamOS 3.5.7

__My output.txt (required) and game save (optional, but recommended)__
[_quicksave.txt](https://github.com/pioneerspacesim/pioneer/files/13924189/_quicksave.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/13924191/output.txt)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/13924194/opengl.txt)

**Comment by mikehgentry** [comment]
[terminaloutput.txt](https://github.com/pioneerspacesim/pioneer/files/13924567/terminaloutput.txt)

**Comment by Gliese852** [comment]
I think, in general, crashes from the steamdeck are useful, but the flatpak version is quite outdated (relative to the "unstable" branch), and this bug was fixed a long time ago, in #5564.

**Comment by mikehgentry** [comment]
OK, thanks.

Not that I don't believe you, I'm just rather new to using flatpaks and confused: any idea why it says 20231206 on the title screen if it's an old build? 

The way I installed it was just to run "flatpak install net.pioneerspacesim.Pioneer" from a terminal

**Comment by nozmajner** [comment]
Could you post a screenshot of the main menu? There were changes there in the last couple of months, so it whould help to see if it is a build of master or flathub just rebuilt it recently for some reason.

**Comment by mikehgentry** [comment]
![372917_20240113154848_1](https://github.com/pioneerspacesim/pioneer/assets/1724168/e43e00a9-64e5-4f44-b7cd-29e8491fdaa7)

**Comment by hexagonrecursion** [comment]
flathub follows **stable** releases. It is their standard policy. [Currently the latest flatpak from flathub uses 20230203](https://github.com/flathub/net.pioneerspacesim.Pioneer/blob/b815ec543bcfbe75d9b164e0a0775dcc0b0116f2/net.pioneerspacesim.Pioneer.json#L74C75-L74C83) - the latest stable release of pioneer. As far as I understand this **is** what we want because save file compatibility between different builds of the unstable master branch is not guaranteed. 

"20231206" likely comes from this line in CMakeLists.txt:

https://github.com/pioneerspacesim/pioneer/blob/5e7314b21f095d40e0f00fae31442772655759e1/CMakeLists.txt#L121

As long as we use the current date and time **from the build machine** to decide "version", the "version" of the game from flathub or any other downstream distribution is not going to be useful.

**Comment by Gliese852** [comment]
Yes, I raised a discussion about this problem with the version a couple of times, in some distributions this is being patched, I hope to fix it for the next release.

**Comment by mikehgentry** [comment]
Are you hoping for another stable release early February? I'm not sure I'm feeling brave enough to try to cross compile it at the moment...

**Comment by nozmajner** [comment]
Yes, mark the 3rd of February in all your calendars!
Until that you could try one of the gihub builds from the [changelog update PR](https://github.com/pioneerspacesim/pioneer/actions/runs/7458290920) for example.
