### ISSUE TITLE
Impossible mission

### ISSUE THREAD

**Issue by SomenameIchose** [pioneerspacesim/pioneer#5803]
### Observed behaviour
An impossible mission is generated, namely "cartography order of Venus".
I have to update a data for Venus at an altitude of 533m which is completely impossible to do because of extreme atmo pressure.
My shield is ruined at 35km even if I have a heavy one.
![screenshot-20240320-194301](https://github.com/pioneerspacesim/pioneer/assets/154741968/3473ca23-941a-47fe-95e9-86bf971a7357)
![screenshot-20240320-194331](https://github.com/pioneerspacesim/pioneer/assets/154741968/2999127a-042d-41b1-8d2c-37f468c2e7e3)
![screenshot-20240320-194403](https://github.com/pioneerspacesim/pioneer/assets/154741968/8fbfe419-ef42-4e98-bc93-75eaada3801c)
![screenshot-20240320-194810](https://github.com/pioneerspacesim/pioneer/assets/154741968/ba37e930-68b0-43b7-b511-48ac9478afc2)
![screenshot-20240320-194814](https://github.com/pioneerspacesim/pioneer/assets/154741968/0f17f76c-678d-4c5c-95d5-c80cd88285dc)

### Expected behaviour
An impossible missions shouldn't be generated.

### Steps to reproduce
Check out your Bulletin board.

__My pioneer version (and OS):__
ver 20240314 (8b6ae92)

__My output.txt (required) and game save (optional, but recommended)__

[output.txt](https://github.com/pioneerspacesim/pioneer/files/14669315/output.txt)
[save.zip](https://github.com/pioneerspacesim/pioneer/files/14669359/save.zip)

**Comment by Web-eWorks** [comment]
Fixed in #5841, missions now have an upper bound on atmosphere and inform the player if there is a potentially-dangerous amount of atmospheric pressure or gravity.

Note that mission generation does not take your current ship's configuration into account - the game no longer generates surface scan missions that are impossible to complete with *any* ship but does not guarantee that you can take a contract without double-checking if *your* ship can sustain the pressure or gravitational requirements of the target body.
