### ISSUE TITLE
Combat mission can fail even though the status shows "Completed"

### ISSUE THREAD

**Issue by lolo101** [pioneerspacesim/pioneer#5890]
Not a bug, maybe a feature request?

### Observed behaviour

In Combat mission where you have to fight some ruffian, after they are eliminated the mission status shows "Complete" even though I have not claimed my payment yet
![image](https://github.com/user-attachments/assets/7a459ad4-bfeb-4b59-a911-67aa90f4cba9)

However, if I fail to claim the payment either by entering the specified system or docking to a valid station before the due date the mission has failed!

### Expected behaviour

Once a mission status is Complete, it should not fail. Maybe another status should be introduced? Like "Payment awaiting" or something like that so the player understands the clock is still ticking :slightly_smiling_face: 
Or still "Active" but the mission wording states clearly that the payment needs to be claimed before the due date

### Steps to reproduce

Take any Combat mission
Load the saved game
=> The mission status is "Completed"
Wait for the due date to expire
Go claim the payment
=> The mission has failed

__My pioneer version (and OS):__
20240710 (Linux)

__My output.txt (required) and game save (optional, but recommended)__
[output.txt](https://github.com/user-attachments/files/16652791/output.txt)
[mission completed.gz](https://github.com/user-attachments/files/16652792/mission.completed.gz)

**Comment by impaktor** [comment]
If player is given the impression that they don't need to go back to the station before due date, due to wording of the mission, then it's bug-territory.

Fix:
- either we re-word mission
- move deadline check to when it's "completed" rather than when it's "landed at correct station to pick up payment".

Remind me: does not other missions flip to "completed" when heading back to collect payment? Or they no longer have a deadline when in "completed"-state? Looks like other missions with "completed" state are:
- assassination
- scoop
- scout

**Comment by Bodasey** [comment]
The Status column is updated only when you are docked, not dynamically during flight, and this is the case for all type of missions (tested delivery, freight, scanning).
